// Budget update pipeline — reads Finance Dept PDF tables and patches DEPARTMENTS[].budget_cr.
// Run manually after TN Budget presentation (February/March each year).
// Usage: npx ts-node lib/etl/budget-updater.ts --year 2025 --dry-run

import type { Department } from '@/types'

// Manual input: paste extracted values from Budget Demands for Grants PDF.
// Keys are dept slugs matching DEPARTMENTS[].slug.
// Values are in crores (convert from lakhs in PDF: ÷100).
export type BudgetInput = {
  slug: string
  budget_cr: number           // Total budget outlay (Revenue + Capital)
  revenue_cr: number          // Own revenue receipts
  central_funding_pct: number // Percentage of budget from Centre
  year: string                // e.g. "2024-25"
  source_ref: string          // Demand No. or Major Head ref from PDF
}

export type UpdateResult = {
  slug: string
  old_budget_cr: number
  new_budget_cr: number
  change_pct: number
  action: 'updated' | 'no_change' | 'not_found'
}

export function validateBudgetInput(inputs: BudgetInput[]): string[] {
  const errors: string[] = []
  const slugsSeen = new Set<string>()
  for (const inp of inputs) {
    if (slugsSeen.has(inp.slug)) {
      errors.push(`Duplicate slug: ${inp.slug}`)
    }
    slugsSeen.add(inp.slug)
    if (inp.budget_cr <= 0) {
      errors.push(`${inp.slug}: budget_cr must be positive (got ${inp.budget_cr})`)
    }
    if (inp.central_funding_pct < 0 || inp.central_funding_pct > 100) {
      errors.push(`${inp.slug}: central_funding_pct out of range (got ${inp.central_funding_pct})`)
    }
    if (!inp.year.match(/^\d{4}-\d{2}$/)) {
      errors.push(`${inp.slug}: year must be "YYYY-YY" format (got ${inp.year})`)
    }
  }
  return errors
}

export function computeUpdates(
  departments: Department[],
  inputs: BudgetInput[],
): UpdateResult[] {
  return inputs.map(inp => {
    const dept = departments.find(d => d.slug === inp.slug)
    if (!dept) {
      return { slug: inp.slug, old_budget_cr: 0, new_budget_cr: inp.budget_cr, change_pct: 0, action: 'not_found' }
    }
    const changePct = dept.budget_cr > 0
      ? ((inp.budget_cr - dept.budget_cr) / dept.budget_cr) * 100
      : 100
    const action: UpdateResult['action'] = inp.budget_cr === dept.budget_cr ? 'no_change' : 'updated'
    return {
      slug: inp.slug,
      old_budget_cr: dept.budget_cr,
      new_budget_cr: inp.budget_cr,
      change_pct: Math.round(changePct * 10) / 10,
      action,
    }
  })
}

export function generatePatchComment(results: UpdateResult[], year: string): string {
  const updated = results.filter(r => r.action === 'updated')
  const notFound = results.filter(r => r.action === 'not_found')
  const lines: string[] = [
    `// Budget patch for ${year} — generated by lib/etl/budget-updater.ts`,
    `// Run date: ${new Date().toISOString().slice(0, 10)}`,
    `// Updated: ${updated.length} departments | Not found: ${notFound.length}`,
    '',
  ]
  for (const r of updated) {
    const direction = r.change_pct > 0 ? '+' : ''
    lines.push(`// ${r.slug}: ₹${r.old_budget_cr.toLocaleString('en-IN')} Cr → ₹${r.new_budget_cr.toLocaleString('en-IN')} Cr (${direction}${r.change_pct}%)`)
  }
  if (notFound.length > 0) {
    lines.push('', '// WARNING — slugs not found in DEPARTMENTS:')
    for (const r of notFound) {
      lines.push(`//   ${r.slug} — add new department entry or fix slug`)
    }
  }
  return lines.join('\n')
}

// Summarize budget changes for admin dashboard display
export function summariseBudgetDelta(results: UpdateResult[]): {
  total_increase_cr: number
  total_decrease_cr: number
  largest_increase: UpdateResult | null
  largest_decrease: UpdateResult | null
  not_found_count: number
} {
  const updated = results.filter(r => r.action === 'updated')
  const increases = updated.filter(r => r.change_pct > 0)
  const decreases = updated.filter(r => r.change_pct < 0)
  return {
    total_increase_cr: increases.reduce((s, r) => s + (r.new_budget_cr - r.old_budget_cr), 0),
    total_decrease_cr: Math.abs(decreases.reduce((s, r) => s + (r.new_budget_cr - r.old_budget_cr), 0)),
    largest_increase: increases.sort((a, b) => b.change_pct - a.change_pct)[0] ?? null,
    largest_decrease: decreases.sort((a, b) => a.change_pct - b.change_pct)[0] ?? null,
    not_found_count: results.filter(r => r.action === 'not_found').length,
  }
}
