import { Department } from '@/types'

export const DEPARTMENTS: Department[] = [
  {
    id: 'health', code: 'HEALTH', name_en: 'Health & Family Welfare', name_ta: 'சுகாதாரம் & குடும்ப நலன்',
    slug: 'health', dept_type: 'welfare', established_year: 1921,
    purpose_en: 'Provides free healthcare through 2,780 government hospitals and 1,776 PHCs. No citizen is denied treatment due to inability to pay.',
    purpose_ta: '2,780 அரசு மருத்துவமனைகள் மற்றும் 1,776 PHC-கள் மூலம் இலவச சுகாதார சேவை.',
    citizens_served_en: '8 crore citizens of Tamil Nadu', citizens_served_ta: 'தமிழ்நாட்டின் 8 கோடி குடிமக்கள்',
    budget_cr: 21000, revenue_cr: 1200, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 120000, total_staff_filled: 94000,
    current_secretary_en: 'Additional Chief Secretary, Health & FW Dept',
    flag_count_red: 3, flag_count_amber: 2, flag_count_green: 2,
    description_en: 'Runs 2,780 government hospitals, 1,776 PHCs, and the CMCHIS health insurance scheme covering 1.75 crore families.',
    description_ta: '2,780 அரசு மருத்துவமனைகள், 1,776 PHC-கள் மற்றும் 1.75 கோடி குடும்பங்களுக்கான CMCHIS திட்டம்.',
  },
  {
    id: 'education', code: 'EDU', name_en: 'School Education', name_ta: 'பள்ளிக் கல்வி',
    slug: 'education', dept_type: 'welfare', established_year: 1948,
    purpose_en: 'Manages 37,000+ government schools and runs mid-day meals, CM Breakfast Scheme, Puthumai Penn, and scholarships for SC/ST students.',
    purpose_ta: '37,000+ அரசு பள்ளிகள். மதிய உணவு, CM காலை உணவு, புதுமைப் பெண் திட்டம் மற்றும் SC/ST மாணவர் உதவித்தொகை.',
    citizens_served_en: '66 lakh students in government schools', citizens_served_ta: '66 லட்சம் மாணவர்கள்',
    budget_cr: 56000, revenue_cr: 800, central_funding_pct: 35, state_funding_pct: 65,
    total_staff_sanctioned: 450000, total_staff_filled: 412000,
    current_secretary_en: 'Principal Secretary, School Education Dept',
    flag_count_red: 3, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 37,000+ government schools. Runs mid-day meals, Puthumai Penn, CM Breakfast Scheme, and scholarships for SC/ST students.',
    description_ta: '37,000+ அரசு பள்ளிகள். மதிய உணவு, புதுமைப் பெண், CM காலை உணவு திட்டம்.',
  },
  {
    id: 'revenue', code: 'REVENUE', name_en: 'Revenue & Disaster Management', name_ta: 'வருவாய் & பேரிடர் மேலாண்மை',
    slug: 'revenue', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Manages land records, property registration, patta transfers, district administration, and disaster relief operations across Tamil Nadu.',
    purpose_ta: 'நில ஆவணங்கள், சொத்து பதிவு, பட்டா மாற்றம், மாவட்ட நிர்வாகம் மற்றும் பேரிடர் நிவாரணம்.',
    citizens_served_en: 'All 8 crore TN citizens', citizens_served_ta: 'அனைத்து 8 கோடி குடிமக்கள்',
    budget_cr: 8200, revenue_cr: 23370, central_funding_pct: 10, state_funding_pct: 90,
    total_staff_sanctioned: 85000, total_staff_filled: 74000,
    current_secretary_en: 'Additional Chief Secretary, Revenue Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages land records, property registration, patta transfers, district administration, and disaster relief funds.',
    description_ta: 'நில ஆவணங்கள், சொத்து பதிவு, பட்டா மாற்றம், மாவட்ட நிர்வாகம்.',
  },
  {
    id: 'pwd', code: 'PWD', name_en: 'Public Works Department', name_ta: 'பொதுப்பணி துறை',
    slug: 'pwd', dept_type: 'infrastructure', established_year: 1853,
    purpose_en: 'Builds and maintains 67,000 km of state highways, bridges, irrigation canals, and government buildings across Tamil Nadu.',
    purpose_ta: '67,000 கி.மீ. மாநில நெடுஞ்சாலைகள், பாலங்கள், நீர்ப்பாசன கால்வாய்கள் மற்றும் அரசு கட்டிடங்கள்.',
    citizens_served_en: 'All TN citizens — roads, bridges, irrigation', citizens_served_ta: 'அனைத்து குடிமக்கள் — சாலைகள், பாலங்கள்',
    budget_cr: 18500, revenue_cr: 450, central_funding_pct: 25, state_funding_pct: 75,
    total_staff_sanctioned: 65000, total_staff_filled: 54000,
    current_secretary_en: 'Principal Secretary, Public Works Dept',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: 'Builds and maintains 67,000 km of state highways, bridges, and government buildings across Tamil Nadu.',
    description_ta: '67,000 கி.மீ. மாநில நெடுஞ்சாலைகள், பாலங்கள் மற்றும் அரசு கட்டிடங்கள்.',
  },
  {
    id: 'welfare', code: 'WELFARE', name_en: 'Social Welfare & Women', name_ta: 'சமூக நலன் & மகளிர்',
    slug: 'welfare', dept_type: 'welfare', established_year: 1956,
    purpose_en: 'Runs Kalaignar Magalir Urimai (₹1,000/month to 1.15 crore women), widow pensions, anganwadi centres, and women safety programmes.',
    purpose_ta: 'கலைஞர் மகளிர் உரிமை திட்டம் (1.15 கோடி பெண்களுக்கு மாதம் ₹1,000), விதவை ஓய்வூதியம், அங்கன்வாடி மையங்கள்.',
    citizens_served_en: '1.15 crore women under Magalir Urimai', citizens_served_ta: '1.15 கோடி மகளிர் உரிமை பயனாளிகள்',
    budget_cr: 22400, revenue_cr: 200, central_funding_pct: 40, state_funding_pct: 60,
    total_staff_sanctioned: 95000, total_staff_filled: 82000,
    current_secretary_en: 'Principal Secretary, Social Welfare Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Runs Kalaignar Magalir Urimai (₹1,000/month to 1.15 crore women), widow pensions, anganwadi centres, and women hostels.',
    description_ta: 'கலைஞர் மகளிர் உரிமைத் திட்டம் (1.15 கோடி பெண்களுக்கு மாதம் ₹1,000), விதவை ஓய்வூதியம்.',
  },
  {
    id: 'tasmac', code: 'TASMAC', name_en: 'Prohibition & Excise (TASMAC)', name_ta: 'மதுவிலக்கு & கலால் (TASMAC)',
    slug: 'tasmac', dept_type: 'revenue', established_year: 1983,
    purpose_en: 'Operates 4,928 TASMAC retail outlets — the sole legal liquor channel in TN. Generates ₹12,247 Cr annually that funds welfare schemes.',
    purpose_ta: '4,928 TASMAC கடைகள் — TN-ல் சட்டப்பூர்வமான ஒரே மது விற்பனை சேனல். ஆண்டுக்கு ₹12,247 கோடி வருமானம்.',
    citizens_served_en: 'Revenue to fund state welfare programmes', citizens_served_ta: 'மாநில திட்டங்களுக்கு வருவாய்',
    budget_cr: 1800, revenue_cr: 12247, central_funding_pct: 0, state_funding_pct: 100,
    total_staff_sanctioned: 38000, total_staff_filled: 35000,
    current_secretary_en: 'Commissioner, Prohibition & Excise',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: 'Operates 4,928 TASMAC retail outlets — the sole legal liquor channel in TN. Generates ₹12,247 Cr annually.',
    description_ta: '4,928 TASMAC கடைகள் — TN-ல் சட்டப்பூர்வமான ஒரே மது விற்பனை சேனல்.',
  },
  {
    id: 'transport', code: 'TRANSPORT', name_en: 'Transport (TNSTC)', name_ta: 'போக்குவரத்து (TNSTC)',
    slug: 'transport', dept_type: 'infrastructure', established_year: 1972,
    purpose_en: '21,600 buses carrying 2.5 crore passengers daily. Operates free bus pass for women, students, and differently-abled citizens.',
    purpose_ta: '21,600 பேருந்துகள் தினமும் 2.5 கோடி பயணிகள். பெண்கள், மாணவர்களுக்கு இலவச பாஸ்.',
    citizens_served_en: '2.5 crore daily passengers', citizens_served_ta: 'தினமும் 2.5 கோடி பயணிகள்',
    budget_cr: 9400, revenue_cr: 8200, central_funding_pct: 20, state_funding_pct: 80,
    total_staff_sanctioned: 155000, total_staff_filled: 142000,
    current_secretary_en: 'Secretary, Transport Dept',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: '21,600 buses carrying 2.5 crore passengers daily. Free bus pass for women, students, and differently-abled citizens.',
    description_ta: '21,600 பேருந்துகள் தினமும் 2.5 கோடி பயணிகள். பெண்கள், மாணவர்களுக்கு இலவச பாஸ்.',
  },
  {
    id: 'energy', code: 'ENERGY', name_en: 'Energy (TANGEDCO)', name_ta: 'ஆற்றல் (TANGEDCO)',
    slug: 'energy', dept_type: 'infrastructure', established_year: 1957,
    purpose_en: 'Supplies electricity to 3.5 crore connections. Provides 100 free units to domestic consumers. State absorbs ₹14,442 Cr of TANGEDCO losses annually.',
    purpose_ta: '3.5 கோடி இணைப்புகளுக்கு மின்சாரம். வீட்டு நுகர்வோருக்கு 100 இலவச யூனிட்.',
    citizens_served_en: '3.5 crore electricity connections', citizens_served_ta: '3.5 கோடி மின் இணைப்புகள்',
    budget_cr: 14442, revenue_cr: 70000, central_funding_pct: 15, state_funding_pct: 85,
    total_staff_sanctioned: 98000, total_staff_filled: 86000,
    current_secretary_en: 'Chairman & Managing Director, TANGEDCO',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 0,
    description_en: 'Supplies electricity to 3.5 crore connections. Provides 100 free units to domestic consumers. State absorbs ₹14,442 Cr of TANGEDCO losses.',
    description_ta: '3.5 கோடி இணைப்புகளுக்கு மின்சாரம். 100 இலவச யூனிட். ₹14,442 கோடி TANGEDCO நஷ்டம்.',
  },
  {
    id: 'finance', code: 'FINANCE', name_en: 'Finance Department', name_ta: 'நிதித்துறை',
    slug: 'finance', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Controls the entire state budget. All department spending requires Finance concurrence. Manages borrowing, debt, salaries, and pensions for 10 lakh government employees.',
    purpose_ta: 'மொத்த மாநில பட்ஜெட்டை கட்டுப்படுத்துகிறது. 10 லட்சம் அரசு ஊழியர்களுக்கு சம்பளம் மற்றும் ஓய்வூதியம்.',
    citizens_served_en: 'All TN citizens — manages entire state budget', citizens_served_ta: 'அனைத்து குடிமக்கள் — மாநில பட்ஜெட் மேலாண்மை',
    budget_cr: 439293, revenue_cr: 311000, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 12000, total_staff_filled: 10800,
    current_secretary_en: 'Additional Chief Secretary & Finance Secretary',
    flag_count_red: 3, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Controls the entire state budget. Manages borrowing, debt, salaries, and pensions for 10 lakh government employees.',
    description_ta: 'மொத்த மாநில பட்ஜெட்டை கட்டுப்படுத்துகிறது. 10 லட்சம் அரசு ஊழியர்களுக்கு சம்பளம்.',
  },
  {
    id: 'municipal', code: 'MUNI', name_en: 'Municipal Administration', name_ta: 'நகராட்சி நிர்வாகம்',
    slug: 'municipal', dept_type: 'infrastructure', established_year: 1920,
    purpose_en: 'Manages 21 corporations, 138 municipalities — water supply, sewerage, solid waste, and urban roads for 3.8 crore urban citizens.',
    purpose_ta: '21 மாநகராட்சிகள், 138 நகராட்சிகள் — 3.8 கோடி நகர்ப்புற குடிமக்களுக்கு நீர், கழிவுநீர் மேலாண்மை.',
    citizens_served_en: '3.8 crore urban citizens', citizens_served_ta: '3.8 கோடி நகர்ப்புற குடிமக்கள்',
    budget_cr: 11200, revenue_cr: 6400, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 72000, total_staff_filled: 61000,
    current_secretary_en: 'Principal Secretary, Municipal Administration Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 21 corporations, 138 municipalities — water supply, sewerage, solid waste, and urban roads for 3.8 crore urban citizens.',
    description_ta: '21 மாநகராட்சிகள், 138 நகராட்சிகள் — 3.8 கோடி நகர்ப்புற குடிமக்களுக்கு நீர் மற்றும் திட கழிவு மேலாண்மை.',
  },
  {
    id: 'police', code: 'POLICE', name_en: 'Home (Police & Security)', name_ta: 'உள்துறை (காவல்)',
    slug: 'police', dept_type: 'administration', established_year: 1861,
    purpose_en: '1.35 lakh police personnel handling law enforcement, crime investigation, traffic management, coastal security, and prisons.',
    purpose_ta: '1.35 லட்சம் காவல் துறையினர். சட்ட அமலாக்கம், குற்றவியல் விசாரணை, போக்குவரத்து மேலாண்மை.',
    citizens_served_en: 'All 8 crore TN citizens', citizens_served_ta: 'அனைத்து 8 கோடி குடிமக்கள்',
    budget_cr: 16200, revenue_cr: 380, central_funding_pct: 15, state_funding_pct: 85,
    total_staff_sanctioned: 160000, total_staff_filled: 135000,
    current_secretary_en: 'Director General of Police',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: '1.35 lakh police personnel. Law enforcement, crime investigation, traffic management, coastal security, and prisons.',
    description_ta: '1.35 லட்சம் காவல் துறையினர். சட்ட அமலாக்கம், குற்றவியல் விசாரணை.',
  },
  {
    id: 'agriculture', code: 'AGRI', name_en: 'Agriculture & Farmers Welfare', name_ta: 'வேளாண்மை & விவசாயி நலன்',
    slug: 'agriculture', dept_type: 'welfare', established_year: 1947,
    purpose_en: 'Supports 82 lakh farmers with crop insurance, certified seeds, fertiliser subsidies, irrigation support, and price protection mechanisms.',
    purpose_ta: '82 லட்சம் விவசாயிகளுக்கு பயிர் காப்பீடு, சான்றளிக்கப்பட்ட விதைகள், உர மானியம் மற்றும் நீர்ப்பாசன ஆதரவு.',
    citizens_served_en: '82 lakh farmers', citizens_served_ta: '82 லட்சம் விவசாயிகள்',
    budget_cr: 12800, revenue_cr: 2100, central_funding_pct: 40, state_funding_pct: 60,
    total_staff_sanctioned: 48000, total_staff_filled: 38000,
    current_secretary_en: 'Principal Secretary, Agriculture Dept',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Supports 82 lakh farmers with crop insurance, certified seeds, fertiliser subsidies, and price protection.',
    description_ta: '82 லட்சம் விவசாயிகளுக்கு பயிர் காப்பீடு, சான்றளிக்கப்பட்ட விதைகள் மற்றும் உர மானியம்.',
  },
]

export function getDeptsByType(type: string): Department[] {
  if (type === 'all') return DEPARTMENTS
  return DEPARTMENTS.filter(d => d.dept_type === type)
}

export function getDeptBySlug(slug: string): Department | undefined {
  return DEPARTMENTS.find(d => d.slug === slug)
}

export function formatCr(cr: number): string {
  if (cr >= 100000) return `₹${(cr / 100000).toFixed(2)}L Cr`
  return `₹${cr.toLocaleString('en-IN')} Cr`
}
