import { Department } from '@/types'

export const DEPARTMENTS: Department[] = [
  {
    id: 'health', code: 'HEALTH', name_en: 'Health & Family Welfare', name_ta: 'சுகாதாரம் & குடும்ப நலன்',
    slug: 'health', dept_type: 'welfare', established_year: 1921,
    purpose_en: 'Provides free healthcare through 2,780 government hospitals and 1,776 PHCs. No citizen is denied treatment due to inability to pay.',
    purpose_ta: '2,780 அரசு மருத்துவமனைகள் மற்றும் 1,776 PHC-கள் மூலம் இலவச சுகாதார சேவை.',
    citizens_served_en: '8 crore citizens of Tamil Nadu', citizens_served_ta: 'தமிழ்நாட்டின் 8 கோடி குடிமக்கள்',
    budget_cr: 21000, revenue_cr: 1200, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 120000, total_staff_filled: 94000,
    current_secretary_en: 'Additional Chief Secretary, Health & FW Dept',
    flag_count_red: 3, flag_count_amber: 2, flag_count_green: 2,
    description_en: 'Runs 2,780 government hospitals, 1,776 PHCs, and the CMCHIS health insurance scheme covering 1.75 crore families.',
    description_ta: '2,780 அரசு மருத்துவமனைகள், 1,776 PHC-கள் மற்றும் 1.75 கோடி குடும்பங்களுக்கான CMCHIS திட்டம்.',
  },
  {
    id: 'education', code: 'EDU', name_en: 'School Education', name_ta: 'பள்ளிக் கல்வி',
    slug: 'education', dept_type: 'welfare', established_year: 1948,
    purpose_en: 'Manages 37,000+ government schools and runs mid-day meals, CM Breakfast Scheme, Puthumai Penn, and scholarships for SC/ST students.',
    purpose_ta: '37,000+ அரசு பள்ளிகள். மதிய உணவு, CM காலை உணவு, புதுமைப் பெண் திட்டம் மற்றும் SC/ST மாணவர் உதவித்தொகை.',
    citizens_served_en: '66 lakh students in government schools', citizens_served_ta: '66 லட்சம் மாணவர்கள்',
    budget_cr: 56000, revenue_cr: 800, central_funding_pct: 35, state_funding_pct: 65,
    total_staff_sanctioned: 450000, total_staff_filled: 412000,
    current_secretary_en: 'Principal Secretary, School Education Dept',
    flag_count_red: 3, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 37,000+ government schools. Runs mid-day meals, Puthumai Penn, CM Breakfast Scheme, and scholarships for SC/ST students.',
    description_ta: '37,000+ அரசு பள்ளிகள். மதிய உணவு, புதுமைப் பெண், CM காலை உணவு திட்டம்.',
  },
  {
    id: 'revenue', code: 'REVENUE', name_en: 'Revenue & Disaster Management', name_ta: 'வருவாய் & பேரிடர் மேலாண்மை',
    slug: 'revenue', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Manages land records, property registration, patta transfers, district administration, and disaster relief operations across Tamil Nadu.',
    purpose_ta: 'நில ஆவணங்கள், சொத்து பதிவு, பட்டா மாற்றம், மாவட்ட நிர்வாகம் மற்றும் பேரிடர் நிவாரணம்.',
    citizens_served_en: 'All 8 crore TN citizens', citizens_served_ta: 'அனைத்து 8 கோடி குடிமக்கள்',
    budget_cr: 8200, revenue_cr: 23370, central_funding_pct: 10, state_funding_pct: 90,
    total_staff_sanctioned: 85000, total_staff_filled: 74000,
    current_secretary_en: 'Additional Chief Secretary, Revenue Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages land records, property registration, patta transfers, district administration, and disaster relief funds.',
    description_ta: 'நில ஆவணங்கள், சொத்து பதிவு, பட்டா மாற்றம், மாவட்ட நிர்வாகம்.',
  },
  {
    id: 'pwd', code: 'PWD', name_en: 'Public Works Department', name_ta: 'பொதுப்பணி துறை',
    slug: 'pwd', dept_type: 'infrastructure', established_year: 1853,
    purpose_en: 'Builds and maintains 67,000 km of state highways, bridges, irrigation canals, and government buildings across Tamil Nadu.',
    purpose_ta: '67,000 கி.மீ. மாநில நெடுஞ்சாலைகள், பாலங்கள், நீர்ப்பாசன கால்வாய்கள் மற்றும் அரசு கட்டிடங்கள்.',
    citizens_served_en: 'All TN citizens — roads, bridges, irrigation', citizens_served_ta: 'அனைத்து குடிமக்கள் — சாலைகள், பாலங்கள்',
    budget_cr: 18500, revenue_cr: 450, central_funding_pct: 25, state_funding_pct: 75,
    total_staff_sanctioned: 65000, total_staff_filled: 54000,
    current_secretary_en: 'Principal Secretary, Public Works Dept',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: 'Builds and maintains 67,000 km of state highways, bridges, and government buildings across Tamil Nadu.',
    description_ta: '67,000 கி.மீ. மாநில நெடுஞ்சாலைகள், பாலங்கள் மற்றும் அரசு கட்டிடங்கள்.',
  },
  {
    id: 'welfare', code: 'WELFARE', name_en: 'Social Welfare & Women', name_ta: 'சமூக நலன் & மகளிர்',
    slug: 'welfare', dept_type: 'welfare', established_year: 1956,
    purpose_en: 'Runs Kalaignar Magalir Urimai (₹1,000/month to 1.15 crore women), widow pensions, anganwadi centres, and women safety programmes.',
    purpose_ta: 'கலைஞர் மகளிர் உரிமை திட்டம் (1.15 கோடி பெண்களுக்கு மாதம் ₹1,000), விதவை ஓய்வூதியம், அங்கன்வாடி மையங்கள்.',
    citizens_served_en: '1.15 crore women under Magalir Urimai', citizens_served_ta: '1.15 கோடி மகளிர் உரிமை பயனாளிகள்',
    budget_cr: 22400, revenue_cr: 200, central_funding_pct: 40, state_funding_pct: 60,
    total_staff_sanctioned: 95000, total_staff_filled: 82000,
    current_secretary_en: 'Principal Secretary, Social Welfare Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Runs Kalaignar Magalir Urimai (₹1,000/month to 1.15 crore women), widow pensions, anganwadi centres, and women hostels.',
    description_ta: 'கலைஞர் மகளிர் உரிமைத் திட்டம் (1.15 கோடி பெண்களுக்கு மாதம் ₹1,000), விதவை ஓய்வூதியம்.',
  },
  {
    id: 'tasmac', code: 'TASMAC', name_en: 'Prohibition & Excise (TASMAC)', name_ta: 'மதுவிலக்கு & கலால் (TASMAC)',
    slug: 'tasmac', dept_type: 'revenue', established_year: 1983,
    purpose_en: 'Operates 4,928 TASMAC retail outlets — the sole legal liquor channel in TN. Generates ₹12,247 Cr annually that funds welfare schemes.',
    purpose_ta: '4,928 TASMAC கடைகள் — TN-ல் சட்டப்பூர்வமான ஒரே மது விற்பனை சேனல். ஆண்டுக்கு ₹12,247 கோடி வருமானம்.',
    citizens_served_en: 'Revenue to fund state welfare programmes', citizens_served_ta: 'மாநில திட்டங்களுக்கு வருவாய்',
    budget_cr: 1800, revenue_cr: 12247, central_funding_pct: 0, state_funding_pct: 100,
    total_staff_sanctioned: 38000, total_staff_filled: 35000,
    current_secretary_en: 'Commissioner, Prohibition & Excise',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: 'Operates 4,928 TASMAC retail outlets — the sole legal liquor channel in TN. Generates ₹12,247 Cr annually.',
    description_ta: '4,928 TASMAC கடைகள் — TN-ல் சட்டப்பூர்வமான ஒரே மது விற்பனை சேனல்.',
  },
  {
    id: 'transport', code: 'TRANSPORT', name_en: 'Transport (TNSTC)', name_ta: 'போக்குவரத்து (TNSTC)',
    slug: 'transport', dept_type: 'infrastructure', established_year: 1972,
    purpose_en: '21,600 buses carrying 2.5 crore passengers daily. Operates free bus pass for women, students, and differently-abled citizens.',
    purpose_ta: '21,600 பேருந்துகள் தினமும் 2.5 கோடி பயணிகள். பெண்கள், மாணவர்களுக்கு இலவச பாஸ்.',
    citizens_served_en: '2.5 crore daily passengers', citizens_served_ta: 'தினமும் 2.5 கோடி பயணிகள்',
    budget_cr: 9400, revenue_cr: 8200, central_funding_pct: 20, state_funding_pct: 80,
    total_staff_sanctioned: 155000, total_staff_filled: 142000,
    current_secretary_en: 'Secretary, Transport Dept',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: '21,600 buses carrying 2.5 crore passengers daily. Free bus pass for women, students, and differently-abled citizens.',
    description_ta: '21,600 பேருந்துகள் தினமும் 2.5 கோடி பயணிகள். பெண்கள், மாணவர்களுக்கு இலவச பாஸ்.',
  },
  {
    id: 'energy', code: 'ENERGY', name_en: 'Energy (TANGEDCO)', name_ta: 'ஆற்றல் (TANGEDCO)',
    slug: 'energy', dept_type: 'infrastructure', established_year: 1957,
    purpose_en: 'Supplies electricity to 3.5 crore connections. Provides 100 free units to domestic consumers. State absorbs ₹14,442 Cr of TANGEDCO losses annually.',
    purpose_ta: '3.5 கோடி இணைப்புகளுக்கு மின்சாரம். வீட்டு நுகர்வோருக்கு 100 இலவச யூனிட்.',
    citizens_served_en: '3.5 crore electricity connections', citizens_served_ta: '3.5 கோடி மின் இணைப்புகள்',
    budget_cr: 14442, revenue_cr: 70000, central_funding_pct: 15, state_funding_pct: 85,
    total_staff_sanctioned: 98000, total_staff_filled: 86000,
    current_secretary_en: 'Chairman & Managing Director, TANGEDCO',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 0,
    description_en: 'Supplies electricity to 3.5 crore connections. Provides 100 free units to domestic consumers. State absorbs ₹14,442 Cr of TANGEDCO losses.',
    description_ta: '3.5 கோடி இணைப்புகளுக்கு மின்சாரம். 100 இலவச யூனிட். ₹14,442 கோடி TANGEDCO நஷ்டம்.',
  },
  {
    id: 'finance', code: 'FINANCE', name_en: 'Finance Department', name_ta: 'நிதித்துறை',
    slug: 'finance', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Controls the entire state budget. All department spending requires Finance concurrence. Manages borrowing, debt, salaries, and pensions for 10 lakh government employees.',
    purpose_ta: 'மொத்த மாநில பட்ஜெட்டை கட்டுப்படுத்துகிறது. 10 லட்சம் அரசு ஊழியர்களுக்கு சம்பளம் மற்றும் ஓய்வூதியம்.',
    citizens_served_en: 'All TN citizens — manages entire state budget', citizens_served_ta: 'அனைத்து குடிமக்கள் — மாநில பட்ஜெட் மேலாண்மை',
    budget_cr: 439293, revenue_cr: 311000, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 12000, total_staff_filled: 10800,
    current_secretary_en: 'Additional Chief Secretary & Finance Secretary',
    flag_count_red: 3, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Controls the entire state budget. Manages borrowing, debt, salaries, and pensions for 10 lakh government employees.',
    description_ta: 'மொத்த மாநில பட்ஜெட்டை கட்டுப்படுத்துகிறது. 10 லட்சம் அரசு ஊழியர்களுக்கு சம்பளம்.',
  },
  {
    id: 'municipal', code: 'MUNI', name_en: 'Municipal Administration', name_ta: 'நகராட்சி நிர்வாகம்',
    slug: 'municipal', dept_type: 'infrastructure', established_year: 1920,
    purpose_en: 'Manages 21 corporations, 138 municipalities — water supply, sewerage, solid waste, and urban roads for 3.8 crore urban citizens.',
    purpose_ta: '21 மாநகராட்சிகள், 138 நகராட்சிகள் — 3.8 கோடி நகர்ப்புற குடிமக்களுக்கு நீர், கழிவுநீர் மேலாண்மை.',
    citizens_served_en: '3.8 crore urban citizens', citizens_served_ta: '3.8 கோடி நகர்ப்புற குடிமக்கள்',
    budget_cr: 11200, revenue_cr: 6400, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 72000, total_staff_filled: 61000,
    current_secretary_en: 'Principal Secretary, Municipal Administration Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 21 corporations, 138 municipalities — water supply, sewerage, solid waste, and urban roads for 3.8 crore urban citizens.',
    description_ta: '21 மாநகராட்சிகள், 138 நகராட்சிகள் — 3.8 கோடி நகர்ப்புற குடிமக்களுக்கு நீர் மற்றும் திட கழிவு மேலாண்மை.',
  },
  {
    id: 'police', code: 'POLICE', name_en: 'Home (Police & Security)', name_ta: 'உள்துறை (காவல்)',
    slug: 'police', dept_type: 'administration', established_year: 1861,
    purpose_en: '1.35 lakh police personnel handling law enforcement, crime investigation, traffic management, coastal security, and prisons.',
    purpose_ta: '1.35 லட்சம் காவல் துறையினர். சட்ட அமலாக்கம், குற்றவியல் விசாரணை, போக்குவரத்து மேலாண்மை.',
    citizens_served_en: 'All 8 crore TN citizens', citizens_served_ta: 'அனைத்து 8 கோடி குடிமக்கள்',
    budget_cr: 16200, revenue_cr: 380, central_funding_pct: 15, state_funding_pct: 85,
    total_staff_sanctioned: 160000, total_staff_filled: 135000,
    current_secretary_en: 'Director General of Police',
    flag_count_red: 2, flag_count_amber: 1, flag_count_green: 1,
    description_en: '1.35 lakh police personnel. Law enforcement, crime investigation, traffic management, coastal security, and prisons.',
    description_ta: '1.35 லட்சம் காவல் துறையினர். சட்ட அமலாக்கம், குற்றவியல் விசாரணை.',
  },
  {
    id: 'agriculture', code: 'AGRI', name_en: 'Agriculture & Farmers Welfare', name_ta: 'வேளாண்மை & விவசாயி நலன்',
    slug: 'agriculture', dept_type: 'welfare', established_year: 1947,
    purpose_en: 'Supports 82 lakh farmers with crop insurance, certified seeds, fertiliser subsidies, irrigation support, and price protection mechanisms.',
    purpose_ta: '82 லட்சம் விவசாயிகளுக்கு பயிர் காப்பீடு, சான்றளிக்கப்பட்ட விதைகள், உர மானியம் மற்றும் நீர்ப்பாசன ஆதரவு.',
    citizens_served_en: '82 lakh farmers', citizens_served_ta: '82 லட்சம் விவசாயிகள்',
    budget_cr: 12800, revenue_cr: 2100, central_funding_pct: 40, state_funding_pct: 60,
    total_staff_sanctioned: 48000, total_staff_filled: 38000,
    current_secretary_en: 'Principal Secretary, Agriculture Dept',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Supports 82 lakh farmers with crop insurance, certified seeds, fertiliser subsidies, and price protection.',
    description_ta: '82 லட்சம் விவசாயிகளுக்கு பயிர் காப்பீடு, சான்றளிக்கப்பட்ட விதைகள் மற்றும் உர மானியம்.',
  },
  {
    id: 'animal-husbandry', code: 'AH', name_en: 'Animal Husbandry, Dairying & Fisheries', name_ta: 'கால்நடை வளர்ப்பு, பால்வளம் & மீன்வளம்',
    slug: 'animal-husbandry', dept_type: 'welfare', established_year: 1947,
    purpose_en: 'Supports 1.1 crore livestock holders with veterinary services, breed improvement, dairy co-operatives, and 5 lakh fishing families.',
    purpose_ta: '1.1 கோடி கால்நடை வளர்ப்போர், 5 லட்சம் மீனவ குடும்பங்களுக்கு கால்நடை மருத்துவம், பால் கூட்டுறவு.',
    citizens_served_en: '1.1 crore livestock holders & 5 lakh fishing families', citizens_served_ta: '1.1 கோடி கால்நடை வளர்ப்போர் மற்றும் 5 லட்சம் மீனவ குடும்பங்கள்',
    budget_cr: 4200, revenue_cr: 320, central_funding_pct: 35, state_funding_pct: 65,
    total_staff_sanctioned: 18000, total_staff_filled: 14200,
    current_secretary_en: 'Principal Secretary, Animal Husbandry Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Supports livestock holders with veterinary services, breed improvement, dairy co-operatives, and fishing families with boats and gear subsidies.',
    description_ta: 'கால்நடை மருத்துவம், இன மேம்பாடு, பால் கூட்டுறவு மற்றும் மீனவர்களுக்கு படகு மற்றும் கருவி மானியம்.',
  },
  {
    id: 'bc-welfare', code: 'BCW', name_en: 'BC, MBC & Minorities Welfare', name_ta: 'பிற்படுத்தப்பட்டோர், மிகவும் பிற்படுத்தப்பட்டோர் & சிறுபான்மையினர் நலன்',
    slug: 'bc-welfare', dept_type: 'welfare', established_year: 1957,
    purpose_en: 'Provides scholarships, hostels, and welfare schemes for 2.8 crore OBC, 3.2 crore MBC, and 42 lakh minority citizens in Tamil Nadu.',
    purpose_ta: '2.8 கோடி OBC, 3.2 கோடி MBC மற்றும் 42 லட்சம் சிறுபான்மையினருக்கு உதவித்தொகை, விடுதிகள்.',
    citizens_served_en: '2.8 cr OBC + 3.2 cr MBC + 42 lakh minorities', citizens_served_ta: 'OBC, MBC மற்றும் சிறுபான்மையினர்',
    budget_cr: 5800, revenue_cr: 120, central_funding_pct: 25, state_funding_pct: 75,
    total_staff_sanctioned: 12000, total_staff_filled: 9800,
    current_secretary_en: 'Secretary, BC, MBC and Minorities Welfare Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Scholarships, hostels, and welfare schemes for OBC, MBC, and minority communities. Runs 600+ residential schools and hostels.',
    description_ta: 'OBC, MBC மற்றும் சிறுபான்மையினருக்கு உதவித்தொகை, விடுதிகள். 600+ குடியிருப்பு பள்ளிகள்.',
  },
  {
    id: 'commercial-taxes', code: 'CT', name_en: 'Commercial Taxes & Registration', name_ta: 'வணிக வரி & பதிவுத்துறை',
    slug: 'commercial-taxes', dept_type: 'revenue', established_year: 1947,
    purpose_en: 'Collects GST, VAT on petroleum products, stamp duty, and property registration fees. Manages 8.5 lakh registered businesses and 40,000 documents registered daily.',
    purpose_ta: 'GST, பெட்ரோலியம் VAT, முத்திரை வரி மற்றும் சொத்து பதிவு. 8.5 லட்சம் பதிவு செய்யப்பட்ட வணிகங்கள்.',
    citizens_served_en: '8.5 lakh businesses; 40,000 registrations/day', citizens_served_ta: '8.5 லட்சம் வணிகங்கள்; தினமும் 40,000 பதிவுகள்',
    budget_cr: 1600, revenue_cr: 86000, central_funding_pct: 0, state_funding_pct: 100,
    total_staff_sanctioned: 14000, total_staff_filled: 11200,
    current_secretary_en: 'Commissioner of Commercial Taxes',
    flag_count_red: 1, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Collects GST, VAT, stamp duty, and property registration fees. Revenue backbone of TN government — ₹86,000 Cr annual collection.',
    description_ta: 'GST, VAT, முத்திரை வரி மற்றும் சொத்து பதிவு வசூல். ஆண்டுக்கு ₹86,000 கோடி வருவாய்.',
  },
  {
    id: 'cooperation', code: 'COOP', name_en: 'Co-operation, Food & Consumer Protection', name_ta: 'கூட்டுறவு, உணவு & நுகர்வோர் பாதுகாப்பு',
    slug: 'cooperation', dept_type: 'welfare', established_year: 1948,
    purpose_en: 'Manages PDS for 2.06 crore ration card families, 2,600 co-operative societies, TNCSC rice procurement, and consumer protection courts.',
    purpose_ta: '2.06 கோடி குடும்பங்களுக்கு PDS, 2,600 கூட்டுறவு சங்கங்கள், TNCSC நெல் கொள்முதல்.',
    citizens_served_en: '2.06 crore ration card families', citizens_served_ta: '2.06 கோடி ரேஷன் அட்டை குடும்பங்கள்',
    budget_cr: 8400, revenue_cr: 1800, central_funding_pct: 50, state_funding_pct: 50,
    total_staff_sanctioned: 28000, total_staff_filled: 24000,
    current_secretary_en: 'Secretary, Co-operation, Food and Consumer Protection Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 2,
    description_en: 'Manages PDS for 2.06 crore families, 2,600 co-operatives, TNCSC rice procurement, and consumer grievance redressal.',
    description_ta: '2.06 கோடி குடும்பங்களுக்கு PDS. 2,600 கூட்டுறவு சங்கங்கள் மற்றும் நுகர்வோர் புகார் தீர்வு.',
  },
  {
    id: 'environment', code: 'ENV', name_en: 'Environment, Climate Change & Forests', name_ta: 'சூழல், காலநிலை மாற்றம் & காடுகள்',
    slug: 'environment', dept_type: 'administration', established_year: 1980,
    purpose_en: 'Manages 26,321 sq km of forest cover, TNPCB pollution monitoring, coastal regulation, biodiversity conservation, and climate action plans.',
    purpose_ta: '26,321 சதுர கி.மீ. காடுகள், TNPCB மாசு கண்காணிப்பு, கடலோர ஒழுங்குமுறை, பல்லுயிர் பாதுகாப்பு.',
    citizens_served_en: 'All citizens — environmental services', citizens_served_ta: 'அனைத்து குடிமக்கள் — சுற்றுச்சூழல் சேவைகள்',
    budget_cr: 2800, revenue_cr: 380, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 22000, total_staff_filled: 17500,
    current_secretary_en: 'Principal Chief Conservator of Forests',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 26,321 sq km of forest cover, TNPCB pollution monitoring, coastal regulation, and biodiversity conservation.',
    description_ta: '26,321 சதுர கி.மீ. காடுகள், TNPCB மாசு கண்காணிப்பு மற்றும் பல்லுயிர் பாதுகாப்பு.',
  },
  {
    id: 'adi-dravidar', code: 'ADW', name_en: 'Adi Dravidar & Tribal Welfare', name_ta: 'ஆதி திராவிட & பழங்குடியினர் நலன்',
    slug: 'adi-dravidar', dept_type: 'welfare', established_year: 1956,
    purpose_en: 'Runs welfare schemes, residential schools, and hostels for 1.72 crore SC citizens and 7.9 lakh ST citizens — post-matric scholarships, free cycles, and land grants.',
    purpose_ta: '1.72 கோடி SC மற்றும் 7.9 லட்சம் ST குடிமக்களுக்கு குடியிருப்பு பள்ளிகள், விடுதிகள், உதவித்தொகை.',
    citizens_served_en: '1.72 cr SC + 7.9 lakh ST citizens', citizens_served_ta: '1.72 கோடி SC மற்றும் 7.9 லட்சம் ST குடிமக்கள்',
    budget_cr: 6200, revenue_cr: 80, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 15000, total_staff_filled: 12000,
    current_secretary_en: 'Secretary, Adi Dravidar and Tribal Welfare Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Welfare schemes, 1,200+ residential schools, hostels, post-matric scholarships, and land grants for SC/ST communities.',
    description_ta: '1,200+ குடியிருப்பு பள்ளிகள், விடுதிகள், பட்டப்பின் உதவித்தொகை மற்றும் SC/ST சமூகங்களுக்கு நில மானியம்.',
  },
  {
    id: 'higher-education', code: 'HE', name_en: 'Higher Education', name_ta: 'உயர் கல்வி',
    slug: 'higher-education', dept_type: 'welfare', established_year: 1950,
    purpose_en: 'Oversees 566 government arts & science colleges, 13 universities, and 460 polytechnics — serving 25 lakh students through state and aided institutions.',
    purpose_ta: '566 அரசு கலை & அறிவியல் கல்லூரிகள், 13 பல்கலைக்கழகங்கள், 460 பாலிடெக்னிக்குகள் — 25 லட்சம் மாணவர்கள்.',
    citizens_served_en: '25 lakh students in higher education', citizens_served_ta: '25 லட்சம் உயர்கல்வி மாணவர்கள்',
    budget_cr: 9800, revenue_cr: 1200, central_funding_pct: 20, state_funding_pct: 80,
    total_staff_sanctioned: 52000, total_staff_filled: 44000,
    current_secretary_en: 'Principal Secretary, Higher Education Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Oversees 566 government colleges, 13 universities, and 460 polytechnics. Manages Pudhumai Penn scholarship for 1.4 lakh college women.',
    description_ta: '566 அரசு கல்லூரிகள், 13 பல்கலைக்கழகங்கள். 1.4 லட்சம் கல்லூரி மாணவிகளுக்கு புதுமைப்பெண் உதவித்தொகை.',
  },
  {
    id: 'housing', code: 'HOUS', name_en: 'Housing & Urban Development', name_ta: 'வீட்டுவசதி & நகர்ப்புற வளர்ச்சி',
    slug: 'housing', dept_type: 'infrastructure', established_year: 1961,
    purpose_en: 'Builds affordable housing through TNHB and CMDA. Targets 6 lakh housing units under Kalaignar Illam. Manages Chennai metropolitan planning.',
    purpose_ta: 'TNHB மற்றும் CMDA மூலம் மலிவு விலை வீடுகள். கலைஞர் இல்லம் திட்டத்தில் 6 லட்சம் வீடுகள்.',
    citizens_served_en: '6 lakh families under housing schemes', citizens_served_ta: '6 லட்சம் குடும்பங்கள்',
    budget_cr: 7600, revenue_cr: 2400, central_funding_pct: 35, state_funding_pct: 65,
    total_staff_sanctioned: 8000, total_staff_filled: 6800,
    current_secretary_en: 'Secretary, Housing and Urban Development Dept',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 0,
    description_en: 'Builds affordable housing through TNHB and CMDA. Manages Chennai metropolitan planning and Kalaignar Illam housing programme.',
    description_ta: 'TNHB மற்றும் CMDA மூலம் மலிவு விலை வீடுகள். கலைஞர் இல்லம் திட்டம் மற்றும் சென்னை நகர்ப்புற திட்டமிடல்.',
  },
  {
    id: 'industries', code: 'IND', name_en: 'Industries, Investment Promotion & Commerce', name_ta: 'தொழில்கள், முதலீட்டு ஊக்குவிப்பு & வணிகம்',
    slug: 'industries', dept_type: 'infrastructure', established_year: 1947,
    purpose_en: 'Promotes industrial investment through TIDCO, SIPCOT, and TIDEL. TN attracted ₹6.65 lakh Cr in investment intentions at GIM 2024.',
    purpose_ta: 'TIDCO, SIPCOT மற்றும் TIDEL மூலம் தொழில் முதலீட்டு ஊக்குவிப்பு. GIM 2024-ல் ₹6.65 லட்சம் கோடி முதலீட்டு நோக்கங்கள்.',
    citizens_served_en: 'Industrial workers & investors', citizens_served_ta: 'தொழிலாளர்கள் மற்றும் முதலீட்டாளர்கள்',
    budget_cr: 3200, revenue_cr: 1400, central_funding_pct: 20, state_funding_pct: 80,
    total_staff_sanctioned: 9000, total_staff_filled: 7400,
    current_secretary_en: 'Principal Secretary, Industries Dept',
    flag_count_red: 1, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Promotes industrial investment through TIDCO, SIPCOT, TIDEL. Manages special economic zones and industrial parks across TN.',
    description_ta: 'TIDCO, SIPCOT, TIDEL மூலம் தொழில் முதலீட்டு ஊக்குவிப்பு. சிறப்பு பொருளாதார மண்டலங்கள்.',
  },
  {
    id: 'it', code: 'IT', name_en: 'Information Technology', name_ta: 'தகவல் தொழில்நுட்பம்',
    slug: 'it', dept_type: 'infrastructure', established_year: 1999,
    purpose_en: 'Manages TN-e-governance (TNEGA), digital services, fibre network, and IT corridor. Chennai is India\'s second-largest IT hub with 5 lakh IT professionals.',
    purpose_ta: 'TNEGA மின்-ஆட்சி, டிஜிட்டல் சேவைகள், ஃபைபர் நெட்வொர்க். சென்னை — 5 லட்சம் IT நிபுணர்களுடன் இந்தியாவின் இரண்டாவது IT மையம்.',
    citizens_served_en: '5 lakh IT professionals; all e-service users', citizens_served_ta: '5 லட்சம் IT நிபுணர்கள்; அனைத்து மின்சேவை பயனாளிகள்',
    budget_cr: 2100, revenue_cr: 600, central_funding_pct: 25, state_funding_pct: 75,
    total_staff_sanctioned: 4200, total_staff_filled: 3600,
    current_secretary_en: 'Secretary, Information Technology Dept',
    flag_count_red: 0, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Manages TNEGA e-governance platform, TN-FIBERNET, and IT Expressway. Chennai is India\'s second-largest IT hub.',
    description_ta: 'TNEGA மின்-ஆட்சி தளம், TN-FIBERNET மற்றும் IT நெடுஞ்சாலை. சென்னை — இந்தியாவின் இரண்டாவது IT மையம்.',
  },
  {
    id: 'labour', code: 'LAB', name_en: 'Labour Welfare & Skill Development', name_ta: 'தொழிலாளர் நலன் & திறன் மேம்பாடு',
    slug: 'labour', dept_type: 'welfare', established_year: 1947,
    purpose_en: 'Enforces labour laws for 3.2 crore workers. Manages TNSDC skill training for 6 lakh youth annually. Oversees construction workers\' board and ESI hospitals.',
    purpose_ta: '3.2 கோடி தொழிலாளர்களுக்கு தொழிலாளர் சட்டங்கள். TNSDC மூலம் ஆண்டுக்கு 6 லட்சம் இளைஞர்களுக்கு திறன் பயிற்சி.',
    citizens_served_en: '3.2 crore workers; 6 lakh skill trainees/year', citizens_served_ta: '3.2 கோடி தொழிலாளர்கள்; ஆண்டுக்கு 6 லட்சம் திறன் பயிற்சியாளர்கள்',
    budget_cr: 3800, revenue_cr: 280, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 11000, total_staff_filled: 8800,
    current_secretary_en: 'Commissioner of Labour',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Enforces labour laws, manages TNSDC skill training, Construction Workers Welfare Board, and ESI dispensaries.',
    description_ta: 'தொழிலாளர் சட்டங்கள் அமலாக்கம், TNSDC திறன் பயிற்சி, கட்டட தொழிலாளர் நலன் வாரியம்.',
  },
  {
    id: 'law', code: 'LAW', name_en: 'Law Department', name_ta: 'சட்டத்துறை',
    slug: 'law', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Drafts legislation, manages government legal defence, oversees 2.8 crore pending court cases, and coordinates law reform commissions.',
    purpose_ta: 'சட்ட வரைவு, அரசு வழக்கு நிர்வாகம், 2.8 கோடி நிலுவை வழக்குகள் மேலாண்மை மற்றும் சட்ட சீர்திருத்த ஆணையங்கள்.',
    citizens_served_en: 'All citizens — justice system', citizens_served_ta: 'அனைத்து குடிமக்கள் — நீதி அமைப்பு',
    budget_cr: 1400, revenue_cr: 120, central_funding_pct: 10, state_funding_pct: 90,
    total_staff_sanctioned: 8500, total_staff_filled: 7200,
    current_secretary_en: 'Secretary, Law Department',
    flag_count_red: 1, flag_count_amber: 1, flag_count_green: 1,
    description_en: 'Drafts legislation, manages government legal defence, and oversees 2.8 crore pending court cases in TN courts.',
    description_ta: 'சட்ட வரைவு, அரசு வழக்கு நிர்வாகம் மற்றும் 2.8 கோடி நிலுவை வழக்குகள் மேலாண்மை.',
  },
  {
    id: 'planning', code: 'PLAN', name_en: 'Planning, Development & Special Initiatives', name_ta: 'திட்டமிடல், வளர்ச்சி & சிறப்பு முயற்சிகள்',
    slug: 'planning', dept_type: 'administration', established_year: 1950,
    purpose_en: 'Coordinates state five-year vision plans, MLA Local Area Development Fund (₹2.25 Cr/constituency), and monitors development programme outcomes.',
    purpose_ta: 'மாநில ஐந்தாண்டு திட்டங்கள், MLA உள்ளாட்சி வளர்ச்சி நிதி (₹2.25 கோடி/தொகுதி) மற்றும் திட்ட கண்காணிப்பு.',
    citizens_served_en: 'All TN citizens — development planning', citizens_served_ta: 'அனைத்து குடிமக்கள் — வளர்ச்சி திட்டமிடல்',
    budget_cr: 12000, revenue_cr: 800, central_funding_pct: 40, state_funding_pct: 60,
    total_staff_sanctioned: 3500, total_staff_filled: 3000,
    current_secretary_en: 'Secretary, Planning and Development Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Coordinates state vision plans, MLA Local Area Development Fund allocations, and monitors programme outcomes across all departments.',
    description_ta: 'மாநில திட்டங்கள் ஒருங்கிணைப்பு, MLA உள்ளாட்சி வளர்ச்சி நிதி ஒதுக்கீடு மற்றும் திட்ட கண்காணிப்பு.',
  },
  {
    id: 'rural-development', code: 'RD', name_en: 'Rural Development & Panchayat Raj', name_ta: 'ஊரக வளர்ச்சி & பஞ்சாயத்து ராஜ்',
    slug: 'rural-development', dept_type: 'infrastructure', established_year: 1994,
    purpose_en: 'Manages 12,524 village panchayats, MGNREGS employment for 55 lakh households, rural roads, drinking water supply, and rural housing.',
    purpose_ta: '12,524 கிராம பஞ்சாயத்துகள், MGNREGS மூலம் 55 லட்சம் குடும்பங்களுக்கு வேலை, கிராமப்புற சாலைகள்.',
    citizens_served_en: '55 lakh MGNREGS households; 4 crore rural citizens', citizens_served_ta: '55 லட்சம் MGNREGS குடும்பங்கள்; 4 கோடி கிராமப்புற குடிமக்கள்',
    budget_cr: 18200, revenue_cr: 2800, central_funding_pct: 60, state_funding_pct: 40,
    total_staff_sanctioned: 45000, total_staff_filled: 38000,
    current_secretary_en: 'Principal Secretary, Rural Development and Panchayat Raj Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 12,524 village panchayats, MGNREGS rural employment, rural roads under PMGSY, and Jal Jeevan Mission water supply.',
    description_ta: '12,524 கிராம பஞ்சாயத்துகள், MGNREGS கிராமப்புற வேலைவாய்ப்பு, கிராமப்புற சாலைகள் மற்றும் ஜல் ஜீவன் திட்டம்.',
  },
  {
    id: 'tourism', code: 'TOU', name_en: 'Tourism, Culture & Religious Endowments', name_ta: 'சுற்றுலா, கலாச்சாரம் & இந்துசமய அறநிலையம்',
    slug: 'tourism', dept_type: 'administration', established_year: 1964,
    purpose_en: 'Promotes TN tourism (38,000+ temples, 13 UNESCO sites). Manages HR&CE with 36,000+ Hindu temples. Operates TTDC with 78 hotels and yatras.',
    purpose_ta: 'TN சுற்றுலா ஊக்குவிப்பு (38,000+ கோவில்கள்). HR&CE — 36,000+ இந்துக் கோவில்கள் நிர்வாகம். TTDC: 78 ஓய்வகங்கள்.',
    citizens_served_en: '4 crore domestic & 8 lakh foreign tourists/year', citizens_served_ta: 'ஆண்டுக்கு 4 கோடி உள்நாட்டு & 8 லட்சம் வெளிநாட்டு சுற்றுலாப் பயணிகள்',
    budget_cr: 3600, revenue_cr: 2200, central_funding_pct: 15, state_funding_pct: 85,
    total_staff_sanctioned: 14000, total_staff_filled: 11500,
    current_secretary_en: 'Secretary, Tourism, Culture and Religious Endowments Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 38,000+ temples through HR&CE, promotes heritage tourism, and operates TTDC hotels and Char Dham yatras.',
    description_ta: 'HR&CE மூலம் 38,000+ கோவில்கள் நிர்வாகம், பாரம்பரிய சுற்றுலா ஊக்குவிப்பு மற்றும் TTDC ஓய்வகங்கள்.',
  },
  {
    id: 'water-resources', code: 'WR', name_en: 'Water Resources', name_ta: 'நீர்வளத்துறை',
    slug: 'water-resources', dept_type: 'infrastructure', established_year: 1947,
    purpose_en: 'Manages 39,202 water bodies, irrigation canals, Cauvery water allocation, Chennai Metro Water, and water supply to 2 crore urban households.',
    purpose_ta: '39,202 நீர்நிலைகள், காவேரி நீர் ஒதுக்கீடு, சென்னை மெட்ரோ வாட்டர் மற்றும் 2 கோடி நகர்ப்புற குடும்பங்களுக்கு நீர் வழங்கல்.',
    citizens_served_en: '2 crore urban + 4 crore irrigation beneficiaries', citizens_served_ta: '2 கோடி நகர்ப்புற மற்றும் 4 கோடி பாசன பயனாளிகள்',
    budget_cr: 9600, revenue_cr: 1800, central_funding_pct: 25, state_funding_pct: 75,
    total_staff_sanctioned: 32000, total_staff_filled: 26000,
    current_secretary_en: 'Secretary, Water Resources Dept',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages 39,202 water bodies, Cauvery water allocation, Chennai Metro Water, and urban/rural water supply infrastructure.',
    description_ta: '39,202 நீர்நிலைகள், காவேரி நீர் ஒதுக்கீடு, சென்னை மெட்ரோ வாட்டர் மற்றும் நகர்ப்புற/கிராமப்புற நீர் வழங்கல்.',
  },
  {
    id: 'youth-sports', code: 'YS', name_en: 'Youth Welfare & Sports Development', name_ta: 'இளைஞர் நலன் & விளையாட்டு வளர்ச்சி',
    slug: 'youth-sports', dept_type: 'welfare', established_year: 1971,
    purpose_en: 'Runs 1,127 youth welfare centres, manages Rajiv Gandhi sports infrastructure, Chief Minister\'s Udanila Vilaiyattu Thittam, and NSS in colleges.',
    purpose_ta: '1,127 இளைஞர் நலன் மையங்கள், ராஜீவ் காந்தி விளையாட்டு உள்கட்டமைப்பு, முதலமைச்சர் உடனிலா விளையாட்டு திட்டம்.',
    citizens_served_en: '2.5 crore youth (15–35 age)', citizens_served_ta: '2.5 கோடி இளைஞர்கள் (15–35 வயது)',
    budget_cr: 1800, revenue_cr: 80, central_funding_pct: 25, state_funding_pct: 75,
    total_staff_sanctioned: 6000, total_staff_filled: 5200,
    current_secretary_en: 'Secretary, Youth Welfare and Sports Development Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Runs 1,127 youth welfare centres, manages sports infrastructure, and Udanila Vilaiyattu Thittam for grassroots sports.',
    description_ta: '1,127 இளைஞர் நலன் மையங்கள், விளையாட்டு உள்கட்டமைப்பு மற்றும் உடனிலா விளையாட்டு திட்டம்.',
  },
  {
    id: 'handlooms', code: 'HT', name_en: 'Handlooms, Handicrafts, Textiles & Khadi', name_ta: 'கைத்தறி, கைவினைஞர்கள், ஜவுளி & காதி',
    slug: 'handlooms', dept_type: 'welfare', established_year: 1956,
    purpose_en: 'Supports 4 lakh handloom weavers, 2.5 lakh handicraft artisans. Manages Cooptex, Tamil Nadu Handloom Weavers\' Co-operative Society, and khadi boards.',
    purpose_ta: '4 லட்சம் கைத்தறி நெசவாளர்கள், 2.5 லட்சம் கைவினைஞர்களை ஆதரிக்கிறது. Cooptex மற்றும் TNHWS நிர்வாகம்.',
    citizens_served_en: '4 lakh weavers + 2.5 lakh artisans', citizens_served_ta: '4 லட்சம் நெசவாளர்கள் + 2.5 லட்சம் கைவினைஞர்கள்',
    budget_cr: 1600, revenue_cr: 420, central_funding_pct: 20, state_funding_pct: 80,
    total_staff_sanctioned: 7000, total_staff_filled: 5600,
    current_secretary_en: 'Secretary, Handlooms and Textiles Dept',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Supports handloom weavers and handicraft artisans through Cooptex, welfare schemes, and marketing support.',
    description_ta: 'Cooptex, நலன் திட்டங்கள் மற்றும் சந்தைப்படுத்தல் ஆதரவு மூலம் நெசவாளர்கள் மற்றும் கைவினைஞர்களை ஆதரிக்கிறது.',
  },
  {
    id: 'msme', code: 'MSME', name_en: 'Micro, Small & Medium Enterprises', name_ta: 'நுண், சிறு & நடுத்தர தொழில்கள்',
    slug: 'msme', dept_type: 'infrastructure', established_year: 2004,
    purpose_en: 'Supports 46 lakh MSME units employing 1.1 crore people. Manages SIDCO, TANSTIA, tool rooms, and MSME credit guarantee and cluster schemes.',
    purpose_ta: '46 லட்சம் MSME பிரிவுகள் — 1.1 கோடி பேருக்கு வேலை. SIDCO, TANSTIA நிர்வாகம் மற்றும் கடன் உத்தரவாதம்.',
    citizens_served_en: '46 lakh MSME units; 1.1 crore workers', citizens_served_ta: '46 லட்சம் MSME பிரிவுகள்; 1.1 கோடி தொழிலாளர்கள்',
    budget_cr: 2400, revenue_cr: 380, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 5000, total_staff_filled: 4200,
    current_secretary_en: 'Secretary, MSME Dept',
    flag_count_red: 1, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Supports 46 lakh MSME units through SIDCO, tool rooms, credit guarantees, and cluster development programmes.',
    description_ta: 'SIDCO, கருவி அறைகள், கடன் உத்தரவாதம் மற்றும் கொத்தணி வளர்ச்சி திட்டங்கள் மூலம் 46 லட்சம் MSME பிரிவுகளை ஆதரிக்கிறது.',
  },
  {
    id: 'tamil-development', code: 'TD', name_en: 'Tamil Development, Information & Publicity', name_ta: 'தமிழ் வளர்ச்சி, தகவல் & விளம்பரம்',
    slug: 'tamil-development', dept_type: 'administration', established_year: 1967,
    purpose_en: 'Promotes Tamil language and culture, manages Doordarshan Kendra, All India Radio Chennai, Tamil Nadu government media, and official communications.',
    purpose_ta: 'தமிழ் மொழி மற்றும் கலாச்சாரம் ஊக்குவிப்பு, தூர்தர்ஷன் கேந்திரா, ஆகாஷவாணி சென்னை, அரசு ஊடகம் மேலாண்மை.',
    citizens_served_en: 'All Tamil-speaking citizens', citizens_served_ta: 'அனைத்து தமிழ் பேசும் குடிமக்கள்',
    budget_cr: 1200, revenue_cr: 180, central_funding_pct: 5, state_funding_pct: 95,
    total_staff_sanctioned: 4800, total_staff_filled: 4100,
    current_secretary_en: 'Secretary, Tamil Development Dept',
    flag_count_red: 0, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Promotes Tamil language, manages government media, and oversees official communications, publications, and cultural events.',
    description_ta: 'தமிழ் மொழி ஊக்குவிப்பு, அரசு ஊடக மேலாண்மை மற்றும் அலுவலக தகவல்தொடர்பு, வெளியீடுகள் மற்றும் கலாச்சார நிகழ்வுகள்.',
  },
  {
    id: 'prison', code: 'PRS', name_en: 'Prison Management & Reforms', name_ta: 'சிறை நிர்வாகம் & சீர்திருத்தம்',
    slug: 'prison', dept_type: 'administration', established_year: 1861,
    purpose_en: 'Manages 145 prisons housing 29,000 inmates. Runs rehabilitation, vocational training, open camps, and Borstal school for juveniles.',
    purpose_ta: '29,000 கைதிகளை கொண்ட 145 சிறைகள். மறுவாழ்வு, தொழில் பயிற்சி, திறந்த முகாம்கள் மற்றும் போர்ஸ்டல் பள்ளி.',
    citizens_served_en: '29,000 inmates; prisoner families', citizens_served_ta: '29,000 கைதிகள்; கைதிகளின் குடும்பங்கள்',
    budget_cr: 1100, revenue_cr: 60, central_funding_pct: 10, state_funding_pct: 90,
    total_staff_sanctioned: 12000, total_staff_filled: 9800,
    current_secretary_en: 'Director General of Prisons and Correctional Services',
    flag_count_red: 2, flag_count_amber: 2, flag_count_green: 0,
    description_en: 'Manages 145 prisons, inmate rehabilitation, vocational training, and Borstal school for juvenile offenders.',
    description_ta: '145 சிறைகள் நிர்வாகம், கைதி மறுவாழ்வு, தொழில் பயிற்சி மற்றும் சிறார் குற்றவாளிகளுக்கான போர்ஸ்டல் பள்ளி.',
  },
  {
    id: 'personnel', code: 'PAR', name_en: 'Personnel & Administrative Reforms', name_ta: 'பணியாளர் & நிர்வாக சீர்திருத்தம்',
    slug: 'personnel', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Manages service rules, DPC meetings, ACR records, and administrative reforms for 10 lakh state government employees. Coordinates TNPSC.',
    purpose_ta: 'சேவை விதிகள், DPC கூட்டங்கள், ACR பதிவுகள் மற்றும் 10 லட்சம் அரசு ஊழியர்களுக்கான நிர்வாக சீர்திருத்தம். TNPSC ஒருங்கிணைப்பு.',
    citizens_served_en: '10 lakh state government employees', citizens_served_ta: '10 லட்சம் மாநில அரசு ஊழியர்கள்',
    budget_cr: 800, revenue_cr: 40, central_funding_pct: 5, state_funding_pct: 95,
    total_staff_sanctioned: 3000, total_staff_filled: 2600,
    current_secretary_en: 'Secretary, Personnel and Administrative Reforms Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages service rules, DPC promotions, ACR records, and administrative reforms for all state government employees.',
    description_ta: 'சேவை விதிகள், DPC பதவி உயர்வுகள், ACR பதிவுகள் மற்றும் அனைத்து மாநில அரசு ஊழியர்களுக்கான நிர்வாக சீர்திருத்தம்.',
  },
  {
    id: 'special-programme', code: 'SPI', name_en: 'Special Programme Implementation', name_ta: 'சிறப்பு திட்ட செயலாக்கம்',
    slug: 'special-programme', dept_type: 'administration', established_year: 1985,
    purpose_en: 'Coordinates Chief Minister\'s Special Packages, monitors flagship schemes, handles MPLADs, and accelerates stalled projects across all departments.',
    purpose_ta: 'முதலமைச்சர் சிறப்பு தொகுப்புகள், முக்கிய திட்டங்கள் கண்காணிப்பு, MPLADS மேலாண்மை மற்றும் தடைபட்ட திட்டங்கள் முடுக்கிவிடல்.',
    citizens_served_en: 'Beneficiaries of flagship schemes', citizens_served_ta: 'முக்கிய திட்டங்களின் பயனாளிகள்',
    budget_cr: 5200, revenue_cr: 200, central_funding_pct: 40, state_funding_pct: 60,
    total_staff_sanctioned: 1800, total_staff_filled: 1600,
    current_secretary_en: 'Secretary, Special Programme Implementation Dept',
    flag_count_red: 0, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Coordinates CM Special Packages, monitors flagship schemes, handles MPLAD funds, and accelerates stalled projects.',
    description_ta: 'CM சிறப்பு தொகுப்புகள், முக்கிய திட்டங்கள் கண்காணிப்பு, MPLAD நிதி மேலாண்மை மற்றும் தடைபட்ட திட்டங்கள் முடுக்கிவிடல்.',
  },
  {
    id: 'government-estates', code: 'GE', name_en: 'Government Estates', name_ta: 'அரசு நில மேலாண்மை',
    slug: 'government-estates', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Manages government-owned land, buildings, estates, and inam lands. Oversees assignment of surplus land to landless poor and encroachment removal.',
    purpose_ta: 'அரசு நில, கட்டிட மேலாண்மை. நிலமற்ற ஏழைகளுக்கு மிகுதி நில ஒதுக்கீடு மற்றும் ஆக்கிரமிப்பு அகற்றல்.',
    citizens_served_en: 'Landless poor; government estate users', citizens_served_ta: 'நிலமற்ற ஏழைகள்; அரசு நில பயனாளிகள்',
    budget_cr: 600, revenue_cr: 480, central_funding_pct: 0, state_funding_pct: 100,
    total_staff_sanctioned: 4000, total_staff_filled: 3200,
    current_secretary_en: 'Commissioner of Land Administration',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Manages government-owned land and buildings, assigns surplus land to landless poor, and oversees inam lands.',
    description_ta: 'அரசு நில மற்றும் கட்டிட மேலாண்மை, நிலமற்ற ஏழைகளுக்கு மிகுதி நில ஒதுக்கீடு மற்றும் இனாம் நிலங்கள் மேலாண்மை.',
  },
  {
    id: 'fisheries', code: 'FISH', name_en: 'Fisheries', name_ta: 'மீன்வளம்',
    slug: 'fisheries', dept_type: 'welfare', established_year: 1962,
    purpose_en: 'Supports 5 lakh fishermen families along 1,076 km coastline. Manages fishing harbours, boat loans, life insurance, and fish processing infrastructure.',
    purpose_ta: '1,076 கி.மீ. கடற்கரையில் 5 லட்சம் மீனவ குடும்பங்கள். மீன்பிடி துறைமுகங்கள், படகு கடன், உயிர் காப்பீடு.',
    citizens_served_en: '5 lakh fishing families', citizens_served_ta: '5 லட்சம் மீனவ குடும்பங்கள்',
    budget_cr: 1800, revenue_cr: 280, central_funding_pct: 40, state_funding_pct: 60,
    total_staff_sanctioned: 5500, total_staff_filled: 4400,
    current_secretary_en: 'Commissioner of Fisheries',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Supports 5 lakh fishing families with harbour infrastructure, boat subsidies, life insurance, and fish processing support.',
    description_ta: '5 லட்சம் மீனவ குடும்பங்களுக்கு துறைமுக உள்கட்டமைப்பு, படகு மானியம், உயிர் காப்பீடு மற்றும் மீன் பதப்படுத்தல் ஆதரவு.',
  },
  {
    id: 'public-dept', code: 'PUB', name_en: 'Public (General Administration)', name_ta: 'பொது (பொது நிர்வாகம்)',
    slug: 'public-dept', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Secretariat coordination, Chief Secretary\'s office, inter-departmental policy, Governor liaison, All-India Service cadre management, and ceremonial functions.',
    purpose_ta: 'செயலக ஒருங்கிணைப்பு, முதன்மை செயலாளர் அலுவலகம், மாநிலாளர் தொடர்பு, அகில இந்திய சேவை நடைமுறை.',
    citizens_served_en: 'All citizens — secretariat governance', citizens_served_ta: 'அனைத்து குடிமக்கள் — செயலக ஆட்சி',
    budget_cr: 1800, revenue_cr: 100, central_funding_pct: 5, state_funding_pct: 95,
    total_staff_sanctioned: 6000, total_staff_filled: 5400,
    current_secretary_en: 'Chief Secretary to Government',
    flag_count_red: 0, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Secretariat coordination, Chief Secretary\'s office, inter-departmental policy, and All-India Service cadre management.',
    description_ta: 'செயலக ஒருங்கிணைப்பு, முதன்மை செயலாளர் அலுவலகம் மற்றும் அகில இந்திய சேவை நடைமுறை மேலாண்மை.',
  },
  {
    id: 'secretariat-admin', code: 'SA', name_en: 'Secretariat Administration', name_ta: 'செயலக நிர்வாகம்',
    slug: 'secretariat-admin', dept_type: 'administration', established_year: 1947,
    purpose_en: 'Manages the Fort St. George Secretariat operations — file management, staff postings, record rooms, and government printing.',
    purpose_ta: 'ஃபோர்ட் செயின்ட் ஜார்ஜ் செயலக செயல்பாடுகள் — கோப்பு மேலாண்மை, பணியாளர் நியமனம், ஆவண அறைகள்.',
    citizens_served_en: 'Internal administrative function', citizens_served_ta: 'உள்நிர்வாக செயல்பாடு',
    budget_cr: 400, revenue_cr: 30, central_funding_pct: 0, state_funding_pct: 100,
    total_staff_sanctioned: 5000, total_staff_filled: 4200,
    current_secretary_en: 'Secretary, Secretariat Administration Dept',
    flag_count_red: 0, flag_count_amber: 1, flag_count_green: 1,
    description_en: 'Manages Secretariat file movement, staff allocations, record rooms, stationery, and government printing press operations.',
    description_ta: 'செயலக கோப்பு இயக்கம், பணியாளர் ஒதுக்கீடு, ஆவண அறைகள் மற்றும் அரசு அச்சக செயல்பாடுகள்.',
  },
  {
    id: 'hrm', code: 'HRM', name_en: 'Human Resources Management', name_ta: 'மனித வள மேலாண்மை',
    slug: 'hrm', dept_type: 'administration', established_year: 2001,
    purpose_en: 'Manages recruitment, training, and capacity building for all state government employees. Oversees TNPSC, Anna Institute of Management, and TNSLAS.',
    purpose_ta: 'அனைத்து மாநில அரசு ஊழியர்களுக்கு ஆட்சேர்ப்பு, பயிற்சி மேலாண்மை. TNPSC, அண்ணா மேலாண்மை நிறுவனம் மேலாண்மை.',
    citizens_served_en: '10 lakh state government employees', citizens_served_ta: '10 லட்சம் மாநில அரசு ஊழியர்கள்',
    budget_cr: 600, revenue_cr: 50, central_funding_pct: 10, state_funding_pct: 90,
    total_staff_sanctioned: 2000, total_staff_filled: 1800,
    current_secretary_en: 'Secretary, Human Resources Management Dept',
    flag_count_red: 0, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Manages government employee recruitment, training through Anna Institute of Management, and TNPSC coordination.',
    description_ta: 'அரசு ஊழியர் ஆட்சேர்ப்பு, அண்ணா மேலாண்மை நிறுவனம் மூலம் பயிற்சி மற்றும் TNPSC ஒருங்கிணைப்பு.',
  },
  {
    id: 'stationery', code: 'STP', name_en: 'Stationery & Printing', name_ta: 'எழுதுபொருள் & அச்சுத்துறை',
    slug: 'stationery', dept_type: 'administration', established_year: 1920,
    purpose_en: 'Manages government press for official publications, Tamil Nadu Government Gazette, textbooks printed by TNTB, and stationery procurement.',
    purpose_ta: 'அலுவலக வெளியீடுகளுக்கு அரசு அச்சகம், தமிழ்நாடு அரசு வர்த்தமானி, TNTB பாடப்புத்தகங்கள் மற்றும் எழுதுபொருள் கொள்முதல்.',
    citizens_served_en: 'Internal government function', citizens_served_ta: 'அரசு உள் செயல்பாடு',
    budget_cr: 350, revenue_cr: 80, central_funding_pct: 0, state_funding_pct: 100,
    total_staff_sanctioned: 3000, total_staff_filled: 2400,
    current_secretary_en: 'Director of Stationery and Printing',
    flag_count_red: 0, flag_count_amber: 1, flag_count_green: 1,
    description_en: 'Government press for Gazette, textbooks, official documents, and stationery procurement for all departments.',
    description_ta: 'வர்த்தமானி, பாடப்புத்தகங்கள், அலுவலக ஆவணங்கள் மற்றும் அனைத்து துறைகளுக்கும் எழுதுபொருள் கொள்முதல்.',
  },
  {
    id: 'differently-abled', code: 'DAW', name_en: 'Differently Abled Persons Welfare', name_ta: 'மாற்றுத்திறனாளிகள் நலன்',
    slug: 'differently-abled', dept_type: 'welfare', established_year: 1990,
    purpose_en: 'Supports 16.4 lakh differently abled persons with disability certificates, aids & appliances, special schools, monthly assistance of ₹1,500, and ADIP scheme.',
    purpose_ta: '16.4 லட்சம் மாற்றுத்திறனாளிகளுக்கு ஊனமுற்றோர் சான்றிதழ், உதவிக்கருவிகள், சிறப்பு பள்ளிகள், மாத உதவி ₹1,500.',
    citizens_served_en: '16.4 lakh differently abled persons', citizens_served_ta: '16.4 லட்சம் மாற்றுத்திறனாளிகள்',
    budget_cr: 2200, revenue_cr: 40, central_funding_pct: 30, state_funding_pct: 70,
    total_staff_sanctioned: 4500, total_staff_filled: 3800,
    current_secretary_en: 'Commissioner for Welfare of the Differently Abled',
    flag_count_red: 1, flag_count_amber: 2, flag_count_green: 1,
    description_en: 'Provides disability certificates, aids & appliances, special schools, monthly assistance, and ADIP scheme benefits to 16.4 lakh differently abled persons.',
    description_ta: 'ஊனமுற்றோர் சான்றிதழ், உதவிக்கருவிகள், சிறப்பு பள்ளிகள், மாத உதவி மற்றும் ADIP திட்ட நன்மைகள்.',
  },
  {
    id: 'legislative-assembly', code: 'LA', name_en: 'Legislative Assembly Secretariat', name_ta: 'சட்டமன்ற செயலகம்',
    slug: 'legislative-assembly', dept_type: 'administration', established_year: 1921,
    purpose_en: 'Manages TN Legislative Assembly operations — 234 MLAs, session conduct, library, research service, question management, and bill drafting support.',
    purpose_ta: 'TN சட்டமன்ற செயல்பாடுகள் — 234 சட்டமன்ற உறுப்பினர்கள், கூட்டத்தொடர் நடத்தல், ஆராய்ச்சி சேவை.',
    citizens_served_en: '234 MLAs; all TN citizens through legislation', citizens_served_ta: '234 சட்டமன்ற உறுப்பினர்கள்; சட்டவாக்கம் மூலம் அனைத்து குடிமக்கள்',
    budget_cr: 280, revenue_cr: 20, central_funding_pct: 0, state_funding_pct: 100,
    total_staff_sanctioned: 1500, total_staff_filled: 1300,
    current_secretary_en: 'Secretary, Tamil Nadu Legislative Assembly',
    flag_count_red: 0, flag_count_amber: 1, flag_count_green: 2,
    description_en: 'Manages Legislative Assembly sessions, 234 MLA support services, library, research, and bill drafting assistance.',
    description_ta: 'சட்டமன்ற கூட்டத்தொடர்கள், 234 சட்டமன்ற உறுப்பினர் ஆதரவு சேவைகள், நூலகம் மற்றும் மசோதா வரைவு உதவி.',
  },
]

export function getDeptsByType(type: string): Department[] {
  if (type === 'all') return DEPARTMENTS
  return DEPARTMENTS.filter(d => d.dept_type === type)
}

export function getDeptBySlug(slug: string): Department | undefined {
  return DEPARTMENTS.find(d => d.slug === slug)
}

export function formatCr(cr: number): string {
  if (cr >= 100000) return `₹${(cr / 100000).toFixed(2)}L Cr`
  return `₹${cr.toLocaleString('en-IN')} Cr`
}
