import { Department, Scheme, Flag, Entitlement, Process, OutcomeMetric } from '@/types'

export const HEALTH_DEPT: Department = {
  id: 'health',
  code: 'HEALTH',
  name_en: 'Health & Family Welfare',
  name_ta: 'சுகாதாரம் & குடும்ப நலன்',
  slug: 'health',
  dept_type: 'welfare',
  established_year: 1921,
  purpose_en: 'Established in 1921 under the Madras Presidency. Provides free healthcare to all citizens through government hospitals, primary health centres, and community health centres. Ensures no citizen is denied treatment due to inability to pay.',
  purpose_ta: '1921-ல் மதராஸ் மாகாணத்தில் நிறுவப்பட்டது. அரசு மருத்துவமனைகள், PHC-கள் மூலம் இலவச சுகாதார சேவை வழங்குகிறது. பொருளாதார நிலை காரணமாக எவரும் சிகிச்சை மறுக்கப்படாத வகையில் செயல்படுகிறது.',
  citizens_served_en: '8 crore citizens of Tamil Nadu',
  citizens_served_ta: 'தமிழ்நாட்டின் 8 கோடி குடிமக்கள்',
  budget_cr: 21000,
  revenue_cr: 1200,
  central_funding_pct: 30,
  state_funding_pct: 70,
  total_staff_sanctioned: 120000,
  total_staff_filled: 94000,
  current_secretary_en: 'Additional Chief Secretary, Health & FW Dept',
  flag_count_red: 3,
  flag_count_amber: 2,
  flag_count_green: 2,
}

export const HEALTH_SERVICES = [
  {
    if_you_are_en: 'Sick and have no money',
    you_get_en: 'Free treatment at any of 2,780 government hospitals and 1,776 Primary Health Centres',
    if_you_are_ta: 'நோய்வாய்ப்பட்டு பணமில்லாவிட்டால்',
    you_get_ta: '2,780 அரசு மருத்துவமனைகள் மற்றும் 1,776 PHC-களில் இலவச சிகிச்சை',
  },
  {
    if_you_are_en: 'Having a baby',
    you_get_en: 'Free delivery at any govt hospital + JSY cash assistance of ₹1,000 for institutional delivery',
    if_you_are_ta: 'கர்ப்பிணியாக இருந்தால்',
    you_get_ta: 'இலவச பிரசவம் + JSY ₹1,000 பணம்',
  },
  {
    if_you_are_en: 'A BPL family needing surgery',
    you_get_en: 'CMCHIS health insurance covers up to ₹5 lakh per year at empanelled hospitals',
    if_you_are_ta: 'BPL குடும்பத்தினர், அறுவை சிகிச்சை தேவை',
    you_get_ta: 'CMCHIS காப்பீட்டில் ஆண்டுக்கு ₹5 லட்சம் வரை',
  },
  {
    if_you_are_en: 'In a medical emergency',
    you_get_en: '108 ambulance anywhere in TN — free, available 24/7',
    if_you_are_ta: 'மருத்துவ அவசரநிலையில்',
    you_get_ta: '108 ஆம்புலன்ஸ் — இலவசம், 24/7',
  },
  {
    if_you_are_en: 'A child under 5',
    you_get_en: 'Free immunisation for all 12 vaccine-preventable diseases under Universal Immunisation Programme',
    if_you_are_ta: '5 வயதுக்குட்பட்ட குழந்தை',
    you_get_ta: '12 நோய்களுக்கு இலவச தடுப்பூசி',
  },
  {
    if_you_are_en: 'Needing medicines',
    you_get_en: 'Free essential medicines at all government health facilities under TNMSC free medicine scheme — 348 generic medicines available',
    if_you_are_ta: 'மருந்துகள் தேவைப்பட்டால்',
    you_get_ta: 'அனைத்து அரசு மருத்துவமனைகளிலும் 348 இலவச மருந்துகள்',
  },
  {
    if_you_are_en: 'Elderly or unable to travel',
    you_get_en: 'Makkalai Thedi Maruthuvam — health worker visits your home to screen for 27 diseases',
    if_you_are_ta: 'வயதானவர் அல்லது பயணிக்க இயலாதவர்',
    you_get_ta: 'மக்களை தேடி மருத்துவம் — 27 நோய்களுக்கு வீட்டில் பரிசோதனை',
  },
]

export const HEALTH_SCHEMES: Scheme[] = [
  {
    id: 'cmchis',
    name_en: 'Chief Minister Comprehensive Health Insurance Scheme (CMCHIS)',
    name_ta: 'முதலமைச்சரின் விரிவான சுகாதார காப்பீட்டுத் திட்டம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2012,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1.75 crore families',
    eligibility_en: 'BPL families and those earning below ₹72,000 per year. Annual health cover of ₹5 lakh per family.',
    eligibility_ta: 'BPL குடும்பங்கள் மற்றும் ஆண்டு வருமானம் ₹72,000-க்கு கீழ் உள்ளவர்கள். ஆண்டுக்கு ₹5 லட்சம் வரை.',
    how_to_apply_en: 'Register at nearest government hospital with Aadhaar, income certificate, and ration card. No premium payment required.',
    source_url: 'https://www.cmchistn.com',
  },
  {
    id: 'jsy',
    name_en: 'Janani Suraksha Yojana (JSY)',
    name_ta: 'ஜனனி சுரட்சா யோஜனா',
    dept_id: 'health',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2005,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '5 lakh deliveries per year',
    eligibility_en: 'All pregnant women delivering in government hospitals. ₹1,000 cash assistance for institutional delivery in TN.',
    eligibility_ta: 'அரசு மருத்துவமனையில் பிரசவிக்கும் அனைத்து கர்ப்பிணி பெண்கள். ₹1,000 பணம்.',
    how_to_apply_en: 'Register at nearest PHC or govt hospital during antenatal check-up. ASHA worker will assist.',
    source_url: 'https://nhm.gov.in',
  },
  {
    id: 'makkalai-thedi',
    name_en: 'Makkalai Thedi Maruthuvam',
    name_ta: 'மக்களை தேடி மருத்துவம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'extended',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '55 lakh patients screened',
    eligibility_en: 'All citizens. Medical teams visit homes to screen for diabetes, hypertension, cancer, and TB. No eligibility restriction.',
    eligibility_ta: 'அனைத்து குடிமக்களும். மருத்துவ குழு வீட்டிற்கு வந்து பரிசோதிக்கும்.',
    how_to_apply_en: 'No application needed. Medical team visits your home. You can also visit nearest PHC.',
    source_url: 'https://www.tnhealth.tn.gov.in',
  },
  {
    id: 'nhm',
    name_en: 'National Health Mission (NHM)',
    name_ta: 'தேசிய சுகாதார இயக்கம்',
    dept_id: 'health',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2005,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: 'All TN citizens — strengthens rural PHC infrastructure',
    eligibility_en: 'All citizens — benefits delivered through government PHCs, hospitals, and ASHA workers.',
    eligibility_ta: 'அனைத்து குடிமக்களும் — PHC-கள் மற்றும் ASHA ஊழியர்கள் மூலம்.',
    how_to_apply_en: 'No application needed. Benefits available at all government PHCs and hospitals.',
    source_url: 'https://nhm.gov.in',
  },
]

export const HEALTH_PROCESSES: Process[] = [
  {
    id: 'phc-treatment',
    name_en: 'Getting treatment at a PHC',
    name_ta: 'PHC-ல் சிகிச்சை பெறுவது',
    official_steps: [
      'Walk in to nearest PHC — no appointment needed',
      'Register at OPD counter (free)',
      'See the doctor on duty',
      'Receive free prescription',
      'Collect free medicines from pharmacy counter',
    ],
    official_days: 0,
    reality_days: 0,
    stall_point_en: 'Doctor may not be present — 23% PHC medical officer posts are vacant in 8 districts. Medicine stock varies — some medicines regularly out of stock at PHC level.',
    documents_required: [
      'No documents required for basic OPD treatment',
      'Aadhaar for CMCHIS or JSY benefits',
    ],
    portal_url: undefined,
  },
  {
    id: 'cmchis-claim',
    name_en: 'Filing a CMCHIS insurance claim',
    name_ta: 'CMCHIS காப்பீடு கோரிக்கை',
    official_steps: [
      'Identify empanelled hospital near you (list on cmchistn.com)',
      'Show ration card and Aadhaar at hospital',
      'Hospital verifies eligibility online',
      'Treatment begins — cashless',
      'Hospital claims reimbursement from govt (citizen not involved)',
    ],
    official_days: 1,
    reality_days: 1,
    stall_point_en: 'Hospital may claim you are not in the system — verify your eligibility online at cmchistn.com before going. Some empanelled hospitals refuse to admit CMCHIS patients citing reimbursement delays.',
    documents_required: [
      'Aadhaar card',
      'Ration card',
      'Income certificate if not BPL card holder',
    ],
    portal_url: 'https://www.cmchistn.com',
  },
  {
    id: '108-ambulance',
    name_en: 'Calling 108 Ambulance (Emergency)',
    name_ta: '108 ஆம்புலன்ஸ் அழைக்க',
    official_steps: [
      'Call 108 from any mobile or landline — free, 24/7',
      'Give your location clearly — nearest landmark, street name, district',
      'Stay on the line — dispatcher tracks ambulance',
      'Ambulance carries paramedic + basic life support',
      'Transported to nearest government hospital casualty',
    ],
    official_days: 0,
    reality_days: 0,
    stall_point_en: 'Urban response target: 8 minutes. Actual urban average: 13.2 minutes. Rural average: 24 minutes vs 20-minute target. GPS lock failure in newly developed areas.',
    documents_required: [],
    portal_url: undefined,
  },
]

export const HEALTH_METRICS: OutcomeMetric[] = [
  {
    id: 'phc-doctor',
    label_en: 'PHC medical officer vacancy rate',
    label_ta: 'PHC மருத்துவர் காலி பணியிட விகிதம்',
    official_target: '0% vacancy — all posts filled',
    actual_value: '23% vacant in 8 districts (2024)',
    source: 'Assembly Q&A + Dept Annual Report',
    source_url: 'https://tnassembly.gov.in',
    trend: 'flat',
  },
  {
    id: 'infant-mortality',
    label_en: 'Infant mortality rate (per 1,000 live births)',
    label_ta: 'குழந்தை இறப்பு விகிதம்',
    official_target: 'Less than 15 (SDG target)',
    actual_value: '19 (NFHS-5, 2021)',
    source: 'National Family Health Survey 5',
    source_url: 'https://rchiips.org/nfhs/nfhs-5.shtml',
    trend: 'down',
  },
  {
    id: 'institutional-delivery',
    label_en: 'Institutional delivery rate',
    label_ta: 'மருத்துவமனை பிரசவ விகிதம்',
    official_target: '100%',
    actual_value: '99.7% (NFHS-5)',
    source: 'NFHS-5 Tamil Nadu factsheet',
    source_url: 'https://rchiips.org/nfhs/nfhs-5.shtml',
    trend: 'up',
  },
  {
    id: 'medicine-availability',
    label_en: 'Essential medicine availability at PHCs',
    label_ta: 'PHC-களில் மருந்து கிடைக்கும் விகிதம்',
    official_target: '100% availability',
    actual_value: 'Data not publicly published — RTI needed',
    source: 'TNMSC internal records — not disclosed',
    source_url: 'https://www.tnmsc.com',
    trend: 'flat',
  },
]

export const HEALTH_FLAGS: Flag[] = [
  {
    id: 'health-spend-low',
    severity: 'red',
    title_en: 'Health spend below national average — 3 years running',
    title_ta: 'சுகாதார செலவு தேசிய சராசரிக்கு கீழ்',
    body_en: 'TN spends ₹2,575 per person per year on health. National average is ₹3,100. TN has been below average in 2022-23, 2023-24, and 2024-25.',
    body_ta: 'TN ஒவ்வொருவருக்கும் ஆண்டுக்கு ₹2,575 செலவிடுகிறது. தேசிய சராசரி ₹3,100.',
    source_org: 'PRS India',
    source_doc: 'TN Budget Analysis 2024-25',
    source_year: '2025',
    source_url: 'https://prsindia.org/budgets/states/tamil-nadu-budget-analysis-2024-25',
  },
  {
    id: 'phc-vacancy',
    severity: 'red',
    title_en: 'PHC doctor vacancy — not publicly reported',
    title_ta: 'PHC மருத்துவர் காலி பணியிடங்கள் — வெளியிடப்படவில்லை',
    body_en: 'Exact PHC-level doctor vacancy data is not published. Assembly Q&A answers confirm significant vacancies in rural districts but no consolidated district-wise data is available online.',
    body_ta: 'துல்லியமான PHC மட்ட மருத்துவர் காலி பணியிட தரவு வெளியிடப்படவில்லை.',
    source_org: 'TN Assembly Q&A 2023',
    source_doc: 'Question on health dept vacancies — minister answer',
    source_year: '2023',
    source_url: 'https://tnassembly.gov.in',
  },
  {
    id: 'medicine-data',
    severity: 'amber',
    title_en: 'Medicine stock data at PHCs — never publicly disclosed',
    title_ta: 'PHC மருந்து இருப்பு தகவல் — வெளியிடப்படவில்லை',
    body_en: 'TNMSC has real-time medicine stock data for all PHCs. This has never been made public. Citizens travel to PHCs without knowing if medicines are available.',
    body_ta: 'TNMSC-இடம் அனைத்து PHC-களுக்கும் மருந்து இருப்பு தகவல் உள்ளது. இது பொதுமக்களுக்கு வழங்கப்படவில்லை.',
    source_org: 'TNMSC',
    source_doc: 'Internal supply chain system — public disclosure: none',
    source_year: '2025',
    source_url: 'https://www.tnmsc.com',
  },
  {
    id: 'cmchis-reimbursement',
    severity: 'amber',
    title_en: 'CMCHIS reimbursement delays to hospitals reported',
    title_ta: 'CMCHIS மருத்துவமனை திருப்பிச் செலுத்தல் தாமதம்',
    body_en: 'Multiple hospitals have reported delays in CMCHIS reimbursement from the government. Some hospitals informally restrict CMCHIS admissions. Not officially acknowledged.',
    body_ta: 'பல மருத்துவமனைகள் CMCHIS திருப்பிச் செலுத்தல் தாமதம் பற்றி புகார் அளித்துள்ளன.',
    source_org: 'The Hindu Tamil',
    source_doc: 'Healthcare access reporting 2024',
    source_year: '2024',
    source_url: 'https://www.thehindu.com',
  },
  {
    id: 'institutional-delivery-green',
    severity: 'green',
    title_en: 'Institutional delivery rate — 99.7% verified',
    title_ta: 'மருத்துவமனை பிரசவ விகிதம் — 99.7% சரிபார்க்கப்பட்டது',
    body_en: 'NFHS-5 confirms TN institutional delivery rate at 99.7% — among the highest in India. This is independently verified by a national survey.',
    body_ta: 'NFHS-5 தமிழ்நாட்டின் மருத்துவமனை பிரசவ விகிதம் 99.7% என்று உறுதிப்படுத்துகிறது — இந்தியாவிலேயே மிக அதிகம்.',
    source_org: 'NFHS-5',
    source_doc: 'Tamil Nadu State Factsheet',
    source_year: '2021',
    source_url: 'https://rchiips.org/nfhs/nfhs-5.shtml',
  },
]

export const HEALTH_ENTITLEMENTS: Entitlement[] = [
  {
    id: 'free-treatment',
    dept_id: 'health',
    title_en: 'Free treatment at government hospitals',
    title_ta: 'அரசு மருத்துவமனைகளில் இலவச சிகிச்சை',
    what_you_get_en: 'Any citizen can walk into any government hospital and receive free OPD treatment, free essential medicines, and free emergency care — regardless of income.',
    what_you_get_ta: 'எந்த குடிமகனும் எந்த அரசு மருத்துவமனையிலும் இலவச OPD சிகிச்சை, இலவச மருந்துகள், இலவச அவசர சிகிச்சை பெறலாம்.',
    timeline_days: 0,
    legal_basis: 'TN Government Resolution — Universal Health Coverage commitment',
    how_to_claim_en: 'Walk into any government hospital. No card or document needed for emergency treatment.',
    escalation_en: 'If refused: Contact District Health Officer → Director of Public Health → Health Secretary.',
  },
  {
    id: 'cmchis-right',
    dept_id: 'health',
    title_en: 'CMCHIS — ₹5 lakh annual health coverage',
    title_ta: 'CMCHIS — ஆண்டுக்கு ₹5 லட்சம் சுகாதார காப்பீடு',
    what_you_get_en: 'If you hold a BPL ration card or earn below ₹72,000 per year, you are entitled to ₹5 lakh annual health insurance at empanelled hospitals — no premium payment.',
    what_you_get_ta: 'BPL அட்டை அல்லது ஆண்டு வருமானம் ₹72,000-க்கு கீழ் இருந்தால், empanelled மருத்துவமனைகளில் ₹5 லட்சம் வரை இலவச சிகிச்சை.',
    timeline_days: 1,
    legal_basis: 'CMCHIS GO Ms 280 Health and Family Welfare Dept 2012',
    how_to_claim_en: 'Check eligibility at cmchistn.com. Go to empanelled hospital with Aadhaar + ration card. Hospital processes claim directly.',
    escalation_en: 'If hospital refuses: Call CMCHIS helpline 044-28592828. File complaint at cmchistn.com.',
  },
]
