import { Department, Scheme, Flag, Entitlement, Process, OutcomeMetric, OrgLevel, ContractWorkerCategory, LegalAppointment, Minister } from '@/types'

export const HEALTH_DEPT: Department = {
  id: 'health',
  code: 'HEALTH',
  name_en: 'Health & Family Welfare',
  name_ta: 'சுகாதாரம் & குடும்ப நலன்',
  slug: 'health',
  dept_type: 'welfare',
  established_year: 1921,
  purpose_en: 'Established in 1921 under the Madras Presidency. Provides free healthcare to all citizens through government hospitals, primary health centres, and community health centres. Ensures no citizen is denied treatment due to inability to pay.',
  purpose_ta: '1921-ல் மதராஸ் மாகாணத்தில் நிறுவப்பட்டது. அரசு மருத்துவமனைகள், PHC-கள் மூலம் இலவச சுகாதார சேவை வழங்குகிறது. பொருளாதார நிலை காரணமாக எவரும் சிகிச்சை மறுக்கப்படாத வகையில் செயல்படுகிறது.',
  citizens_served_en: '8 crore citizens of Tamil Nadu',
  citizens_served_ta: 'தமிழ்நாட்டின் 8 கோடி குடிமக்கள்',
  budget_cr: 21000,
  revenue_cr: 1200,
  central_funding_pct: 30,
  state_funding_pct: 70,
  total_staff_sanctioned: 120000,
  total_staff_filled: 94000,
  current_secretary_en: 'Additional Chief Secretary, Health & FW Dept',
  flag_count_red: 3,
  flag_count_amber: 2,
  flag_count_green: 2,
}

export const HEALTH_SERVICES = [
  {
    if_you_are_en: 'Sick and have no money',
    you_get_en: 'Free treatment at any of 2,780 government hospitals and 1,776 Primary Health Centres',
    if_you_are_ta: 'நோய்வாய்ப்பட்டு பணமில்லாவிட்டால்',
    you_get_ta: '2,780 அரசு மருத்துவமனைகள் மற்றும் 1,776 PHC-களில் இலவச சிகிச்சை',
  },
  {
    if_you_are_en: 'Having a baby',
    you_get_en: 'Free delivery at any govt hospital + JSY cash assistance of ₹1,000 for institutional delivery',
    if_you_are_ta: 'கர்ப்பிணியாக இருந்தால்',
    you_get_ta: 'இலவச பிரசவம் + JSY ₹1,000 பணம்',
  },
  {
    if_you_are_en: 'A BPL family needing surgery',
    you_get_en: 'CMCHIS health insurance covers up to ₹5 lakh per year at empanelled hospitals',
    if_you_are_ta: 'BPL குடும்பத்தினர், அறுவை சிகிச்சை தேவை',
    you_get_ta: 'CMCHIS காப்பீட்டில் ஆண்டுக்கு ₹5 லட்சம் வரை',
  },
  {
    if_you_are_en: 'In a medical emergency',
    you_get_en: '108 ambulance anywhere in TN — free, available 24/7',
    if_you_are_ta: 'மருத்துவ அவசரநிலையில்',
    you_get_ta: '108 ஆம்புலன்ஸ் — இலவசம், 24/7',
  },
  {
    if_you_are_en: 'A child under 5',
    you_get_en: 'Free immunisation for all 12 vaccine-preventable diseases under Universal Immunisation Programme',
    if_you_are_ta: '5 வயதுக்குட்பட்ட குழந்தை',
    you_get_ta: '12 நோய்களுக்கு இலவச தடுப்பூசி',
  },
  {
    if_you_are_en: 'Needing medicines',
    you_get_en: 'Free essential medicines at all government health facilities under TNMSC free medicine scheme — 348 generic medicines available',
    if_you_are_ta: 'மருந்துகள் தேவைப்பட்டால்',
    you_get_ta: 'அனைத்து அரசு மருத்துவமனைகளிலும் 348 இலவச மருந்துகள்',
  },
  {
    if_you_are_en: 'Elderly or unable to travel',
    you_get_en: 'Makkalai Thedi Maruthuvam — health worker visits your home to screen for 27 diseases',
    if_you_are_ta: 'வயதானவர் அல்லது பயணிக்க இயலாதவர்',
    you_get_ta: 'மக்களை தேடி மருத்துவம் — 27 நோய்களுக்கு வீட்டில் பரிசோதனை',
  },
]

export const HEALTH_SCHEMES: Scheme[] = [
  {
    id: 'cmchis',
    name_en: 'Chief Minister Comprehensive Health Insurance Scheme (CMCHIS)',
    name_ta: 'முதலமைச்சரின் விரிவான சுகாதார காப்பீட்டுத் திட்டம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2012,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1.75 crore families',
    eligibility_en: 'BPL families and those earning below ₹72,000 per year. Annual health cover of ₹5 lakh per family.',
    eligibility_ta: 'BPL குடும்பங்கள் மற்றும் ஆண்டு வருமானம் ₹72,000-க்கு கீழ் உள்ளவர்கள். ஆண்டுக்கு ₹5 லட்சம் வரை.',
    how_to_apply_en: 'Register at nearest government hospital with Aadhaar, income certificate, and ration card. No premium payment required.',
    source_url: 'https://www.cmchistn.com',
  },
  {
    id: 'jsy',
    name_en: 'Janani Suraksha Yojana (JSY)',
    name_ta: 'ஜனனி சுரட்சா யோஜனா',
    dept_id: 'health',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2005,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '5 lakh deliveries per year',
    eligibility_en: 'All pregnant women delivering in government hospitals. ₹1,000 cash assistance for institutional delivery in TN.',
    eligibility_ta: 'அரசு மருத்துவமனையில் பிரசவிக்கும் அனைத்து கர்ப்பிணி பெண்கள். ₹1,000 பணம்.',
    how_to_apply_en: 'Register at nearest PHC or govt hospital during antenatal check-up. ASHA worker will assist.',
    source_url: 'https://nhm.gov.in',
  },
  {
    id: 'makkalai-thedi',
    name_en: 'Makkalai Thedi Maruthuvam',
    name_ta: 'மக்களை தேடி மருத்துவம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'extended',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '55 lakh patients screened',
    eligibility_en: 'All citizens. Medical teams visit homes to screen for diabetes, hypertension, cancer, and TB. No eligibility restriction.',
    eligibility_ta: 'அனைத்து குடிமக்களும். மருத்துவ குழு வீட்டிற்கு வந்து பரிசோதிக்கும்.',
    how_to_apply_en: 'No application needed. Medical team visits your home. You can also visit nearest PHC.',
    source_url: 'https://www.tnhealth.tn.gov.in',
  },
  {
    id: 'nhm',
    name_en: 'National Health Mission (NHM)',
    name_ta: 'தேசிய சுகாதார இயக்கம்',
    dept_id: 'health',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2005,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: 'All TN citizens — strengthens rural PHC infrastructure',
    eligibility_en: 'All citizens — benefits delivered through government PHCs, hospitals, and ASHA workers.',
    eligibility_ta: 'அனைத்து குடிமக்களும் — PHC-கள் மற்றும் ASHA ஊழியர்கள் மூலம்.',
    how_to_apply_en: 'No application needed. Benefits available at all government PHCs and hospitals.',
    source_url: 'https://nhm.gov.in',
  },
]

export const HEALTH_PROCESSES: Process[] = [
  {
    id: 'phc-treatment',
    name_en: 'Getting treatment at a PHC',
    name_ta: 'PHC-ல் சிகிச்சை பெறுவது',
    official_steps: [
      'Walk in to nearest PHC — no appointment needed',
      'Register at OPD counter (free)',
      'See the doctor on duty',
      'Receive free prescription',
      'Collect free medicines from pharmacy counter',
    ],
    official_days: 0,
    reality_days: 0,
    stall_point_en: 'Doctor may not be present — 23% PHC medical officer posts are vacant in 8 districts. Medicine stock varies — some medicines regularly out of stock at PHC level.',
    documents_required: [
      'No documents required for basic OPD treatment',
      'Aadhaar for CMCHIS or JSY benefits',
    ],
    portal_url: undefined,
  },
  {
    id: 'cmchis-claim',
    name_en: 'Filing a CMCHIS insurance claim',
    name_ta: 'CMCHIS காப்பீடு கோரிக்கை',
    official_steps: [
      'Identify empanelled hospital near you (list on cmchistn.com)',
      'Show ration card and Aadhaar at hospital',
      'Hospital verifies eligibility online',
      'Treatment begins — cashless',
      'Hospital claims reimbursement from govt (citizen not involved)',
    ],
    official_days: 1,
    reality_days: 1,
    stall_point_en: 'Hospital may claim you are not in the system — verify your eligibility online at cmchistn.com before going. Some empanelled hospitals refuse to admit CMCHIS patients citing reimbursement delays.',
    documents_required: [
      'Aadhaar card',
      'Ration card',
      'Income certificate if not BPL card holder',
    ],
    portal_url: 'https://www.cmchistn.com',
  },
  {
    id: '108-ambulance',
    name_en: 'Calling 108 Ambulance (Emergency)',
    name_ta: '108 ஆம்புலன்ஸ் அழைக்க',
    official_steps: [
      'Call 108 from any mobile or landline — free, 24/7',
      'Give your location clearly — nearest landmark, street name, district',
      'Stay on the line — dispatcher tracks ambulance',
      'Ambulance carries paramedic + basic life support',
      'Transported to nearest government hospital casualty',
    ],
    official_days: 0,
    reality_days: 0,
    stall_point_en: 'Urban response target: 8 minutes. Actual urban average: 13.2 minutes. Rural average: 24 minutes vs 20-minute target. GPS lock failure in newly developed areas.',
    documents_required: [],
    portal_url: undefined,
  },
]

export const HEALTH_METRICS: OutcomeMetric[] = [
  {
    id: 'phc-doctor',
    label_en: 'PHC medical officer vacancy rate',
    label_ta: 'PHC மருத்துவர் காலி பணியிட விகிதம்',
    official_target: '0% vacancy — all posts filled',
    actual_value: '23% vacant in 8 districts (2024)',
    source: 'Assembly Q&A + Dept Annual Report',
    source_url: 'https://tnassembly.gov.in',
    trend: 'flat',
  },
  {
    id: 'infant-mortality',
    label_en: 'Infant mortality rate (per 1,000 live births)',
    label_ta: 'குழந்தை இறப்பு விகிதம்',
    official_target: 'Less than 15 (SDG target)',
    actual_value: '19 (NFHS-5, 2021)',
    source: 'National Family Health Survey 5',
    source_url: 'https://rchiips.org/nfhs/nfhs-5.shtml',
    trend: 'down',
  },
  {
    id: 'institutional-delivery',
    label_en: 'Institutional delivery rate',
    label_ta: 'மருத்துவமனை பிரசவ விகிதம்',
    official_target: '100%',
    actual_value: '99.7% (NFHS-5)',
    source: 'NFHS-5 Tamil Nadu factsheet',
    source_url: 'https://rchiips.org/nfhs/nfhs-5.shtml',
    trend: 'up',
  },
  {
    id: 'medicine-availability',
    label_en: 'Essential medicine availability at PHCs',
    label_ta: 'PHC-களில் மருந்து கிடைக்கும் விகிதம்',
    official_target: '100% availability',
    actual_value: 'Data not publicly published — RTI needed',
    source: 'TNMSC internal records — not disclosed',
    source_url: 'https://www.tnmsc.com',
    trend: 'flat',
  },
]

export const HEALTH_FLAGS: Flag[] = [
  {
    id: 'health-spend-low',
    severity: 'red',
    title_en: 'Health spend below national average — 3 years running',
    title_ta: 'சுகாதார செலவு தேசிய சராசரிக்கு கீழ்',
    body_en: 'TN spends ₹2,575 per person per year on health. National average is ₹3,100. TN has been below average in 2022-23, 2023-24, and 2024-25.',
    body_ta: 'TN ஒவ்வொருவருக்கும் ஆண்டுக்கு ₹2,575 செலவிடுகிறது. தேசிய சராசரி ₹3,100.',
    source_org: 'PRS India',
    source_doc: 'TN Budget Analysis 2024-25',
    source_year: '2025',
    source_url: 'https://prsindia.org/budgets/states/tamil-nadu-budget-analysis-2024-25',
  },
  {
    id: 'phc-vacancy',
    severity: 'red',
    title_en: 'PHC doctor vacancy — not publicly reported',
    title_ta: 'PHC மருத்துவர் காலி பணியிடங்கள் — வெளியிடப்படவில்லை',
    body_en: 'Exact PHC-level doctor vacancy data is not published. Assembly Q&A answers confirm significant vacancies in rural districts but no consolidated district-wise data is available online.',
    body_ta: 'துல்லியமான PHC மட்ட மருத்துவர் காலி பணியிட தரவு வெளியிடப்படவில்லை.',
    source_org: 'TN Assembly Q&A 2023',
    source_doc: 'Question on health dept vacancies — minister answer',
    source_year: '2023',
    source_url: 'https://tnassembly.gov.in',
  },
  {
    id: 'medicine-data',
    severity: 'amber',
    title_en: 'Medicine stock data at PHCs — never publicly disclosed',
    title_ta: 'PHC மருந்து இருப்பு தகவல் — வெளியிடப்படவில்லை',
    body_en: 'TNMSC has real-time medicine stock data for all PHCs. This has never been made public. Citizens travel to PHCs without knowing if medicines are available.',
    body_ta: 'TNMSC-இடம் அனைத்து PHC-களுக்கும் மருந்து இருப்பு தகவல் உள்ளது. இது பொதுமக்களுக்கு வழங்கப்படவில்லை.',
    source_org: 'TNMSC',
    source_doc: 'Internal supply chain system — public disclosure: none',
    source_year: '2025',
    source_url: 'https://www.tnmsc.com',
  },
  {
    id: 'cmchis-reimbursement',
    severity: 'amber',
    title_en: 'CMCHIS reimbursement delays to hospitals reported',
    title_ta: 'CMCHIS மருத்துவமனை திருப்பிச் செலுத்தல் தாமதம்',
    body_en: 'Multiple hospitals have reported delays in CMCHIS reimbursement from the government. Some hospitals informally restrict CMCHIS admissions. Not officially acknowledged.',
    body_ta: 'பல மருத்துவமனைகள் CMCHIS திருப்பிச் செலுத்தல் தாமதம் பற்றி புகார் அளித்துள்ளன.',
    source_org: 'The Hindu Tamil',
    source_doc: 'Healthcare access reporting 2024',
    source_year: '2024',
    source_url: 'https://www.thehindu.com',
  },
  {
    id: 'institutional-delivery-green',
    severity: 'green',
    title_en: 'Institutional delivery rate — 99.7% verified',
    title_ta: 'மருத்துவமனை பிரசவ விகிதம் — 99.7% சரிபார்க்கப்பட்டது',
    body_en: 'NFHS-5 confirms TN institutional delivery rate at 99.7% — among the highest in India. This is independently verified by a national survey.',
    body_ta: 'NFHS-5 தமிழ்நாட்டின் மருத்துவமனை பிரசவ விகிதம் 99.7% என்று உறுதிப்படுத்துகிறது — இந்தியாவிலேயே மிக அதிகம்.',
    source_org: 'NFHS-5',
    source_doc: 'Tamil Nadu State Factsheet',
    source_year: '2021',
    source_url: 'https://rchiips.org/nfhs/nfhs-5.shtml',
  },
]

export const HEALTH_ENTITLEMENTS: Entitlement[] = [
  {
    id: 'free-treatment',
    dept_id: 'health',
    title_en: 'Free treatment at government hospitals',
    title_ta: 'அரசு மருத்துவமனைகளில் இலவச சிகிச்சை',
    what_you_get_en: 'Any citizen can walk into any government hospital and receive free OPD treatment, free essential medicines, and free emergency care — regardless of income.',
    what_you_get_ta: 'எந்த குடிமகனும் எந்த அரசு மருத்துவமனையிலும் இலவச OPD சிகிச்சை, இலவச மருந்துகள், இலவச அவசர சிகிச்சை பெறலாம்.',
    timeline_days: 0,
    legal_basis: 'TN Government Resolution — Universal Health Coverage commitment',
    how_to_claim_en: 'Walk into any government hospital. No card or document needed for emergency treatment.',
    escalation_en: 'If refused: Contact District Health Officer → Director of Public Health → Health Secretary.',
  },
  {
    id: 'cmchis-right',
    dept_id: 'health',
    title_en: 'CMCHIS — ₹5 lakh annual health coverage',
    title_ta: 'CMCHIS — ஆண்டுக்கு ₹5 லட்சம் சுகாதார காப்பீடு',
    what_you_get_en: 'If you hold a BPL ration card or earn below ₹72,000 per year, you are entitled to ₹5 lakh annual health insurance at empanelled hospitals — no premium payment.',
    what_you_get_ta: 'BPL அட்டை அல்லது ஆண்டு வருமானம் ₹72,000-க்கு கீழ் இருந்தால், empanelled மருத்துவமனைகளில் ₹5 லட்சம் வரை இலவச சிகிச்சை.',
    timeline_days: 1,
    legal_basis: 'CMCHIS GO Ms 280 Health and Family Welfare Dept 2012',
    how_to_claim_en: 'Check eligibility at cmchistn.com. Go to empanelled hospital with Aadhaar + ration card. Hospital processes claim directly.',
    escalation_en: 'If hospital refuses: Call CMCHIS helpline 044-28592828. File complaint at cmchistn.com.',
  },
]

// ── ORG LEVELS ───────────────────────────────────────────────────

export const HEALTH_ORG_LEVELS: OrgLevel[] = [
  {
    id: 'health-l1',
    dept_id: 'health',
    level: 1,
    designation_en: 'Principal Secretary / Secretary, Health',
    designation_ta: 'தலைமை செயலாளர் / செயலாளர், சுகாதாரம்',
    cadre: 'IAS',
    recruitment_body: 'UPSC — All India Service',
    pay_min: 144200,
    pay_max: 225000,
    sanctioned_posts: 1,
    filled_posts: 1,
    data_quality_staffing: 'available',
    citizen_facing: false,
    decision_powers_en: [
      'Issue Government Orders on health policy',
      'Release funds to Directorate',
      'Approve state-level procurement above Rs 10 crore',
      'Represent department in Cabinet',
      'Sign MOUs with Central government',
    ],
    decision_limitations_en: [
      'Cannot approve expenditure beyond budget allocation without Finance concurrence',
      'Cannot alter scheme design of Central schemes unilaterally',
      'Cannot override Cabinet decisions',
      'Cannot recruit directly — must go through TNPSC or MRBC',
      'Cannot release Central funds — only state funds',
    ],
    for_citizen_problem_en: 'Secretary level is not a citizen contact point. For systemic failures only — approach via RTI or through MLA/MP.',
    transfer_authority: 'State Government (Chief Minister and Chief Secretary)',
    typical_tenure_months: 18,
    source: 'TN Financial Code · Allocation of Business Rules',
  },
  {
    id: 'health-l2',
    dept_id: 'health',
    level: 2,
    designation_en: 'Commissioner of Health and Family Welfare',
    designation_ta: 'சுகாதார ஆணையர்',
    cadre: 'IAS',
    recruitment_body: 'UPSC / Senior State Service empanelled',
    pay_min: 123100,
    pay_max: 215900,
    sanctioned_posts: 1,
    filled_posts: 1,
    data_quality_staffing: 'available',
    citizen_facing: false,
    decision_powers_en: [
      'Approve procurement up to Rs 10 crore',
      'Post and transfer officers up to Deputy Director level',
      'Approve district-level budget releases',
      'Issue operational circulars to all districts',
      'Approve hospital upgrades within sanctioned budget',
    ],
    decision_limitations_en: [
      'Cannot post or transfer Joint Directors without Secretary approval',
      'Cannot exceed sanctioned budget without GO amendment',
      'Cannot approve new schemes — only implement sanctioned ones',
      'Cannot hire permanent staff — only approve existing vacancies for MRBC',
      'Cannot waive tender procedures',
    ],
    for_citizen_problem_en: 'Contact for: systemic medicine shortage across multiple districts, PHC closure patterns, policy-level failures. Write to: The Commissioner of Health and Family Welfare, DMS Complex, Chennai 600 006.',
    transfer_authority: 'Health Secretary with Chief Secretary concurrence',
    typical_tenure_months: 24,
    source: 'TN Financial Code · Delegation of Financial Powers Rules',
  },
  {
    id: 'health-l3',
    dept_id: 'health',
    level: 3,
    designation_en: 'Joint Director of Health Services — District',
    designation_ta: 'மாவட்ட கூட்டு இயக்குநர், சுகாதாரம்',
    cadre: 'state_service',
    recruitment_body: 'Tamil Nadu Medical Services Recruitment Board',
    pay_min: 67700,
    pay_max: 208700,
    sanctioned_posts: 38,
    filled_posts: 31,
    data_quality_staffing: 'estimated',
    citizen_facing: false,
    decision_powers_en: [
      'Approve district medicine indent and distribution',
      'Post Medical Officers within district',
      'Approve PHC and hospital operational decisions',
      'Sanction local purchase up to Rs 10,000',
      'Recommend disciplinary action against staff',
    ],
    decision_limitations_en: [
      'Cannot transfer staff out of district without Commissioner approval',
      'Cannot approve capital expenditure',
      'Cannot hire any staff — all recruitment centralised',
      'Cannot waive medicine procurement norms',
      'Cannot exceed district budget allocation',
    ],
    for_citizen_problem_en: 'Contact for: multiple PHC failures in a district, district-level medicine shortage, recurring staff absence. Find contact at: district.tn.gov.in',
    transfer_authority: 'Commissioner of Health',
    typical_tenure_months: 30,
    source: 'TN Health Department Service Rules · Assembly Q&A',
  },
  {
    id: 'health-l4',
    dept_id: 'health',
    level: 4,
    designation_en: 'Block Medical Officer',
    designation_ta: 'வட்டார மருத்துவ அதிகாரி',
    cadre: 'state_service',
    recruitment_body: 'Tamil Nadu Medical Services Recruitment Board',
    pay_min: 56100,
    pay_max: 177500,
    sanctioned_posts: 385,
    filled_posts: 310,
    data_quality_staffing: 'estimated',
    citizen_facing: true,
    decision_powers_en: [
      'Supervise all PHCs in the block',
      'Approve local medicine procurement for emergencies',
      'Grant leave to PHC staff in block',
      'Recommend disciplinary action for block staff',
      'Coordinate 108 ambulance coverage',
    ],
    decision_limitations_en: [
      'Cannot hire any staff',
      'Cannot approve capital works',
      'Cannot override TNMSC medicine supply schedules',
      'Cannot permanently post staff to a specific PHC',
      'Cannot waive patient treatment fees (nominal)',
    ],
    for_citizen_problem_en: 'Contact for: specific PHC has no doctor for extended period, medicine shortage at block level. Block Medical Officer contact available at district health office.',
    transfer_authority: 'Joint Director of Health Services District',
    typical_tenure_months: 36,
    source: 'TN Health Department Manuals · RTI responses',
  },
  {
    id: 'health-l5',
    dept_id: 'health',
    level: 5,
    designation_en: 'Medical Officer — Primary Health Centre',
    designation_ta: 'PHC மருத்துவ அதிகாரி',
    cadre: 'state_service',
    recruitment_body: 'Tamil Nadu Medical Services Recruitment Board',
    pay_min: 56100,
    pay_max: 177500,
    sanctioned_posts: 1776,
    filled_posts: 1370,
    data_quality_staffing: 'estimated',
    citizen_facing: true,
    decision_powers_en: [
      'Provide OPD consultation and treatment',
      'Prescribe from essential medicines list',
      'Refer to secondary or tertiary facilities',
      'Conduct minor procedures within PHC capacity',
      'Issue medical certificates',
    ],
    decision_limitations_en: [
      'Cannot prescribe outside essential medicines list without referral',
      'Cannot admit patients (PHC is outpatient only)',
      'Cannot purchase medicines outside TNMSC supply',
      'Cannot employ any supporting staff',
      'Cannot issue fitness certificates for certain categories',
    ],
    for_citizen_problem_en: 'Your first point of contact for illness, basic treatment, referrals, immunisation, maternal care. PHC locations: tnhealth.tn.gov.in',
    transfer_authority: 'Block Medical Officer recommendation — Joint Director approval',
    typical_tenure_months: 36,
    source: 'TN Health Department Service Manual',
  },
  {
    id: 'health-l6',
    dept_id: 'health',
    level: 6,
    designation_en: 'Auxiliary Nurse Midwife / Health Worker',
    designation_ta: 'துணை செவிலி மருத்துவி / சுகாதார பணியாளர்',
    cadre: 'subordinate',
    recruitment_body: 'Tamil Nadu Medical Services Recruitment Board',
    pay_min: 19500,
    pay_max: 62000,
    sanctioned_posts: 8706,
    filled_posts: 7200,
    data_quality_staffing: 'estimated',
    citizen_facing: true,
    decision_powers_en: [
      'Conduct home visits for maternal and child health',
      'Administer scheduled vaccines',
      'Maintain village health records',
      'Identify and report disease outbreaks',
      'Assist Medical Officer in PHC procedures',
    ],
    decision_limitations_en: [
      'Cannot prescribe any medication',
      'Cannot diagnose illness',
      'Cannot admit or refer patients independently',
      'Cannot access TNMSC medicine stocks independently',
      'Cannot issue any official health certificates',
    ],
    for_citizen_problem_en: 'Your sub-centre level contact for immunisation, maternal health tracking, nutrition monitoring. Contact through village health nurse or sub-centre.',
    transfer_authority: 'Block Medical Officer',
    typical_tenure_months: 48,
    source: 'TN Health Department Sub-Centre Manual',
  },
  {
    id: 'health-l7',
    dept_id: 'health',
    level: 7,
    designation_en: 'Village Health Nurse',
    designation_ta: 'கிராம சுகாதார செவிலியர்',
    cadre: 'subordinate',
    recruitment_body: 'Tamil Nadu Medical Services Recruitment Board',
    pay_min: 19500,
    pay_max: 62000,
    sanctioned_posts: 12000,
    filled_posts: 10200,
    data_quality_staffing: 'estimated',
    citizen_facing: true,
    decision_powers_en: [
      'Home visits for birth tracking and immunisation',
      'Record vital events — births, deaths',
      'Distribute ORS, iron tablets per protocol',
      'Identify high-risk pregnancies for referral',
      'Community health education',
    ],
    decision_limitations_en: [
      'Cannot prescribe or dispense medicines',
      'Cannot conduct deliveries independently',
      'Cannot issue any official documents',
      'Cannot override Medical Officer decisions',
      'Cannot access hospital records',
    ],
    for_citizen_problem_en: 'Village-level contact for immunisation schedule, pregnancy monitoring, child nutrition. Know your Village Health Nurse — she visits your home.',
    transfer_authority: 'Block Medical Officer',
    typical_tenure_months: 60,
    source: 'TN Village Health Nurse Manual',
  },
]

// ── CONTRACT WORKERS ─────────────────────────────────────────────

export const HEALTH_CONTRACT_WORKERS: ContractWorkerCategory[] = [
  {
    id: 'health-cw-1',
    dept_id: 'health',
    role_en: 'Specialist doctors at district hospitals',
    role_ta: 'மாவட்ட மருத்துவமனைகளில் நிபுணர் மருத்துவர்கள்',
    count_approximate: 1200,
    pay_range_en: 'Rs 75,000 to Rs 1,50,000 per month (fixed-term contract)',
    vs_permanent_pay_en: 'Comparable to junior specialist scale but without annual increment or pension',
    job_security_en: 'Fixed-term contract, typically 1–2 years, renewable subject to performance review. Not covered by service protections applicable to permanent staff.',
    services_they_deliver_en: 'Specialist consultations in surgery, gynaecology, orthopaedics, anaesthesia at district hospitals. Citizens receiving specialist care at district hospitals may be attended by contract doctors.',
    source: 'TN Health Department GO Ms 142/2019 · Assembly Q&A 2023',
    data_quality: 'estimated',
  },
  {
    id: 'health-cw-2',
    dept_id: 'health',
    role_en: 'Lab technicians and paramedical staff',
    role_ta: 'ஆய்வக தொழில்நுட்பவியலாளர்கள் மற்றும் பாராமெடிக்கல் பணியாளர்கள்',
    count_approximate: 3500,
    pay_range_en: 'Rs 15,000 to Rs 25,000 per month',
    vs_permanent_pay_en: 'Approximately 40–60% of equivalent permanent post pay scale',
    job_security_en: 'Annual contract renewal. Employment terms differ from permanent staff. Not covered by service protections applicable to permanent staff.',
    services_they_deliver_en: 'Blood tests, X-rays, ECGs at PHC and district hospital level. Lab services for most OPD patients are delivered by contract technicians.',
    source: 'Assembly Q&A 2022 · NHM Tamil Nadu reports',
    data_quality: 'estimated',
  },
]

// ── LEGAL APPOINTMENTS ───────────────────────────────────────────

export const HEALTH_LEGAL_APPOINTMENTS: LegalAppointment[] = [
  {
    id: 'health-la-1',
    designation: 'Government Pleader — Health Department matters',
    appointment_basis: 'Appointed by Advocate General\'s office on recommendation of Law Department',
    appointing_authority: 'Government of Tamil Nadu — Law Department',
    tenure_en: 'Typically 3 years, renewable',
    fee_structure_en: 'Fee structure governed by Tamil Nadu Government Pleaders Rules — not publicly disclosed in detail. RTI needed for specific fee amounts.',
    cases_handled_en: 'Consumer disputes against government hospitals, PILs on health policy, employment disputes involving health department staff, CMCHIS reimbursement disputes.',
    source: 'TN Law Department records — partial. Full details require RTI.',
    data_quality: 'estimated',
    rti_note_en: 'To obtain complete fee structure and case list: file RTI with Public Information Officer, Law Department, Government of Tamil Nadu, Chennai 600 009.',
  },
]

// ── MINISTERS (Health) ────────────────────────────────────────────

export const HEALTH_MINISTERS: Minister[] = [
  {
    id: 'health-m-1',
    dept_id: 'health',
    name_en: 'C. Subramaniam',
    name_ta: 'சி. சுப்பிரமணியம்',
    party: 'INC',
    tenure_start: '1952-04-01',
    tenure_end: '1954-03-31',
    cm_name_en: 'C. Rajagopalachari',
    notable_policies_en: 'Early public health infrastructure development post-Independence.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-2',
    dept_id: 'health',
    name_en: 'V. R. Nedunchezhiyan',
    name_ta: 'வி. ஆர். நெடுஞ்செழியன்',
    party: 'DMK',
    tenure_start: '1967-03-06',
    tenure_end: '1971-01-15',
    cm_name_en: 'C. N. Annadurai / M. Karunanidhi',
    notable_policies_en: 'Expanded PHC network across rural Tamil Nadu.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-3',
    dept_id: 'health',
    name_en: 'P. U. Shanmugam',
    name_ta: 'பி. யு. சண்முகம்',
    party: 'DMK',
    tenure_start: '1971-03-15',
    tenure_end: '1976-01-31',
    cm_name_en: 'M. Karunanidhi',
    notable_policies_en: 'Rural health extension programmes.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-4',
    dept_id: 'health',
    name_en: 'S. Thirunavukkarasar',
    name_ta: 'எஸ். திருநாவுக்கரசர்',
    party: 'AIADMK',
    tenure_start: '1977-06-30',
    tenure_end: '1980-02-17',
    cm_name_en: 'M. G. Ramachandran',
    notable_policies_en: 'Initiated expansion of government hospital network.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-5',
    dept_id: 'health',
    name_en: 'P. H. Pandian',
    name_ta: 'பி. எச். பாண்டியன்',
    party: 'AIADMK',
    tenure_start: '1980-06-09',
    tenure_end: '1987-12-24',
    cm_name_en: 'M. G. Ramachandran',
    notable_policies_en: 'Expanded maternal and child health services; increased PHC staffing.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-6',
    dept_id: 'health',
    name_en: 'M. Tamilkudiyan',
    name_ta: 'எம். தமிழ்குடியான்',
    party: 'AIADMK',
    tenure_start: '1989-01-07',
    tenure_end: '1989-12-30',
    cm_name_en: 'Janaki Ramachandran / R. M. Veerappan (President\'s Rule)',
    notable_policies_en: '',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-7',
    dept_id: 'health',
    name_en: 'A. Ramamirtham',
    name_ta: 'ஏ. ராமாமிர்தம்',
    party: 'DMK',
    tenure_start: '1989-01-27',
    tenure_end: '1991-01-30',
    cm_name_en: 'M. Karunanidhi',
    notable_policies_en: 'Continued rural health expansion.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-8',
    dept_id: 'health',
    name_en: 'K. A. Krishnaswamy',
    name_ta: 'கே. ஏ. கிருஷ்ணசாமி',
    party: 'AIADMK',
    tenure_start: '1991-06-24',
    tenure_end: '1996-05-12',
    cm_name_en: 'J. Jayalalithaa',
    notable_policies_en: 'Early TNMSC medicine supply chain reforms.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: true,
  },
  {
    id: 'health-m-9',
    dept_id: 'health',
    name_en: 'Durai Murugan',
    name_ta: 'துரைமுருகன்',
    party: 'DMK',
    tenure_start: '1996-05-13',
    tenure_end: '2001-05-13',
    cm_name_en: 'M. Karunanidhi',
    notable_policies_en: 'Free medicine scheme expansion; telemedicine pilots.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: false,
  },
  {
    id: 'health-m-10',
    dept_id: 'health',
    name_en: 'K. C. Veeramani',
    name_ta: 'கே. சி. வீரமணி',
    party: 'AIADMK',
    tenure_start: '2001-05-14',
    tenure_end: '2006-05-11',
    cm_name_en: 'J. Jayalalithaa',
    notable_policies_en: 'CMCHIS predecessor scheme initiation; hospital upgrades.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: false,
  },
  {
    id: 'health-m-11',
    dept_id: 'health',
    name_en: 'M. R. K. Panneerselvam',
    name_ta: 'எம். ஆர். கே. பண்ணீர்செல்வம்',
    party: 'DMK',
    tenure_start: '2006-05-13',
    tenure_end: '2011-05-15',
    cm_name_en: 'M. Karunanidhi',
    notable_policies_en: 'National Health Mission implementation; 108 ambulance launch in TN.',
    source: 'TN Assembly records / Gazette',
    dates_approximate: false,
  },
  {
    id: 'health-m-12',
    dept_id: 'health',
    name_en: 'V. S. Vijayabaskar',
    name_ta: 'வி. எஸ். விஜயபாஸ்கர்',
    party: 'AIADMK',
    tenure_start: '2011-05-16',
    tenure_end: '2021-05-07',
    cm_name_en: 'J. Jayalalithaa / E. K. Palaniswami',
    notable_policies_en: 'CMCHIS expansion to ₹5 lakh coverage; COVID-19 response 2020–21.',
    source: 'TN Assembly records / tn.gov.in',
    dates_approximate: false,
  },
  {
    id: 'health-m-13',
    dept_id: 'health',
    name_en: 'Ma. Subramanian',
    name_ta: 'மா. சுப்பிரமணியன்',
    party: 'DMK',
    tenure_start: '2021-05-07',
    tenure_end: 'present',
    cm_name_en: 'M. K. Stalin',
    notable_policies_en: 'Makkalai Thedi Maruthuvam launch; CMCHIS continuation; free medicine list expansion.',
    source: 'TN Assembly records / tn.gov.in',
    dates_approximate: false,
  },
]

// ── TENDER SIGNALS (Health) ───────────────────────────────────────

export const HEALTH_TENDER_SIGNALS = [] as const
