import type { LocalBody } from '@/types'

// All 21 municipal corporations of Tamil Nadu (as constituted post-2022 mergers)
export const TN_CORPORATIONS: LocalBody[] = [
  {
    id: 'corp-chennai',
    type: 'corporation',
    name_en: 'Greater Chennai Corporation',
    name_ta: 'சென்னை மாநகராட்சி',
    district: 'Chennai',
    population: 7088000,
    budget_cr: 6820,
    budget_year: '2023-24',
    key_functions_en: ['Roads & drains', 'Solid waste', 'Birth & death registration', 'Building plans', 'Markets', 'Street lights'],
    schemes_implemented: ['PM SVANidhi', 'Smart City Mission', 'AMRUT 2.0', 'Tamil Nadu Urban Flagship'],
    elected_members: 200,
    permanent_staff: 14200,
    contract_staff: 3800,
    website_url: 'https://chennaicorporation.gov.in',
    source_url: 'https://chennaicorporation.gov.in/gcc/annual-report',
    data_quality: 'available',
  },
  {
    id: 'corp-coimbatore',
    type: 'corporation',
    name_en: 'Coimbatore City Municipal Corporation',
    name_ta: 'கோயம்புத்தூர் மாநகராட்சி',
    district: 'Coimbatore',
    population: 1061000,
    budget_cr: 1240,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Waste management', 'Sanitation', 'Parks'],
    schemes_implemented: ['AMRUT 2.0', 'Smart City Mission', 'TNUFIP'],
    elected_members: 100,
    permanent_staff: 4800,
    contract_staff: 1200,
    website_url: 'https://www.ccmc.gov.in',
    source_url: 'https://www.ccmc.gov.in',
    data_quality: 'available',
  },
  {
    id: 'corp-madurai',
    type: 'corporation',
    name_en: 'Madurai City Municipal Corporation',
    name_ta: 'மதுரை மாநகராட்சி',
    district: 'Madurai',
    population: 1017000,
    budget_cr: 980,
    budget_year: '2023-24',
    key_functions_en: ['Water supply', 'Roads', 'Waste', 'Sanitation', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 100,
    permanent_staff: 3900,
    contract_staff: 900,
    website_url: 'https://maduraicorporation.com',
    source_url: 'https://maduraicorporation.com',
    data_quality: 'available',
  },
  {
    id: 'corp-trichy',
    type: 'corporation',
    name_en: 'Tiruchirappalli City Municipal Corporation',
    name_ta: 'திருச்சிராப்பள்ளி மாநகராட்சி',
    district: 'Tiruchirappalli',
    population: 916857,
    budget_cr: 860,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Solid waste', 'Sanitation', 'Burial grounds'],
    schemes_implemented: ['AMRUT 2.0', 'Smart City Mission', 'TNUFIP'],
    elected_members: 65,
    permanent_staff: 3400,
    contract_staff: 700,
    website_url: 'https://www.corporationoftrichy.in',
    source_url: 'https://www.corporationoftrichy.in',
    data_quality: 'available',
  },
  {
    id: 'corp-salem',
    type: 'corporation',
    name_en: 'Salem City Municipal Corporation',
    name_ta: 'சேலம் மாநகராட்சி',
    district: 'Salem',
    population: 831038,
    budget_cr: 720,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Drainage', 'Waste management', 'Street lights', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 60,
    permanent_staff: 2800,
    contract_staff: 600,
    website_url: 'https://www.salemmunicipalcorporation.com',
    source_url: 'https://www.salemmunicipalcorporation.com',
    data_quality: 'estimated',
  },
  {
    id: 'corp-tirunelveli',
    type: 'corporation',
    name_en: 'Tirunelveli City Municipal Corporation',
    name_ta: 'திருநெல்வேலி மாநகராட்சி',
    district: 'Tirunelveli',
    population: 474838,
    budget_cr: 520,
    budget_year: '2023-24',
    key_functions_en: ['Water supply', 'Solid waste', 'Roads', 'Sanitation', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 55,
    permanent_staff: 2200,
    contract_staff: 500,
    website_url: 'https://tirunelvelicorporation.tn.gov.in',
    source_url: 'https://tirunelvelicorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-tiruppur',
    type: 'corporation',
    name_en: 'Tiruppur City Municipal Corporation',
    name_ta: 'திருப்பூர் மாநகராட்சி',
    district: 'Tiruppur',
    population: 877778,
    budget_cr: 680,
    budget_year: '2023-24',
    key_functions_en: ['Water supply', 'Sewerage', 'Solid waste', 'Roads', 'Street lights'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 60,
    permanent_staff: 2600,
    contract_staff: 550,
    website_url: 'https://tiruppur.tn.gov.in',
    source_url: 'https://tiruppur.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-vellore',
    type: 'corporation',
    name_en: 'Vellore City Municipal Corporation',
    name_ta: 'வேலூர் மாநகராட்சி',
    district: 'Vellore',
    population: 423425,
    budget_cr: 410,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Sanitation', 'Markets', 'Solid waste'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 52,
    permanent_staff: 1900,
    contract_staff: 400,
    website_url: 'https://vellorecorporation.tn.gov.in',
    source_url: 'https://vellorecorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-thoothukudi',
    type: 'corporation',
    name_en: 'Thoothukudi City Municipal Corporation',
    name_ta: 'தூத்துக்குடி மாநகராட்சி',
    district: 'Thoothukudi',
    population: 237229,
    budget_cr: 340,
    budget_year: '2023-24',
    key_functions_en: ['Port-city services', 'Water supply', 'Solid waste', 'Roads', 'Sanitation'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 48,
    permanent_staff: 1600,
    contract_staff: 350,
    website_url: 'https://thoothukudi.tn.gov.in',
    source_url: 'https://thoothukudi.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-erode',
    type: 'corporation',
    name_en: 'Erode City Municipal Corporation',
    name_ta: 'ஈரோடு மாநகராட்சி',
    district: 'Erode',
    population: 214174,
    budget_cr: 360,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Solid waste', 'Street lights', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 48,
    permanent_staff: 1700,
    contract_staff: 360,
    website_url: 'https://erodecorporation.tn.gov.in',
    source_url: 'https://erodecorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-thanjavur',
    type: 'corporation',
    name_en: 'Thanjavur City Municipal Corporation',
    name_ta: 'தஞ்சாவூர் மாநகராட்சி',
    district: 'Thanjavur',
    population: 222943,
    budget_cr: 290,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Solid waste', 'Heritage area maintenance', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP', 'HRIDAY (heritage)'],
    elected_members: 48,
    permanent_staff: 1500,
    contract_staff: 300,
    website_url: 'https://thanjavurcorporation.tn.gov.in',
    source_url: 'https://thanjavurcorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-dindigul',
    type: 'corporation',
    name_en: 'Dindigul City Municipal Corporation',
    name_ta: 'திண்டுக்கல் மாநகராட்சி',
    district: 'Dindigul',
    population: 207327,
    budget_cr: 260,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Solid waste', 'Markets', 'Sanitation'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 48,
    permanent_staff: 1400,
    contract_staff: 280,
    website_url: 'https://dindigulcorporation.tn.gov.in',
    source_url: 'https://dindigulcorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-nagercoil',
    type: 'corporation',
    name_en: 'Nagercoil City Municipal Corporation',
    name_ta: 'நாகர்கோவில் மாநகராட்சி',
    district: 'Kanyakumari',
    population: 275097,
    budget_cr: 310,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Solid waste', 'Sanitation', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 48,
    permanent_staff: 1450,
    contract_staff: 300,
    website_url: 'https://nagercoilcorporation.tn.gov.in',
    source_url: 'https://nagercoilcorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-kumbakonam',
    type: 'corporation',
    name_en: 'Kumbakonam City Municipal Corporation',
    name_ta: 'கும்பகோணம் மாநகராட்சி',
    district: 'Thanjavur',
    population: 140156,
    budget_cr: 220,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Temple-city services', 'Water supply', 'Solid waste', 'Sanitation'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP', 'HRIDAY (heritage)'],
    elected_members: 36,
    permanent_staff: 1100,
    contract_staff: 220,
    website_url: 'https://kumbakonamcorporation.tn.gov.in',
    source_url: 'https://kumbakonamcorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-hosur',
    type: 'corporation',
    name_en: 'Hosur City Municipal Corporation',
    name_ta: 'ஓசூர் மாநகராட்சி',
    district: 'Krishnagiri',
    population: 280684,
    budget_cr: 380,
    budget_year: '2023-24',
    key_functions_en: ['Industrial-area roads', 'Water supply', 'Solid waste', 'Sanitation', 'Street lights'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP', 'Industrial growth corridor support'],
    elected_members: 48,
    permanent_staff: 1500,
    contract_staff: 320,
    website_url: 'https://hosurmunicorporation.tn.gov.in',
    source_url: 'https://hosurmunicorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-kancheepuram',
    type: 'corporation',
    name_en: 'Kancheepuram City Municipal Corporation',
    name_ta: 'காஞ்சிபுரம் மாநகராட்சி',
    district: 'Kancheepuram',
    population: 164384,
    budget_cr: 240,
    budget_year: '2023-24',
    key_functions_en: ['Temple-city services', 'Roads', 'Water supply', 'Solid waste', 'Heritage maintenance'],
    schemes_implemented: ['AMRUT 2.0', 'HRIDAY (heritage)', 'TNUFIP'],
    elected_members: 40,
    permanent_staff: 1200,
    contract_staff: 240,
    website_url: 'https://kancheepuramcorporation.tn.gov.in',
    source_url: 'https://kancheepuramcorporation.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-cuddalore',
    type: 'corporation',
    name_en: 'Cuddalore City Municipal Corporation',
    name_ta: 'கடலூர் மாநகராட்சி',
    district: 'Cuddalore',
    population: 173676,
    budget_cr: 230,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Coastal waste management', 'Sanitation', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP', 'Industrial corridor (SIPCOT proximity)'],
    elected_members: 40,
    permanent_staff: 1150,
    contract_staff: 230,
    website_url: 'https://cuddaloremu.tn.gov.in',
    source_url: 'https://cuddaloremu.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-sivakasi',
    type: 'corporation',
    name_en: 'Sivakasi City Municipal Corporation',
    name_ta: 'சிவகாசி மாநகராட்சி',
    district: 'Virudhunagar',
    population: 72001,
    budget_cr: 170,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Industrial-area sanitation', 'Solid waste', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 36,
    permanent_staff: 900,
    contract_staff: 180,
    website_url: 'https://sivakasimu.tn.gov.in',
    source_url: 'https://sivakasimu.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-karur',
    type: 'corporation',
    name_en: 'Karur City Municipal Corporation',
    name_ta: 'கரூர் மாநகராட்சி',
    district: 'Karur',
    population: 104000,
    budget_cr: 195,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Textile-hub services', 'Solid waste', 'Sanitation'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 40,
    permanent_staff: 1000,
    contract_staff: 200,
    website_url: 'https://karurmu.tn.gov.in',
    source_url: 'https://karurmu.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-ambur',
    type: 'corporation',
    name_en: 'Ambur City Municipal Corporation',
    name_ta: 'ஆம்பூர் மாநகராட்சி',
    district: 'Tirupattur',
    population: 134000,
    budget_cr: 185,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Leather-industry area services', 'Water supply', 'Solid waste', 'Sanitation'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP'],
    elected_members: 36,
    permanent_staff: 950,
    contract_staff: 190,
    website_url: 'https://amburmu.tn.gov.in',
    source_url: 'https://amburmu.tn.gov.in',
    data_quality: 'estimated',
  },
  {
    id: 'corp-ranipet',
    type: 'corporation',
    name_en: 'Ranipet City Municipal Corporation',
    name_ta: 'ராணிப்பேட்டை மாநகராட்சி',
    district: 'Ranipet',
    population: 115000,
    budget_cr: 175,
    budget_year: '2023-24',
    key_functions_en: ['Roads', 'Water supply', 'Industrial-area sanitation', 'Solid waste', 'Markets'],
    schemes_implemented: ['AMRUT 2.0', 'TNUFIP', 'TIDCO industrial zone support'],
    elected_members: 36,
    permanent_staff: 900,
    contract_staff: 180,
    website_url: 'https://ranipetmu.tn.gov.in',
    source_url: 'https://ranipetmu.tn.gov.in',
    data_quality: 'estimated',
  },
]

export const CORP_SUMMARY = {
  total: TN_CORPORATIONS.length,
  totalBudgetCr: TN_CORPORATIONS.reduce((a, b) => a + (b.budget_cr ?? 0), 0),
  totalElected: TN_CORPORATIONS.reduce((a, b) => a + (b.elected_members ?? 0), 0),
  totalStaff: TN_CORPORATIONS.reduce((a, b) => a + (b.permanent_staff ?? 0) + (b.contract_staff ?? 0), 0),
}
