import { Scheme, SchemeType } from '@/types'

export const ALL_SCHEMES: Scheme[] = [
  // WELFARE
  {
    id: 'magalir-urimai',
    name_en: 'Kalaignar Magalir Urimai Thittam',
    name_ta: 'கலைஞர் மகளிர் உரிமைத் திட்டம்',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2023,
    origin_party: 'DMK',
    beneficiaries_claimed: '1.15 crore women',
    eligibility_en: 'Women aged 21 and above who are head of household. Excludes government employees, income tax payers. ₹1,000 per month direct to bank account.',
    eligibility_ta: '21 வயதுக்கு மேல் உள்ள குடும்பத் தலைவி பெண்கள். அரசு ஊழியர்கள் மற்றும் வருமான வரி செலுத்துவோர் விலக்கு.',
    how_to_apply_en: 'Apply at nearest ration shop or e-Sevai centre with Aadhaar, bank passbook, and ration card. Application is free.',
    source_url: 'https://magalir.tn.gov.in',
  },
  {
    id: 'samathuvapuram',
    name_en: 'Samathuvapuram Housing Scheme',
    name_ta: 'சமத்துவபுரம் வீட்டு திட்டம்',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1999,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1.5 lakh families housed',
    eligibility_en: 'BPL families including SC/ST, minorities, women-headed households — integrated housing in mixed communities.',
    eligibility_ta: 'BPL குடும்பங்கள் — SC/ST, சிறுபான்மையினர், பெண் தலைவியர் — கலப்பு சமூக வீட்டு வசதி.',
    how_to_apply_en: 'Apply at your Collectorate or Block Development Officer. Allotment through lottery among eligible applicants.',
    source_url: 'https://tnscb.tn.gov.in',
  },
  // HEALTH
  {
    id: 'cmchis',
    name_en: 'Chief Minister Comprehensive Health Insurance Scheme (CMCHIS)',
    name_ta: 'முதலமைச்சரின் விரிவான சுகாதார காப்பீட்டுத் திட்டம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2012,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1.75 crore families',
    eligibility_en: 'BPL families and those earning below ₹72,000 per year. Annual health cover of ₹5 lakh per family for 1,027 procedures.',
    eligibility_ta: 'BPL குடும்பங்கள் மற்றும் ஆண்டு வருமானம் ₹72,000-க்கு கீழ் உள்ளவர்கள். 1,027 சிகிச்சைகளுக்கு ₹5 லட்சம் வரை.',
    how_to_apply_en: 'Register at nearest government hospital with Aadhaar, income certificate, and ration card. No premium payment required.',
    source_url: 'https://www.cmchistn.com',
  },
  {
    id: 'pmjay',
    name_en: 'Ayushman Bharat PM-JAY',
    name_ta: 'ஆயுஷ்மான் பாரத் PM-JAY',
    dept_id: 'health',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2018,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: 'Merged with CMCHIS in TN',
    eligibility_en: 'Bottom 40% households by income (SECC list). In TN, operationally merged with CMCHIS — use CMCHIS card.',
    eligibility_ta: 'கீழ் 40% வருமான குடும்பங்கள். TN-ல் CMCHIS-உடன் இணைக்கப்பட்டது.',
    how_to_apply_en: 'In Tamil Nadu, apply through CMCHIS at nearest ration shop. CMCHIS card is valid for PM-JAY benefits.',
    source_url: 'https://pmjay.gov.in',
    parent_scheme_en: 'Replaced RSBY (Rashtriya Swasthya Bima Yojana)',
  },
  {
    id: 'jsy',
    name_en: 'Janani Suraksha Yojana (JSY)',
    name_ta: 'ஜனனி சுரட்சா யோஜனா',
    dept_id: 'health',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2005,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '5 lakh deliveries per year',
    eligibility_en: 'All pregnant women delivering in government hospitals. ₹1,000 cash for institutional delivery in TN.',
    eligibility_ta: 'அரசு மருத்துவமனையில் பிரசவிக்கும் அனைத்து கர்ப்பிணி பெண்கள். ₹1,000 பணம்.',
    how_to_apply_en: 'Register at nearest PHC or govt hospital during antenatal check-up. ASHA worker will assist with paperwork.',
    source_url: 'https://nhm.gov.in',
  },
  // EDUCATION
  {
    id: 'puthumai-penn',
    name_en: 'Puthumai Penn Scheme',
    name_ta: 'புதுமைப் பெண் திட்டம்',
    dept_id: 'education',
    scheme_type: 'state',
    status: 'extended',
    funding_ratio_en: '100% State funded',
    origin_year: 2022,
    origin_party: 'DMK',
    beneficiaries_claimed: '5.4 lakh girl students per year',
    eligibility_en: 'Girls studying in government and government-aided schools. ₹1,000 per month from Class 6 to 12. Extended from govt-only to include aided schools in 2023.',
    eligibility_ta: 'அரசு மற்றும் அரசு உதவி பெறும் பள்ளிகளில் படிக்கும் மாணவிகள். 6 முதல் 12-ம் வகுப்பு வரை மாதம் ₹1,000.',
    how_to_apply_en: 'Apply through school principal. Benefits credited directly to student bank account.',
    source_url: 'https://www.tnschools.gov.in',
    parent_scheme_en: 'Same scheme — extended to aided schools in 2023',
  },
  {
    id: 'tamizh-pudhalvan',
    name_en: 'Tamizh Pudhalvan Scheme',
    name_ta: 'தமிழ் புதல்வன் திட்டம்',
    dept_id: 'education',
    scheme_type: 'state',
    status: 'new',
    funding_ratio_en: '100% State funded',
    origin_year: 2024,
    origin_party: 'DMK',
    beneficiaries_claimed: '4.2 lakh boy students',
    eligibility_en: 'Boys in government schools from Class 6 to 12. ₹1,000 per month to match Puthumai Penn parity.',
    eligibility_ta: 'அரசு பள்ளிகளில் படிக்கும் ஆண் மாணவர்கள். 6 முதல் 12-ம் வகுப்பு வரை மாதம் ₹1,000.',
    how_to_apply_en: 'Apply through school principal. Launched January 2024.',
    source_url: 'https://www.tnschools.gov.in',
  },
  {
    id: 'pm-poshan',
    name_en: 'PM POSHAN (Mid-Day Meal Scheme)',
    name_ta: 'PM போஷண் (மதிய உணவு திட்டம்)',
    dept_id: 'education',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 1995,
    origin_party: 'Central (renamed 2021)',
    beneficiaries_claimed: '66 lakh students daily',
    eligibility_en: 'All students in government and government-aided schools from Class 1 to 8. Free cooked meal every school day.',
    eligibility_ta: 'அரசு பள்ளிகளில் 1 முதல் 8-ம் வகுப்பு மாணவர்களுக்கு தினமும் இலவச சத்தான மதிய உணவு.',
    how_to_apply_en: 'No application needed. Automatic for all enrolled students in eligible schools.',
    source_url: 'https://pmposhan.education.gov.in',
    parent_scheme_en: 'Renamed from Mid-Day Meal Scheme in 2021',
  },
  {
    id: 'samagra-shiksha',
    name_en: 'Samagra Shiksha Abhiyan',
    name_ta: 'சமக்ர சிக்ஷா அபியான்',
    dept_id: 'education',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2018,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: 'All govt school students',
    eligibility_en: 'All students in government schools — covers infrastructure, teacher training, digital equipment, and textbooks.',
    eligibility_ta: 'அனைத்து அரசு பள்ளி மாணவர்கள் — கட்டமைப்பு, ஆசிரியர் பயிற்சி, டிஜிட்டல் கருவிகள்.',
    how_to_apply_en: 'No application — delivered through schools automatically.',
    source_url: 'https://samagrashiksha.in',
    parent_scheme_en: 'Merged SSA, RMSA, and TE schemes in 2018',
  },
  // REVENUE
  {
    id: 'pmay-gramin',
    name_en: 'PM Awas Yojana Gramin (PMAY-G)',
    name_ta: 'PM ஆவாஸ் யோஜனா கிராமின்',
    dept_id: 'revenue',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2016,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '8 lakh houses sanctioned in TN',
    eligibility_en: 'Homeless or inadequately housed families in rural areas — BPL, SC/ST, widows, differently-abled. ₹1.2 lakh per unit in plains, ₹1.3 lakh in hilly areas.',
    eligibility_ta: 'கிராமப்புறங்களில் வீடற்ற அல்லது பழுதடைந்த வீடுடைய குடும்பங்கள். ₹1.2 லட்சம் மானியம்.',
    how_to_apply_en: 'Apply through Block Development Office or Gram Panchayat. Beneficiaries selected from Socio-Economic Caste Census (SECC) list.',
    source_url: 'https://pmayg.nic.in',
  },
  // AGRICULTURE
  {
    id: 'pm-kisan',
    name_en: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    name_ta: 'PM-கிசான் (பிரதம மந்திரி கிசான் சம்மான் நிதி)',
    dept_id: 'agriculture',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2019,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '42 lakh farmers in TN',
    eligibility_en: 'All landholder farmer families with cultivable land. ₹6,000 per year in 3 instalments of ₹2,000 direct to bank account.',
    eligibility_ta: 'விவசாய நில உரிமையாளர் குடும்பங்கள். ஆண்டுக்கு ₹6,000 மூன்று தவணைகளில்.',
    how_to_apply_en: 'Register at nearest Common Service Centre or pmkisan.gov.in. Aadhaar, land record, and bank details required.',
    source_url: 'https://pmkisan.gov.in',
  },
  {
    id: 'pmfby',
    name_en: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    name_ta: 'பிரதம மந்திரி ஃபாஸல் பீமா யோஜனா',
    dept_id: 'agriculture',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State',
    origin_year: 2016,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '28 lakh farmers insured in TN',
    eligibility_en: 'All farmers growing notified crops. Premium: 2% for kharif, 1.5% for rabi, 5% for horticulture crops. Government pays the rest.',
    eligibility_ta: 'அனைத்து விவசாயிகள். பயிர் காப்பீட்டுக்கு 2% பிரீமியம் மட்டும் செலுத்தினால் போதும்.',
    how_to_apply_en: 'Apply through nearest bank, cooperative, or Common Service Centre before the crop season deadline. Aadhaar, land record required.',
    source_url: 'https://pmfby.gov.in',
  },
  // TRANSPORT
  {
    id: 'free-bus-women',
    name_en: 'Free Bus Pass for Women',
    name_ta: 'பெண்களுக்கு இலவச பேருந்து பாஸ்',
    dept_id: 'transport',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '1.5 crore women daily',
    eligibility_en: 'All women in Tamil Nadu — free travel on all TNSTC, MTC, and SETC buses. No income restriction.',
    eligibility_ta: 'தமிழ்நாட்டில் உள்ள அனைத்து பெண்களுக்கும் — TNSTC, MTC, SETC பேருந்துகளில் இலவச பயணம்.',
    how_to_apply_en: 'No application needed. Board any government bus and show identity if asked.',
    source_url: 'https://tnstc.in',
  },
  // ENERGY
  {
    id: 'free-100-units',
    name_en: 'Free 100 Units Electricity Scheme',
    name_ta: '100 இலவச மின் யூனிட் திட்டம்',
    dept_id: 'energy',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '2.8 crore domestic consumers',
    eligibility_en: 'All domestic electricity consumers using up to 100 units per month. No application — applied automatically on monthly bill.',
    eligibility_ta: 'மாதம் 100 யூனிட் வரை பயன்படுத்தும் வீட்டு நுகர்வோர். தானாகவே பில்லில் கழிக்கப்படும்.',
    how_to_apply_en: 'No application needed. Free units automatically applied to domestic consumer bills each month.',
    source_url: 'https://www.tangedco.gov.in',
  },
  // MUNICIPAL
  {
    id: 'amrut-2',
    name_en: 'AMRUT 2.0 (Atal Mission for Rejuvenation & Urban Transformation)',
    name_ta: 'AMRUT 2.0',
    dept_id: 'municipal',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State',
    origin_year: 2021,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '3.8 crore urban citizens',
    eligibility_en: 'All urban citizens in cities with population over 1 lakh — water supply, sewerage, and urban green spaces.',
    eligibility_ta: '1 லட்சம் மக்கள்தொகை மேற்பட்ட நகரங்களில் நீர் விநியோகம், கழிவுநீர் மற்றும் பூங்காக்கள்.',
    how_to_apply_en: 'No direct application — benefits delivered through urban local bodies. Contact your municipality for connections.',
    source_url: 'https://amrut.gov.in',
  },
  // PWD
  {
    id: 'pmgsy',
    name_en: 'PMGSY — Pradhan Mantri Gram Sadak Yojana',
    name_ta: 'PM கிராம் சாலை யோஜனா',
    dept_id: 'pwd',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2000,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '12,000+ villages connected in TN',
    eligibility_en: 'All-weather road connectivity to habitations with population over 250. Over 12,000 villages connected in Tamil Nadu.',
    eligibility_ta: '250-க்கும் மேற்பட்ட மக்கள்தொகை உள்ள கிராமங்களுக்கு சர்வகால சாலை வசதி.',
    how_to_apply_en: 'Villages apply through Block Office. Connectivity priority set by state government based on population and connectivity gap.',
    source_url: 'https://pmgsy.nic.in',
  },
  // WELFARE - additional
  {
    id: 'widow-pension',
    name_en: 'Widow Pension Scheme',
    name_ta: 'விதவை ஓய்வூதியம்',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1962,
    origin_party: 'State scheme',
    beneficiaries_claimed: '16 lakh widows',
    eligibility_en: 'Widows below poverty line, not receiving any other pension, aged 18 and above. ₹1,000 per month.',
    eligibility_ta: 'வறுமைக் கோட்டிற்கு கீழ் உள்ள விதவைகள், வேறு ஓய்வூதியம் இல்லாதவர்கள். மாதம் ₹1,000.',
    how_to_apply_en: 'Apply at nearest Block Development Office with death certificate, Aadhaar, and income certificate.',
    source_url: 'https://tnswdept.tn.gov.in',
  },
  // AGRICULTURE - additional
  {
    id: 'crop-loan-waiver',
    name_en: 'Farm Loan Waiver Scheme',
    name_ta: 'விவசாய கடன் தள்ளுபடி திட்டம்',
    dept_id: 'agriculture',
    scheme_type: 'state',
    status: 'extended',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '16.4 lakh farmers',
    eligibility_en: 'Farmers with crop loans up to ₹1 lakh from cooperative banks waived. Phased payment to banks by state government.',
    eligibility_ta: 'கூட்டுறவு வங்கிகளில் ₹1 லட்சம் வரை கடன் உள்ள விவசாயிகள். அரசு படிப்படியாக வங்கிகளுக்கு செலுத்தும்.',
    how_to_apply_en: 'No separate application — farmers with eligible cooperative bank loans automatically included. Check with your bank.',
    source_url: 'https://www.tn.gov.in/agriculture',
  },

  // WELFARE - extended
  {
    id: 'old-age-pension',
    name_en: 'Old Age Pension (Indira Gandhi National Old Age Pension)',
    name_ta: 'முதியோர் ஓய்வூதியம் (IGNOAPS)',
    dept_id: 'welfare',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '75% Central / 25% State',
    origin_year: 1995,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '22 lakh senior citizens',
    eligibility_en: 'BPL citizens aged 60 and above. ₹400/month (₹500 for 80+). State adds ₹600 top-up making it ₹1,000/month.',
    eligibility_ta: 'வறுமைக்கோட்டிற்கு கீழ் 60 வயதுக்கு மேற்பட்ட குடிமக்கள். மாதம் ₹1,000 (மாநில கூடுதல் நிதியுடன்).',
    how_to_apply_en: 'Apply at Block Development Office with Aadhaar, age proof, income certificate, and bank details.',
    source_url: 'https://tnswdept.tn.gov.in',
  },
  {
    id: 'differently-abled-pension',
    name_en: 'Differently Abled Persons Monthly Assistance',
    name_ta: 'மாற்றுத்திறனாளிகள் மாத உதவித்தொகை',
    dept_id: 'differently-abled',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1989,
    origin_party: 'State scheme',
    beneficiaries_claimed: '8 lakh differently abled persons',
    eligibility_en: 'Persons with 40%+ disability, BPL, not employed in government service. ₹1,500/month. Higher assistance for severe disabilities.',
    eligibility_ta: '40% மேல் ஊனம் உள்ள, வறுமைக்கோட்டிற்கு கீழ் உள்ள மாற்றுத்திறனாளிகள். மாதம் ₹1,500.',
    how_to_apply_en: 'Apply with disability certificate (from government hospital), Aadhaar, income certificate at nearest Block Office.',
    source_url: 'https://tnswdept.tn.gov.in',
  },
  {
    id: 'adip-scheme',
    name_en: 'ADIP — Assistance to Disabled Persons for Aids and Appliances',
    name_ta: 'ADIP — மாற்றுத்திறனாளிகளுக்கு உதவிக்கருவிகள்',
    dept_id: 'differently-abled',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '75% Central / 25% State',
    origin_year: 1981,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '2 lakh per year in TN',
    eligibility_en: 'BPL persons with 40%+ disability — free tricycles, hearing aids, calipers, prostheses, white canes, and wheelchairs.',
    eligibility_ta: 'வறுமைக்கோட்டிற்கு கீழ் 40% மேல் ஊனம் உள்ளவர்களுக்கு — திரிசக்கர வண்டி, காது கேட்கும் கருவி, செயற்கை கை/கால்.',
    how_to_apply_en: 'Apply through District Differently Abled Welfare Officer with disability certificate and income proof.',
    source_url: 'https://disabilityaffairs.gov.in',
  },
  {
    id: 'anganwadi-nutrition',
    name_en: 'Anganwadi Nutrition Supplementation (ICDS)',
    name_ta: 'அங்கன்வாடி ஊட்டச்சத்து திட்டம் (ICDS)',
    dept_id: 'welfare',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 1975,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '55 lakh children & 15 lakh mothers',
    eligibility_en: 'Children aged 0–6 and pregnant/lactating mothers — free nutrition, growth monitoring, immunisation, pre-school education at 56,000 anganwadi centres.',
    eligibility_ta: '0–6 வயது குழந்தைகள் மற்றும் கர்ப்பிணி/பாலூட்டும் தாய்மார்கள் — 56,000 அங்கன்வாடிகளில் இலவச ஊட்டச்சத்து.',
    how_to_apply_en: 'Register at nearest anganwadi centre. No formal application — workers actively enrol beneficiaries.',
    source_url: 'https://wcd.nic.in',
  },
  {
    id: 'chief-minister-breakfast',
    name_en: 'Chief Minister Breakfast Scheme',
    name_ta: 'முதலமைச்சர் காலை உணவு திட்டம்',
    dept_id: 'education',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2022,
    origin_party: 'DMK',
    beneficiaries_claimed: '18 lakh students (Classes 1–5)',
    eligibility_en: 'All students in Classes 1–5 in government schools — free nutritious breakfast every school day. Covers 31,266 schools.',
    eligibility_ta: 'அரசு பள்ளிகளில் 1 முதல் 5-ம் வகுப்பு மாணவர்களுக்கு தினமும் இலவச காலை உணவு. 31,266 பள்ளிகளில்.',
    how_to_apply_en: 'No application needed. Automatic for all enrolled government school students in Classes 1–5.',
    source_url: 'https://tnschools.gov.in',
  },
  {
    id: 'cm-breakfast-anganwadi',
    name_en: 'Anganwadi Breakfast — CM Scheme Extension',
    name_ta: 'அங்கன்வாடி காலை உணவு — CM திட்ட நீட்டிப்பு',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'new',
    funding_ratio_en: '100% State funded',
    origin_year: 2023,
    origin_party: 'DMK',
    beneficiaries_claimed: '9 lakh children in anganwadis',
    eligibility_en: 'Children aged 3–5 in government anganwadi centres — free nutritious breakfast extended from school to anganwadi.',
    eligibility_ta: 'அரசு அங்கன்வாடிகளில் 3–5 வயது குழந்தைகளுக்கு இலவச காலை உணவு.',
    how_to_apply_en: 'No application needed. Enrol child at nearest anganwadi centre.',
    source_url: 'https://tnswdept.tn.gov.in',
  },
  {
    id: 'destitute-widow-assistance',
    name_en: 'Destitute Widow Assistance',
    name_ta: 'ஆதரவற்ற விதவை உதவி',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1974,
    origin_party: 'State scheme',
    beneficiaries_claimed: '5 lakh destitute widows',
    eligibility_en: 'Destitute widows without any income source or family support, aged 18 and above. ₹1,000/month plus ration card.',
    eligibility_ta: 'எந்த வருமான ஆதாரமோ குடும்ப ஆதரவோ இல்லாத ஆதரவற்ற விதவைகள். மாதம் ₹1,000.',
    how_to_apply_en: 'Apply through Block Development Office with death certificate, income certificate, and social enquiry report.',
    source_url: 'https://tnswdept.tn.gov.in',
  },
  {
    id: 'tamilnadu-ration',
    name_en: 'Tamil Nadu PDS — Public Distribution System',
    name_ta: 'தமிழ்நாடு பொது விநியோக முறை',
    dept_id: 'cooperation',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '95% Central food subsidy / 5% State',
    origin_year: 1947,
    origin_party: 'State scheme',
    beneficiaries_claimed: '2.06 crore families',
    eligibility_en: 'BPL and AAY families — 5 kg free rice per person per month (NFSA). TN provides additional items: pulses, edible oil, sugar at subsidised rates.',
    eligibility_ta: 'BPL மற்றும் AAY குடும்பங்கள் — ஒருவருக்கு மாதம் 5 கிலோ இலவச அரிசி. TN கூடுதலாக பருப்பு, எண்ணெய், சர்க்கரை.',
    how_to_apply_en: 'Apply for ration card at e-Sevai centre with Aadhaar, family photos, and income proof. Annual income below ₹2 lakh.',
    source_url: 'https://www.tnpds.gov.in',
  },
  {
    id: 'tncsc-procurement',
    name_en: 'TNCSC Paddy Procurement (MSP)',
    name_ta: 'TNCSC நெல் கொள்முதல் (குறைந்தபட்ச ஆதார விலை)',
    dept_id: 'cooperation',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '100% Central MSP, State logistics',
    origin_year: 1958,
    origin_party: 'Central/State',
    beneficiaries_claimed: '10 lakh paddy farmers in TN',
    eligibility_en: 'All paddy farmers in TN. TNCSC procures at MSP (₹2,183/quintal for common variety 2023-24). Farmers sell directly at procurement centres.',
    eligibility_ta: 'TN-ல் அனைத்து நெல் விவசாயிகள். TNCSC குறைந்தபட்ச ஆதார விலையில் கொள்முதல் (₹2,183/குவிண்டால்).',
    how_to_apply_en: 'Register at nearest TNCSC procurement centre with patta, Aadhaar, and bank details before harvest season.',
    source_url: 'https://www.tncsc.tn.gov.in',
  },
  {
    id: 'kcc',
    name_en: 'Kisan Credit Card (KCC)',
    name_ta: 'கிசான் கிரெடிட் கார்டு',
    dept_id: 'agriculture',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central (interest subvention 2%)',
    origin_year: 1998,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '32 lakh farmers with KCC in TN',
    eligibility_en: 'All farmers, sharecroppers, and tenant farmers. Revolving credit limit based on land and crop. Interest subvention reduces rate to 4% p.a.',
    eligibility_ta: 'அனைத்து விவசாயிகள், குத்தகை விவசாயிகள். சுழல் கடன் வசதி. வட்டி சலுகையுடன் 4% வட்டி மட்டும்.',
    how_to_apply_en: 'Apply at nearest bank, cooperative bank, or RRB with land records, identity proof, and passport photo.',
    source_url: 'https://www.nabard.org/kcc',
  },
  {
    id: 'soil-health-card',
    name_en: 'Soil Health Card Scheme',
    name_ta: 'மண் ஆரோக்கிய அட்டை திட்டம்',
    dept_id: 'agriculture',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State',
    origin_year: 2015,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '82 lakh farmers',
    eligibility_en: 'All farmers in Tamil Nadu — free soil testing every 2 years with fertiliser use recommendations. Reduces fertiliser costs by 10–20%.',
    eligibility_ta: 'TN-ல் அனைத்து விவசாயிகள் — இலவச மண் பரிசோதனை, உர பரிந்துரை. இரண்டு ஆண்டுக்கு ஒரு முறை.',
    how_to_apply_en: 'Contact nearest Agriculture Extension Officer or apply at Agriculture Department office. Sample collection done at farm.',
    source_url: 'https://soilhealth.dac.gov.in',
  },
  {
    id: 'nfsm',
    name_en: 'National Food Security Mission (NFSM)',
    name_ta: 'தேசிய உணவு பாதுகாப்பு திட்டம்',
    dept_id: 'agriculture',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2007,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '20 lakh farmers in TN',
    eligibility_en: 'Farmers growing rice, wheat, and pulses — free certified seeds, demonstrations, farm mechanisation, and irrigation. Focus on low productivity districts.',
    eligibility_ta: 'நெல், கோதுமை, பருப்பு வகைகள் விளைவிக்கும் விவசாயிகள் — இலவச சான்றிதழ் விதைகள், விவசாய இயந்திரங்கள்.',
    how_to_apply_en: 'Apply through nearest Agriculture Extension Office. Beneficiaries selected based on land size and crop type.',
    source_url: 'https://www.tn.gov.in/agriculture',
  },

  // HEALTH - extended
  {
    id: 'moovalur-ramamirtham',
    name_en: 'Moovalur Ramamirtham Ammaiyar Ninaivu Scheme',
    name_ta: 'மூவலூர் ராமாமிர்தம் அம்மையார் நினைவு திட்டம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1989,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '5 lakh women per year',
    eligibility_en: 'BPL women for safe delivery — ₹18,000 for SC/ST women, ₹12,000 for others on 4 institutional delivery visits. Includes nutrition kit.',
    eligibility_ta: 'BPL பெண்களுக்கு பாதுகாப்பான பிரசவம் — SC/ST பெண்களுக்கு ₹18,000, மற்றவர்களுக்கு ₹12,000. ஊட்டச்சத்து கிட்டும் வழங்கப்படும்.',
    how_to_apply_en: 'Register at nearest PHC during first antenatal check-up. ASHA worker will guide through 4-visit protocol.',
    source_url: 'https://www.tnhealth.tn.gov.in',
  },
  {
    id: 'national-health-mission',
    name_en: 'National Health Mission (NHM)',
    name_ta: 'தேசிய சுகாதார திட்டம் (NHM)',
    dept_id: 'health',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2005,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: 'All 8 crore TN citizens',
    eligibility_en: 'All citizens — covers free OPD, inpatient care, maternal health, child immunisation, ASHA workers, and rural health infrastructure.',
    eligibility_ta: 'அனைத்து குடிமக்கள் — இலவச OPD, மருத்துவமனை சேர்க்கை, தாய்-சேய் சுகாதாரம், குழந்தை தடுப்பூசி.',
    how_to_apply_en: 'No application — visit nearest government hospital or PHC. ASHA workers provide doorstep services for maternal and child health.',
    source_url: 'https://nhm.gov.in',
    parent_scheme_en: 'Merged NHM Rural and Urban health missions',
  },
  {
    id: 'universal-immunisation',
    name_en: 'Universal Immunisation Programme (UIP)',
    name_ta: 'உலகளாவிய தடுப்பூசி திட்டம்',
    dept_id: 'health',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 1985,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '16 lakh children per year in TN',
    eligibility_en: 'All children aged 0–5 and pregnant women — 12 vaccines free including BCG, OPV, DPT, MMR, Hepatitis B, Typhoid, and COVID-19.',
    eligibility_ta: '0–5 வயது அனைத்து குழந்தைகளுக்கும் கர்ப்பிணி பெண்களுக்கும் — BCG, OPV, DPT, MMR உட்பட 12 தடுப்பூசிகள்.',
    how_to_apply_en: 'Register at nearest PHC or anganwadi. No charges. ASHA workers track and remind families.',
    source_url: 'https://nhm.gov.in',
  },
  {
    id: 'rb-free-dialysis',
    name_en: 'Free Dialysis Scheme',
    name_ta: 'இலவச டயாலிசிஸ் திட்டம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2017,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1 lakh patients per year',
    eligibility_en: 'All BPL patients with chronic kidney disease requiring dialysis. Free dialysis (3 sessions/week) at 264 government dialysis centres.',
    eligibility_ta: 'BPL நிரந்தர சிறுநீரக நோயாளிகள் — 264 அரசு மையங்களில் இலவச டயாலிசிஸ் (வாரம் 3 முறை).',
    how_to_apply_en: 'Apply at nearest government medical college hospital. Nephrologist referral required. BPL certificate needed.',
    source_url: 'https://www.tnhealth.tn.gov.in',
  },
  {
    id: 'tb-nikshay-poshan',
    name_en: 'Nikshay Poshan Yojana (TB Nutritional Support)',
    name_ta: 'நிக்ஷய் போஷண் யோஜனா (TB ஊட்டச்சத்து ஆதரவு)',
    dept_id: 'health',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2018,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '1.2 lakh TB patients in TN',
    eligibility_en: 'All TB patients under NIKSHAY programme — ₹500/month direct benefit transfer for nutrition support during treatment.',
    eligibility_ta: 'NIKSHAY திட்டத்தில் உள்ள அனைத்து TB நோயாளிகள் — சிகிச்சை காலத்தில் மாதம் ₹500 நேரடி நிதி உதவி.',
    how_to_apply_en: 'Automatic on TB diagnosis and registration under NIKSHAY at government hospital.',
    source_url: 'https://nikshay.in',
  },
  {
    id: 'makkalai-thedi-maruthuvam',
    name_en: 'Makkalai Thedi Maruthuvam (Doorstep Healthcare)',
    name_ta: 'மக்களை தேடி மருத்துவம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '2 crore screened per year',
    eligibility_en: 'All citizens — doorstep health screening by health workers every 3 months covering NCDs, hypertension, diabetes, and cancer screening.',
    eligibility_ta: 'அனைத்து குடிமக்களுக்கும் — 3 மாதத்திற்கு ஒரு முறை சுகாதார பணியாளர்களால் வீட்டிற்கு வந்து சுகாதார பரிசோதனை.',
    how_to_apply_en: 'No application — health workers visit every household. Identified patients referred to PHC for treatment.',
    source_url: 'https://www.tnhealth.tn.gov.in',
  },
  {
    id: 'vazhthugal',
    name_en: 'Vazhthugal — Elderly Care at Doorstep',
    name_ta: 'வாழ்த்துகள் — முதியோர் வீட்டுச் சேவை',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2023,
    origin_party: 'DMK',
    beneficiaries_claimed: '50 lakh senior citizens',
    eligibility_en: 'Persons aged 60 and above — home visits by health workers, medicine delivery, physiotherapy, and counselling services.',
    eligibility_ta: '60 வயதுக்கு மேற்பட்டவர்களுக்கு — சுகாதார பணியாளர்கள் வீட்டிற்கு வந்து சேவை, மருந்து வழங்கல்.',
    how_to_apply_en: 'Contact nearest PHC or call 104 health helpline. Health workers proactively enrol senior citizens.',
    source_url: 'https://www.tnhealth.tn.gov.in',
  },

  // RURAL DEVELOPMENT
  {
    id: 'mgnregs',
    name_en: 'MGNREGS — Mahatma Gandhi National Rural Employment Guarantee',
    name_ta: 'மகாத்மா காந்தி தேசிய ஊரக வேலை உத்தரவாதத் திட்டம்',
    dept_id: 'rural-development',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '90% Central / 10% State',
    origin_year: 2006,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '55 lakh households in TN',
    eligibility_en: 'All adult members of rural households who want unskilled manual work. 100 days of guaranteed employment at ₹281/day (TN 2024 wage).',
    eligibility_ta: 'கிராமப்புற குடும்பங்களின் அனைத்து வயது வந்த உறுப்பினர்கள். 100 நாள் வேலை உத்தரவாதம். ₹281/நாள் (TN 2024).',
    how_to_apply_en: 'Apply at Gram Panchayat for Job Card. Within 15 days of applying, employment must be provided or unemployment allowance paid.',
    source_url: 'https://nregs.tn.gov.in',
  },
  {
    id: 'jjm',
    name_en: 'Jal Jeevan Mission — Har Ghar Jal',
    name_ta: 'ஜல் ஜீவன் மிஷன் — ஒவ்வொரு வீட்டிலும் குழாய் நீர்',
    dept_id: 'rural-development',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State',
    origin_year: 2019,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '98.7 lakh rural households in TN',
    eligibility_en: 'All rural households — tap water connection at 55 litres per person per day. TN has achieved 98.7% household coverage.',
    eligibility_ta: 'அனைத்து கிராமப்புற குடும்பங்கள் — ஒருவருக்கு தினமும் 55 லிட்டர் குழாய் நீர் இணைப்பு. TN 98.7% மூடியிருக்கிறது.',
    how_to_apply_en: 'Contact Gram Panchayat or Block Office for connection. Village Water & Sanitation Committee manages local maintenance.',
    source_url: 'https://jaljeevanmission.gov.in',
  },
  {
    id: 'swachh-bharat-rural',
    name_en: 'Swachh Bharat Mission (Gramin) — ODF+',
    name_ta: 'ஸ்வச்ச் பாரத் மிஷன் (கிராமின்)',
    dept_id: 'rural-development',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2014,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: 'All 12,524 panchayats ODF',
    eligibility_en: 'BPL households — ₹12,000 subsidy for individual household toilet. TN has achieved ODF (open defecation free) status; now in ODF+ phase.',
    eligibility_ta: 'BPL குடும்பங்கள் — கழிப்பறை கட்ட ₹12,000 மானியம். TN ODF அந்தஸ்து பெற்றது; இப்போது ODF+ கட்டம்.',
    how_to_apply_en: 'Apply through Gram Panchayat. Funds released directly to beneficiary bank account before construction.',
    source_url: 'https://sbm.gov.in',
  },
  {
    id: 'deen-dayal-upadhyaya',
    name_en: 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)',
    name_ta: 'தீன் தயாள் உபாத்யாய கிராமீண கௌஷல்ய யோஜனா',
    dept_id: 'rural-development',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '75% Central / 25% State',
    origin_year: 2014,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '2 lakh rural youth trained in TN',
    eligibility_en: 'Rural youth aged 15–35 from BPL families — free residential skill training with placement guarantee for 70% of trained candidates.',
    eligibility_ta: 'BPL குடும்பங்களில் 15–35 வயது கிராமப்புற இளைஞர்கள் — இலவச குடியிருப்பு திறன் பயிற்சி.',
    how_to_apply_en: 'Apply through nearest TNSDC or DDU-GKY training centre. Training, boarding, food, and placement support all free.',
    source_url: 'https://ddugky.gov.in',
  },
  {
    id: 'selvamagal-savings',
    name_en: 'Selvamagal Savings Scheme (Sukanya Samriddhi TN)',
    name_ta: 'செல்வமகள் சேமிப்பு திட்டம்',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2014,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '20 lakh girl children',
    eligibility_en: 'Families with girl children below 10 years — ₹15,000 deposited by government at birth; matures on girls\' 21st birthday with interest.',
    eligibility_ta: '10 வயதிற்கு கீழ் பெண் குழந்தைகளுக்கு — அரசு ₹15,000 வைப்பு; 21-ம் வயதில் வட்டியுடன் திரும்பப் பெறலாம்.',
    how_to_apply_en: 'Apply at nearest post office or nationalised bank with birth certificate and parents\' Aadhaar within first year of birth.',
    source_url: 'https://www.tn.gov.in',
    parent_scheme_en: 'Linked to central Sukanya Samriddhi Yojana',
  },
  {
    id: 'nrlm-srlm',
    name_en: 'TNRTP — Tamil Nadu Rural Transformation Project (NRLM)',
    name_ta: 'TN கிராமப்புற மாற்றம் திட்டம் (NRLM)',
    dept_id: 'rural-development',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% World Bank / 40% Central-State',
    origin_year: 2018,
    origin_party: 'State/Central/World Bank',
    beneficiaries_claimed: '25 lakh SHG members',
    eligibility_en: 'Rural women — formation into Self-Help Groups, credit linkage at 7% interest, capacity building, and enterprise support. 4.5 lakh SHGs in TN.',
    eligibility_ta: 'கிராமப்புற பெண்கள் — சுய உதவிக் குழுக்கள், 7% வட்டியில் கடன் இணைப்பு, திறன் மேம்பாடு.',
    how_to_apply_en: 'Contact nearest Block Resource Centre or district TNRTP office. Form SHG with 10–15 women.',
    source_url: 'https://tnsrlm.tn.gov.in',
  },
  {
    id: 'pmgdisha',
    name_en: 'PM Gramin Digital Saksharta Abhiyan (PMGDISHA)',
    name_ta: 'PM கிராமீண டிஜிட்டல் சாக்ஷரதா அபியான்',
    dept_id: 'rural-development',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2017,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '18 lakh rural households trained in TN',
    eligibility_en: 'Rural households without a digitally literate member — free computer/smartphone literacy training, UPI, and online service navigation.',
    eligibility_ta: 'டிஜிட்டல் அறிவு இல்லாத கிராமப்புற குடும்பங்கள் — இலவச கணினி, UPI, ஆன்லைன் சேவை பயிற்சி.',
    how_to_apply_en: 'Register at Common Service Centre (CSC) or Gram Panchayat. One member per household.',
    source_url: 'https://www.pmgdisha.in',
  },

  // HOUSING
  {
    id: 'kalaignar-illam',
    name_en: 'Kalaignar Illam Thittam (Urban Housing)',
    name_ta: 'கலைஞர் இல்லம் திட்டம்',
    dept_id: 'housing',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2022,
    origin_party: 'DMK',
    beneficiaries_claimed: '4 lakh urban slum families',
    eligibility_en: 'Urban slum dwellers without own house — 2 BHK housing units provided free or at subsidised cost in integrated townships.',
    eligibility_ta: 'சொந்த வீடு இல்லாத நகர்ப்புற குடிசை குடும்பங்கள் — 2 BHK வீடுகள் இலவசமாக அல்லது மானிய விலையில்.',
    how_to_apply_en: 'Apply at Greater Chennai Corporation or district collectorate. Allotment by lottery from eligible slum dwellers list.',
    source_url: 'https://tnhb.gov.in',
  },
  {
    id: 'pmay-urban',
    name_en: 'PM Awas Yojana Urban (PMAY-U)',
    name_ta: 'PM ஆவாஸ் யோஜனா நகர்ப்புறம்',
    dept_id: 'housing',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State-beneficiary',
    origin_year: 2015,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '4.4 lakh urban houses sanctioned in TN',
    eligibility_en: 'Urban poor without own house — EWS, LIG, MIG categories. Interest subsidy 3–6.5% on home loans under Credit Linked Subsidy Scheme.',
    eligibility_ta: 'சொந்த வீடு இல்லாத நகர்ப்புற ஏழைகள் — EWS, LIG, MIG பிரிவுகள். வீட்டு கடனில் 3–6.5% வட்டி மானியம்.',
    how_to_apply_en: 'Apply at Urban Local Body or TNHB office. Online at pmaymis.gov.in. Aadhaar, income certificate, and bank details required.',
    source_url: 'https://pmaymis.gov.in',
  },
  {
    id: 'cmda-slum-clearance',
    name_en: 'TNSCB Slum Clearance and Resettlement',
    name_ta: 'TNSCB குடிசை ஒழிப்பு மற்றும் மீள்குடியேற்றம்',
    dept_id: 'housing',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1970,
    origin_party: 'State scheme',
    beneficiaries_claimed: '2 lakh slum families resettled',
    eligibility_en: 'Families in notified slums and objectionable localities — resettlement to permanent tenements. Priority for long-term occupants.',
    eligibility_ta: 'அறிவிக்கப்பட்ட குடிசைப் பகுதிகளில் வசிக்கும் குடும்பங்கள் — நிரந்தர குடியிருப்புகளுக்கு மறுகுடியேற்றம்.',
    how_to_apply_en: 'TNSCB conducts census of slum areas. Families identified and assigned tenements based on dwelling size and duration.',
    source_url: 'https://tnscb.tn.gov.in',
  },

  // BC / MBC WELFARE
  {
    id: 'bc-scholarship',
    name_en: 'BC/MBC Post-Matric Scholarship',
    name_ta: 'BC/MBC பட்டப்பின் உதவித்தொகை',
    dept_id: 'bc-welfare',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State',
    origin_year: 1959,
    origin_party: 'State scheme',
    beneficiaries_claimed: '4 lakh BC/MBC students per year',
    eligibility_en: 'BC/MBC students pursuing degree and above — annual family income below ₹2.5 lakh. Maintenance allowance ₹570–₹1,200/month + course fees.',
    eligibility_ta: 'பட்டப்படிப்பு மேல் படிக்கும் BC/MBC மாணவர்கள் — குடும்ப வருமானம் ₹2.5 லட்சத்திற்கு கீழ். மாதம் ₹570–1,200 + படிப்பு கட்டணம்.',
    how_to_apply_en: 'Apply at National Scholarship Portal (scholarships.gov.in) or through institution. Aadhaar, caste certificate, and marks required.',
    source_url: 'https://scholarships.gov.in',
  },
  {
    id: 'minority-scholarship',
    name_en: 'Pre-Matric and Post-Matric Scholarship for Minorities',
    name_ta: 'சிறுபான்மையினர் பயிற்சி-முந்தைய மற்றும் பட்டப்பின் உதவித்தொகை',
    dept_id: 'bc-welfare',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2006,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '2.8 lakh minority students in TN',
    eligibility_en: 'Muslim, Christian, Sikh, Buddhist, Jain, and Zoroastrian students — family income below ₹2 lakh. Pre-matric: ₹600/year; Post-matric: ₹3,000–10,000.',
    eligibility_ta: 'முஸ்லிம், கிறிஸ்தவ, சீக்கிய, பௌத்த மாணவர்கள் — குடும்ப வருமானம் ₹2 லட்சத்திற்கு கீழ்.',
    how_to_apply_en: 'Apply at National Scholarship Portal. Minority community certificate and income certificate required.',
    source_url: 'https://scholarships.gov.in',
  },
  {
    id: 'bc-residential-school',
    name_en: 'BC/MBC Residential Schools and Hostels',
    name_ta: 'BC/MBC குடியிருப்பு பள்ளிகள் மற்றும் விடுதிகள்',
    dept_id: 'bc-welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1972,
    origin_party: 'State scheme',
    beneficiaries_claimed: '1.5 lakh students in hostels',
    eligibility_en: 'BC/MBC students from Classes 6–12 — free boarding, food, and education at 600+ residential schools and hostels across TN.',
    eligibility_ta: '6 முதல் 12-ம் வகுப்பு BC/MBC மாணவர்களுக்கு — 600+ குடியிருப்பு பள்ளிகள் மற்றும் விடுதிகளில் இலவச தங்குமிட, உணவு, கல்வி.',
    how_to_apply_en: 'Apply through Block Backward Classes Welfare Officer. Selection based on family income and academic merit.',
    source_url: 'https://bcmbcmw.tn.gov.in',
  },

  // ADI DRAVIDAR WELFARE
  {
    id: 'sc-scholarship',
    name_en: 'SC/ST Post-Matric Scholarship',
    name_ta: 'SC/ST பட்டப்பின் உதவித்தொகை',
    dept_id: 'adi-dravidar',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 1944,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '5 lakh SC/ST students per year in TN',
    eligibility_en: 'SC/ST students pursuing post-matriculation courses — no income limit for SC students. Covers tuition, maintenance, and reader allowance for PwD.',
    eligibility_ta: 'SC/ST மாணவர்கள் — SC மாணவர்களுக்கு வருமான வரம்பு இல்லை. கல்விக் கட்டணம், பராமரிப்பு கொடுப்பனவு.',
    how_to_apply_en: 'Apply at National Scholarship Portal with caste certificate, marks, and institution details. Auto-verified by government.',
    source_url: 'https://scholarships.gov.in',
  },
  {
    id: 'ambedkar-residential-school',
    name_en: 'Ambedkar Residential Schools (ADW)',
    name_ta: 'அம்பேத்கர் குடியிருப்பு பள்ளிகள்',
    dept_id: 'adi-dravidar',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1971,
    origin_party: 'State scheme',
    beneficiaries_claimed: '1.2 lakh SC/ST students in 1,200+ schools',
    eligibility_en: 'SC/ST students from Classes 1–12 — free residential education with nutritious food, uniform, books, and coaching for competitive exams.',
    eligibility_ta: '1 முதல் 12-ம் வகுப்பு SC/ST மாணவர்கள் — 1,200+ குடியிருப்பு பள்ளிகளில் இலவச கல்வி, உணவு, சீருடை.',
    how_to_apply_en: 'Apply through District Adi Dravidar Welfare Officer. Priority to orphans and children of single mothers.',
    source_url: 'https://adwelfare.tn.gov.in',
  },
  {
    id: 'arunthathiyar-scheme',
    name_en: 'Special Schemes for Arunthathiyar Community',
    name_ta: 'அருந்ததியர் சமூக சிறப்பு திட்டங்கள்',
    dept_id: 'adi-dravidar',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2009,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '15 lakh Arunthathiyar community members',
    eligibility_en: 'Arunthathiyar (Scheduled Caste sub-classification) — 3% internal reservation within SC quota, special scholarship ₹2,000/month for college students.',
    eligibility_ta: 'அருந்ததியர் சமூகம் — SC இடஒதுக்கீட்டில் 3% சிறப்பு இடஒதுக்கீடு, கல்லூரி மாணவர்களுக்கு மாதம் ₹2,000.',
    how_to_apply_en: 'Apply with Arunthathiyar caste certificate at nearest Adi Dravidar Welfare Office.',
    source_url: 'https://adwelfare.tn.gov.in',
  },
  {
    id: 'tribal-development',
    name_en: 'Tribal Sub-Plan and Forest Dwellers Welfare',
    name_ta: 'பழங்குடியினர் திட்ட நலன்',
    dept_id: 'adi-dravidar',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 1974,
    origin_party: 'Central/State',
    beneficiaries_claimed: '7.9 lakh tribal population in TN',
    eligibility_en: 'Scheduled Tribe population — land rights under Forest Rights Act, special housing, livestock support, drinking water in tribal areas.',
    eligibility_ta: 'TN-ல் 7.9 லட்சம் பழங்குடியினர் — வனவுரிமை சட்டம் நில உரிமை, சிறப்பு வீட்டுவசதி, கால்நடை ஆதரவு.',
    how_to_apply_en: 'Contact Tribal Welfare Officer in designated tribal blocks (Nilgiris, Dharmapuri, Salem, Vellore).',
    source_url: 'https://adwelfare.tn.gov.in',
  },

  // TRANSPORT - extended
  {
    id: 'free-bus-students',
    name_en: 'Free Bus Pass for Students',
    name_ta: 'மாணவர்களுக்கு இலவச பேருந்து பாஸ்',
    dept_id: 'transport',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1972,
    origin_party: 'State scheme',
    beneficiaries_claimed: '30 lakh students daily',
    eligibility_en: 'All students in government, government-aided and private schools/colleges — free travel on TNSTC and MTC buses to and from educational institutions.',
    eligibility_ta: 'அரசு, அரசு உதவி மற்றும் தனியார் பள்ளி/கல்லூரி மாணவர்கள் — கல்வி நிறுவனங்களுக்கு TNSTC, MTC பேருந்துகளில் இலவச பயணம்.',
    how_to_apply_en: 'Apply at school/college with institution letter and identity proof at TNSTC depot.',
    source_url: 'https://tnstc.in',
  },
  {
    id: 'free-bus-disabled',
    name_en: 'Free Bus Pass for Differently Abled',
    name_ta: 'மாற்றுத்திறனாளிகளுக்கு இலவச பேருந்து பாஸ்',
    dept_id: 'transport',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1985,
    origin_party: 'State scheme',
    beneficiaries_claimed: '5 lakh differently abled persons',
    eligibility_en: 'All persons with 40%+ disability — free travel on all government buses. One accompanying attendant also travels free.',
    eligibility_ta: '40% மேல் ஊனம் உள்ள மாற்றுத்திறனாளிகள் — அனைத்து அரசு பேருந்துகளில் இலவச பயணம். ஒரு உதவியாளரும் இலவசமாக பயணிக்கலாம்.',
    how_to_apply_en: 'Apply with disability certificate at nearest TNSTC depot or e-Sevai centre for permanent bus pass.',
    source_url: 'https://tnstc.in',
  },
  {
    id: 'metro-rail-green-chennai',
    name_en: 'Chennai Metro Rail Phase 2',
    name_ta: 'சென்னை மெட்ரோ ரயில் கட்டம் 2',
    dept_id: 'transport',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '20% Central / 20% State / 60% Loans',
    origin_year: 2021,
    origin_party: 'State/Central',
    beneficiaries_claimed: '40 lakh Chennai commuters (target)',
    eligibility_en: '118.9 km Phase 2 expansion across 3 corridors. Capital investment ₹63,246 Cr. Target: 40 lakh daily passengers by 2030.',
    eligibility_ta: 'மூன்று வழிகளில் 118.9 கி.மீ. விரிவாக்கம். ₹63,246 கோடி முதலீடு. 2030-ல் 40 லட்சம் பயணிகள்.',
    how_to_apply_en: 'No application — public infrastructure project. Metro fare from ₹10–60 for existing Phase 1 routes.',
    source_url: 'https://chennaimetrorail.org',
  },

  // ENERGY - extended
  {
    id: 'pm-surya-ghar',
    name_en: 'PM Surya Ghar Muft Bijli Yojana (Solar Rooftop)',
    name_ta: 'PM சூர்ய கர் இலவச மின்சாரம் (சோலார் கூரை)',
    dept_id: 'energy',
    scheme_type: 'centrally_sponsored',
    status: 'new',
    funding_ratio_en: '40% Central subsidy / 60% Loan',
    origin_year: 2024,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '5 lakh TN households (target)',
    eligibility_en: 'All residential consumers — 300 free units/month for 1 crore households nationally. Subsidy: ₹30,000 for 1kW, ₹60,000 for 2kW, ₹78,000 for 3kW+.',
    eligibility_ta: 'அனைத்து குடியிருப்பு நுகர்வோர் — 1kW-க்கு ₹30,000, 2kW-க்கு ₹60,000, 3kW+-க்கு ₹78,000 மானியம்.',
    how_to_apply_en: 'Apply at pmsuryaghar.gov.in or through TANGEDCO. Registered solar installers available through portal.',
    source_url: 'https://pmsuryaghar.gov.in',
  },
  {
    id: 'solar-power-agriculture',
    name_en: 'PM-KUSUM Solar Agriculture Pump Scheme',
    name_ta: 'PM-KUSUM சோலார் விவசாய பம்ப் திட்டம்',
    dept_id: 'energy',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '30% Central / 30% State / 40% Farmer',
    origin_year: 2019,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '50,000 farmers in TN (target)',
    eligibility_en: 'Farmers with grid-unconnected or diesel pump connections — solar pump up to 7.5 HP. 40% farmer contribution (with soft loan available).',
    eligibility_ta: 'கிரிட் இணைப்பு இல்லாத அல்லது டீசல் பம்ப் உள்ள விவசாயிகள் — 7.5 HP வரை சோலார் பம்ப். 40% விவசாயி பங்களிப்பு.',
    how_to_apply_en: 'Apply through TANGEDCO or Agriculture Department. Online at mnre.gov.in/schemes/solar-energy.',
    source_url: 'https://mnre.gov.in',
  },

  // LABOUR
  {
    id: 'construction-welfare-board',
    name_en: 'TN Construction Workers Welfare Board Schemes',
    name_ta: 'TN கட்டட தொழிலாளர் நலன் வாரிய திட்டங்கள்',
    dept_id: 'labour',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% Cess funded (employers)',
    origin_year: 1996,
    origin_party: 'State scheme',
    beneficiaries_claimed: '28 lakh registered construction workers',
    eligibility_en: 'Registered construction workers — death/accident compensation ₹2–5 lakh, housing loan ₹1 lakh, education grant ₹5,000–25,000, maternity ₹10,000.',
    eligibility_ta: 'பதிவு செய்யப்பட்ட கட்டட தொழிலாளர்கள் — மரண/விபத்து இழப்பீடு ₹2–5 லட்சம், வீட்டு கடன் ₹1 லட்சம்.',
    how_to_apply_en: 'Register at District Labour Office with employer certificate, 90-day work proof, and Aadhaar. Annual subscription ₹25.',
    source_url: 'https://tnconstruction.tn.gov.in',
  },
  {
    id: 'esi-scheme',
    name_en: 'Employees State Insurance (ESI) Scheme',
    name_ta: 'ஊழியர் மாநில காப்பீட்டுத் திட்டம் (ESI)',
    dept_id: 'labour',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '3.25% employer + 0.75% employee contribution',
    origin_year: 1952,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '1.5 crore insured persons in TN',
    eligibility_en: 'Employees earning up to ₹21,000/month in establishments with 10+ workers — free medical care for worker and family, sickness cash benefit, maternity leave pay.',
    eligibility_ta: 'மாதம் ₹21,000 வரை சம்பளம் பெறும் ஊழியர்கள் — இலவச மருத்துவ சிகிச்சை, நோய்க்கால பணம், பிரசவ கொடுப்பனவு.',
    how_to_apply_en: 'Employer registers establishment. Employee gets ESI card automatically. Access ESI dispensaries and hospitals across TN.',
    source_url: 'https://www.esic.in',
  },
  {
    id: 'tnsdc-skill',
    name_en: 'TNSDC Skill Training Programmes',
    name_ta: 'TNSDC திறன் பயிற்சி திட்டங்கள்',
    dept_id: 'labour',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '70% State / 30% Central (NSDC)',
    origin_year: 2013,
    origin_party: 'State scheme',
    beneficiaries_claimed: '6 lakh youth trained per year',
    eligibility_en: 'Youth aged 18–35 — 400+ skill courses across IT, construction, healthcare, automotive, and textiles. Free training with placement support. Stipend ₹1,000/month.',
    eligibility_ta: '18–35 வயது இளைஞர்கள் — 400+ திறன் படிப்புகள். இலவச பயிற்சி, வேலைவாய்ப்பு ஆதரவு. மாதம் ₹1,000 கொடுப்பனவு.',
    how_to_apply_en: 'Apply at TNSDC.in or nearest skill training centre. Aadhaar and educational qualification required.',
    source_url: 'https://www.tnsdc.in',
  },
  {
    id: 'pm-svanthi',
    name_en: 'PM SVANidhi — Street Vendor Loan Scheme',
    name_ta: 'PM SVANidhi — தெரு வணிகர் கடன் திட்டம்',
    dept_id: 'labour',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '100% Central (interest subsidy)',
    origin_year: 2020,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '2 lakh street vendors in TN',
    eligibility_en: 'Street vendors with certificate of vending — working capital loans ₹10,000 (first), ₹20,000 (second), ₹50,000 (third tranche). 7% interest subsidy.',
    eligibility_ta: 'தெரு வணிகர் சான்று உள்ள தெரு வணிகர்கள் — ₹10,000 (முதல்), ₹20,000 (இரண்டாம்), ₹50,000 (மூன்றாம்) வேலை மூலதன கடன்.',
    how_to_apply_en: 'Apply through Town Vending Committee or at nearest bank/microfinance institution. Vending certificate from municipality required.',
    source_url: 'https://pmsvanidhi.mohua.gov.in',
  },
  {
    id: 'unorganised-workers-welfare',
    name_en: 'TN Unorganised Workers Social Security Scheme',
    name_ta: 'TN அமைப்பு சாரா தொழிலாளர் சமூக பாதுகாப்பு',
    dept_id: 'labour',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2009,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1.5 crore unorganised workers',
    eligibility_en: 'Workers in unorganised sector — death compensation ₹2 lakh, accident disability ₹1 lakh, children education ₹3,000–8,000/year.',
    eligibility_ta: 'அமைப்பு சாரா துறை தொழிலாளர்கள் — மரண இழப்பீடு ₹2 லட்சம், விபத்து ஊனம் ₹1 லட்சம்.',
    how_to_apply_en: 'Register through employer or self-registration at District Labour Office. Annual premium ₹100.',
    source_url: 'https://www.labour.tn.gov.in',
  },

  // INDUSTRIES / MSME
  {
    id: 'cmegps',
    name_en: 'Chief Minister Employment Generation Programme (CMEGP)',
    name_ta: 'முதலமைச்சர் வேலைவாய்ப்பு உருவாக்கத் திட்டம்',
    dept_id: 'msme',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '50% State subsidy',
    origin_year: 2019,
    origin_party: 'AIADMK (expanded by DMK)',
    beneficiaries_claimed: '50,000 enterprises per year',
    eligibility_en: 'Individuals and SHGs aged 18–45 — subsidised loans for new enterprises up to ₹25 lakh (25–35% subsidy for SC/ST/women/minorities).',
    eligibility_ta: '18–45 வயது தனிநபர்கள் மற்றும் சுய உதவிக் குழுக்கள் — புதிய தொழில் தொடங்க ₹25 லட்சம் வரை மானியக் கடன்.',
    how_to_apply_en: 'Apply at MSME-DFO or District Industries Centre. Business plan and margin money required.',
    source_url: 'https://www.msmedi.gov.in',
  },
  {
    id: 'pmegp',
    name_en: 'Prime Minister Employment Generation Programme (PMEGP)',
    name_ta: 'பிரதம மந்திரி வேலைவாய்ப்பு உருவாக்கத் திட்டம்',
    dept_id: 'msme',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central subsidy (15–35%)',
    origin_year: 2008,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '20,000 new units/year in TN',
    eligibility_en: 'Individuals aged 18+ for manufacturing enterprises up to ₹50 lakh, services ₹20 lakh. 15–35% subsidy based on category and location.',
    eligibility_ta: '18 வயதுக்கு மேல் — உற்பத்தி ₹50 லட்சம், சேவை ₹20 லட்சம் வரை. SC/ST/பெண்களுக்கு 25–35% மானியம்.',
    how_to_apply_en: 'Apply online at kviconline.gov.in through KVIC/KVIB/DIC channels.',
    source_url: 'https://kviconline.gov.in/pmegpeportal',
  },
  {
    id: 'msme-credit-guarantee',
    name_en: 'Credit Guarantee Fund Trust for MSMEs (CGTMSE)',
    name_ta: 'MSME கடன் உத்தரவாத நிதி அறக்கட்டளை',
    dept_id: 'msme',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '75% Central / 25% SIDBI',
    origin_year: 2000,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '1.2 lakh MSMEs in TN',
    eligibility_en: 'New and existing MSMEs without collateral — credit guarantee for loans up to ₹5 crore. Bank can approve without security.',
    eligibility_ta: 'பிணை இல்லாத புதிய மற்றும் ஏற்கனவே இருக்கும் MSME — ₹5 கோடி வரை கடன் உத்தரவாதம்.',
    how_to_apply_en: 'Apply through any scheduled bank. Bank applies to CGTMSE for guarantee. No direct application needed from entrepreneur.',
    source_url: 'https://www.cgtmse.in',
  },
  {
    id: 'gem-portal-tn',
    name_en: 'Government e-Marketplace (GeM) for TN MSMEs',
    name_ta: 'அரசு இ-சந்தை (GeM) — TN MSME',
    dept_id: 'msme',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '100% Central (platform)',
    origin_year: 2016,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '80,000 TN sellers on GeM',
    eligibility_en: 'All MSMEs, artisans, and SHGs — register on GeM to sell directly to government. 25% mandatory government procurement from MSMEs.',
    eligibility_ta: 'அனைத்து MSME, கைவினைஞர்கள், சுய உதவிக் குழுக்கள் — GeM-ல் பதிவு செய்து அரசிடம் நேரடியாக விற்கலாம்.',
    how_to_apply_en: 'Register at gem.gov.in with GSTN, bank account, and business registration. No fees to register as seller.',
    source_url: 'https://gem.gov.in',
  },

  // FISHERIES
  {
    id: 'pmmsy-fisheries',
    name_en: 'PM Matsya Sampada Yojana (PMMSY)',
    name_ta: 'PM மத்ஸ்ய சம்பதா யோஜனா',
    dept_id: 'fisheries',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2020,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '5 lakh fishermen in TN',
    eligibility_en: 'Fishermen, fish farmers, and SHGs — subsidised boats, nets, cold storage, fish markets, and aquaculture pond development. ₹40% subsidy for general, 60% for SC/ST/women.',
    eligibility_ta: 'மீனவர்கள், மீன் வளர்ப்பாளர்கள் — மானியத்தில் படகு, வலை, குளிர் சேமிப்பு, மீன் சந்தை, மீன்வளர்ப்பு குளம்.',
    how_to_apply_en: 'Apply through District Fisheries Officer with fishing licence, Aadhaar, and bank details.',
    source_url: 'https://pmmsy.dof.gov.in',
  },
  {
    id: 'fishermen-safety-insurance',
    name_en: 'Group Accident Insurance for Fishermen',
    name_ta: 'மீனவர்களுக்கு குழு விபத்து காப்பீடு',
    dept_id: 'fisheries',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded (premium)',
    origin_year: 1980,
    origin_party: 'State scheme',
    beneficiaries_claimed: '3.5 lakh active fishermen',
    eligibility_en: 'Active marine and inland fishermen — ₹5 lakh death/total disability cover; ₹2.5 lakh for partial disability. Premium paid by state government.',
    eligibility_ta: 'கடல் மற்றும் உள்நாட்டு மீனவர்கள் — மரணம்/முழு ஊனம் ₹5 லட்சம்; பகுதி ஊனம் ₹2.5 லட்சம். பிரீமியம் அரசு செலுத்தும்.',
    how_to_apply_en: 'Register at nearest Fisheries Department office. Active fishing licence required.',
    source_url: 'https://www.fisheries.tn.gov.in',
  },
  {
    id: 'kizhakku-kadal-scheme',
    name_en: 'Deep Sea Fishing Vessel Scheme',
    name_ta: 'ஆழ்கடல் மீன்பிடி திட்டம்',
    dept_id: 'fisheries',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% Beneficiary loan',
    origin_year: 2002,
    origin_party: 'Central/State',
    beneficiaries_claimed: '5,000 deep-sea fishing vessels supported',
    eligibility_en: 'Fishermen cooperatives and individuals — subsidy for mechanised boats over 20m, gill nets, purse seines, and navigation equipment for deep-sea fishing.',
    eligibility_ta: 'மீனவர் கூட்டுறவுகள் — 20 மீட்டருக்கு மேல் இயந்திரப் படகுகள், வலைகள், ஆழ்கடல் மீன்பிடி உபகரணங்களுக்கு மானியம்.',
    how_to_apply_en: 'Apply through Tamil Nadu Fisheries Development Corporation or Fisheries Department.',
    source_url: 'https://www.fisheries.tn.gov.in',
  },

  // YOUTH / SPORTS
  {
    id: 'cm-udan-sports',
    name_en: 'Chief Minister Udanila Vilaiyattu Thittam',
    name_ta: 'முதலமைச்சர் உடனிலா விளையாட்டு திட்டம்',
    dept_id: 'youth-sports',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '10 lakh grassroots sports youth',
    eligibility_en: 'School and college students at village/panchayat level — sports kits, playfields, coaching, and ₹10,000 cash award for district-level winners.',
    eligibility_ta: 'கிராம/பஞ்சாயத்து மட்டத்தில் பள்ளி மற்றும் கல்லூரி மாணவர்கள் — விளையாட்டு கிட், மைதானம், பயிற்சி, மாவட்ட வெற்றியாளருக்கு ₹10,000.',
    how_to_apply_en: 'Register through school or local Panchayat. Sports events organised at village, block, and district levels.',
    source_url: 'https://www.tn.gov.in/sports',
  },
  {
    id: 'khelo-india',
    name_en: 'Khelo India (Youth Sports Talent)',
    name_ta: 'கேலோ இந்தியா (இளைஞர் விளையாட்டு திறன்)',
    dept_id: 'youth-sports',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '75% Central / 25% State',
    origin_year: 2018,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '5,000 athletes in TN',
    eligibility_en: 'Under-18 talented athletes — ₹6.28 lakh per year for 8 years covering training, diet, coaching, equipment, insurance, and competitive exposure.',
    eligibility_ta: '18 வயதுக்கு கீழ் திறமையான விளையாட்டு வீரர்கள் — 8 ஆண்டுகளுக்கு ஆண்டுக்கு ₹6.28 லட்சம் பயிற்சி, உணவு, போட்டி செலவு.',
    how_to_apply_en: 'Selection through Khelo India talent identification camps. Apply via Sports Authority of Tamil Nadu.',
    source_url: 'https://kheloindia.gov.in',
  },
  {
    id: 'nss',
    name_en: 'National Service Scheme (NSS)',
    name_ta: 'தேசிய சேவை திட்டம் (NSS)',
    dept_id: 'youth-sports',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '75% Central / 25% State',
    origin_year: 1969,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '8 lakh NSS volunteers in TN',
    eligibility_en: 'College students aged 18–24 — 240 hours of community service. NSS badge, certificates, and Republic Day camp selection for outstanding volunteers.',
    eligibility_ta: '18–24 வயது கல்லூரி மாணவர்கள் — 240 மணி நேர சமூக சேவை. NSS பேட்ஜ், சான்றிதழ்கள்.',
    how_to_apply_en: 'Register through college NSS unit. Available in all government colleges and many aided colleges.',
    source_url: 'https://nss.tn.gov.in',
  },

  // ANIMAL HUSBANDRY
  {
    id: 'cattle-insurance',
    name_en: 'Cattle Insurance Scheme',
    name_ta: 'கால்நடை காப்பீட்டு திட்டம்',
    dept_id: 'animal-husbandry',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State (premium subsidy)',
    origin_year: 2010,
    origin_party: 'Central/State',
    beneficiaries_claimed: '10 lakh cattle insured in TN',
    eligibility_en: 'BPL farmers with cross-bred/high-yielding cattle — ₹50–500 premium for insurance covering 100% market value (average ₹40,000–70,000 per animal).',
    eligibility_ta: 'கலப்பினம்/அதிக விளைச்சல் கால்நடை உள்ள BPL விவசாயிகள் — ₹50–500 பிரீமியம், 100% சந்தை மதிப்பு காப்பீடு.',
    how_to_apply_en: 'Apply at nearest Veterinary Dispensary. Veterinary officer tags cattle and issues insurance certificate.',
    source_url: 'https://www.tn.gov.in/animalhusbandry',
  },
  {
    id: 'artificial-insemination',
    name_en: 'Free Artificial Insemination Service',
    name_ta: 'இலவச செயற்கை கருத்தரிப்பு சேவை',
    dept_id: 'animal-husbandry',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1998,
    origin_party: 'State scheme',
    beneficiaries_claimed: '25 lakh AI doses administered per year',
    eligibility_en: 'All cattle and buffalo farmers — free artificial insemination using imported quality semen for breed improvement. Delivered at farmer\'s doorstep by veterinary staff.',
    eligibility_ta: 'அனைத்து கால்நடை வளர்ப்போர் — இலவச செயற்கை கருத்தரிப்பு. ஆவணியர் வீட்டிற்கு வந்து சேவை செய்வார்.',
    how_to_apply_en: 'Call nearest Veterinary Dispensary or use INAPH app to request doorstep AI service.',
    source_url: 'https://www.tn.gov.in/animalhusbandry',
  },
  {
    id: 'pm-mathsya',
    name_en: 'Animal Husbandry Infrastructure Development Fund (AHIDF)',
    name_ta: 'கால்நடை உள்கட்டமைப்பு வளர்ச்சி நிதி',
    dept_id: 'animal-husbandry',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central credit-linked subsidy',
    origin_year: 2020,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '500+ dairy processing units',
    eligibility_en: 'Dairy co-operatives, farmer producer organisations, and private entrepreneurs — credit-linked subsidy for milk processing, dairy infrastructure, and meat processing.',
    eligibility_ta: 'பால் கூட்டுறவுகள், விவசாயி உற்பத்தியாளர் அமைப்புகள் — பால் பதப்படுத்தல், பால்பண்ணை உள்கட்டமைப்புக்கு மானியக் கடன்.',
    how_to_apply_en: 'Apply through NABARD or scheduled commercial bank for credit-linked subsidy.',
    source_url: 'https://dahd.nic.in',
  },

  // HIGHER EDUCATION
  {
    id: 'pudhumai-penn-college',
    name_en: 'Pudhumai Penn Scheme (College Level)',
    name_ta: 'புதுமைப் பெண் திட்டம் (கல்லூரி)',
    dept_id: 'higher-education',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2022,
    origin_party: 'DMK',
    beneficiaries_claimed: '1.4 lakh college women',
    eligibility_en: 'Women studying in government arts and science colleges — ₹1,000/month for UG, ₹1,500/month for PG. Encourages women from govt school background to pursue higher education.',
    eligibility_ta: 'அரசு கலை அறிவியல் கல்லூரிகளில் படிக்கும் பெண்கள் — UG-க்கு மாதம் ₹1,000, PG-க்கு மாதம் ₹1,500.',
    how_to_apply_en: 'Apply through college. Must have studied in government/aided school until Class 12.',
    source_url: 'https://www.tnhigheredu.tn.gov.in',
  },
  {
    id: 'naan-mudhalvan',
    name_en: 'Naan Mudhalvan — Employability Programme',
    name_ta: 'நான் முதல்வன் — வேலைவாய்ப்பு திறன் திட்டம்',
    dept_id: 'higher-education',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2022,
    origin_party: 'DMK',
    beneficiaries_claimed: '25 lakh students trained',
    eligibility_en: 'All students in government colleges and polytechnics — industry-aligned training in coding, communication, aptitude, and domain skills. Free industry certifications.',
    eligibility_ta: 'அரசு கல்லூரிகள் மற்றும் பாலிடெக்னிக் மாணவர்கள் — தொழில் சார்ந்த பயிற்சி, தொழில் நுட்பம், தகவல் தொடர்பு. இலவச சான்றிதழ்கள்.',
    how_to_apply_en: 'Automatic for all government college students. Access training at naanmudhalvan.tn.gov.in.',
    source_url: 'https://naanmudhalvan.tn.gov.in',
  },
  {
    id: 'free-laptop-scheme',
    name_en: 'Free Laptop Scheme for Government College Students',
    name_ta: 'அரசு கல்லூரி மாணவர்களுக்கு இலவச மடிக்கணினி',
    dept_id: 'higher-education',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2010,
    origin_party: 'DMK (restarted 2021)',
    beneficiaries_claimed: '3.5 lakh students per year',
    eligibility_en: 'Students in first year of government arts/science college and polytechnic courses — free laptop worth ₹25,000 to enable digital learning.',
    eligibility_ta: 'அரசு கலை/அறிவியல் கல்லூரி மற்றும் பாலிடெக்னிக் முதலாம் ஆண்டு மாணவர்கள் — ₹25,000 மதிப்புள்ள இலவச மடிக்கணினி.',
    how_to_apply_en: 'No application — distributed automatically to eligible first-year government college students.',
    source_url: 'https://www.tnhigheredu.tn.gov.in',
  },
  {
    id: 'pm-usha',
    name_en: 'PM USHA — Revitalising Infrastructure in Higher Education',
    name_ta: 'PM USHA — உயர் கல்வி உள்கட்டமைப்பு மேம்பாடு',
    dept_id: 'higher-education',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2023,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '12 universities in TN getting funds',
    eligibility_en: 'State universities — research labs, library upgrades, faculty development, and digital infrastructure. Replaces RUSA. TN universities get ₹1,500–3,000 Cr allocation.',
    eligibility_ta: 'மாநில பல்கலைக்கழகங்கள் — ஆராய்ச்சி ஆய்வகங்கள், நூலக மேம்பாடு, ஆசிரியர் மேம்பாடு, டிஜிட்டல் உள்கட்டமைப்பு.',
    how_to_apply_en: 'Applications through University Grants Commission. Universities apply for grants based on development plans.',
    source_url: 'https://education.gov.in',
    parent_scheme_en: 'Replaces RUSA (Rashtriya Uchchatar Shiksha Abhiyan)',
  },

  // MUNICIPAL / WATER
  {
    id: 'smart-cities',
    name_en: 'Smart Cities Mission (Chennai, Coimbatore, Madurai, Salem, Thanjavur, Tiruppur, Tirunelveli, Vellore, Thoothukudi)',
    name_ta: 'ஸ்மார்ட் சிட்டீஸ் திட்டம்',
    dept_id: 'municipal',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State + ULB',
    origin_year: 2015,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '1.5 crore urban citizens in 9 TN cities',
    eligibility_en: '9 Tamil Nadu cities — smart solutions for transport, solid waste, water, ICT command control centre, and area-based development.',
    eligibility_ta: 'TN-ல் 9 நகரங்கள் — போக்குவரத்து, திட கழிவு, நீர், ICT கட்டளை கட்டுப்பாடு மற்றும் பகுதி அடிப்படையிலான வளர்ச்சி.',
    how_to_apply_en: 'No citizen application — urban infrastructure project. Contact municipal corporation for service complaints.',
    source_url: 'https://smartcities.gov.in',
  },
  {
    id: 'swachh-bharat-urban',
    name_en: 'Swachh Bharat Mission (Urban) — Solid Waste',
    name_ta: 'ஸ்வச்ச் பாரத் மிஷன் (நகர்ப்புறம்) — திட கழிவு மேலாண்மை',
    dept_id: 'municipal',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State + ULB',
    origin_year: 2014,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '3.8 crore urban citizens',
    eligibility_en: 'All urban citizens — door-to-door waste collection, segregation infrastructure, bio-gas plants, and plastic waste management in all 676 urban local bodies.',
    eligibility_ta: 'அனைத்து நகர்ப்புற குடிமக்கள் — கதவுக்கு கதவு கழிவு சேகரிப்பு, பிரித்தல், 676 நகராட்சிகளில் கழிவு மேலாண்மை.',
    how_to_apply_en: 'No application — infrastructure delivered through municipalities. Complaint: municipality helpline.',
    source_url: 'https://sbmurban.org',
  },
  {
    id: 'cmwssb-water',
    name_en: 'CMWSSB — Chennai Water and Sewerage Expansion',
    name_ta: 'CMWSSB — சென்னை நீர் வழங்கல் விரிவாக்கம்',
    dept_id: 'municipal',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '70% State / 30% ADB loans',
    origin_year: 1978,
    origin_party: 'State scheme',
    beneficiaries_claimed: '45 lakh Chennai households',
    eligibility_en: 'All Chennai residents — 135 litres per person per day water supply target through pipeline expansion, desalination plants, and groundwater augmentation.',
    eligibility_ta: 'சென்னை குடியிருப்பாளர்கள் — ஒருவருக்கு தினமும் 135 லிட்டர் குழாய் நீர். நீர் நீக்கல் ஆலைகள், குழல் விரிவாக்கம்.',
    how_to_apply_en: 'New connections at CMWSSB zonal offices. Online at https://www.chennaimetrowater.tn.gov.in.',
    source_url: 'https://www.chennaimetrowater.tn.gov.in',
  },

  // DIFFERENTLY ABLED
  {
    id: 'special-schools-da',
    name_en: 'Special Schools for Differently Abled Children',
    name_ta: 'மாற்றுத்திறனாளி குழந்தைகளுக்கு சிறப்பு பள்ளிகள்',
    dept_id: 'differently-abled',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1965,
    origin_party: 'State scheme',
    beneficiaries_claimed: '60,000 differently abled students',
    eligibility_en: 'Children with visual, hearing, intellectual, locomotor disability — 183 government special schools with free education, residential facilities, and therapeutic support.',
    eligibility_ta: 'பார்வை, செவித்திறன், அறிவு, இயக்க ஊனம் உள்ள குழந்தைகள் — 183 அரசு சிறப்பு பள்ளிகளில் இலவச கல்வி, குடியிருப்பு.',
    how_to_apply_en: 'Apply at nearest District Differently Abled Welfare Office with disability certificate and birth certificate.',
    source_url: 'https://tnswdept.tn.gov.in/da',
  },
  {
    id: 'nils-scheme',
    name_en: 'National Institute for Locomotor Disabilities (NILD) Services',
    name_ta: 'நில ஊனமுற்றோர் சேவைகள்',
    dept_id: 'differently-abled',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 1978,
    origin_party: 'Central scheme',
    beneficiaries_claimed: '50,000 persons per year in TN',
    eligibility_en: 'Persons with locomotor disabilities — free physiotherapy, prosthetics, orthotics, and vocational training at government centres across TN.',
    eligibility_ta: 'இயக்க ஊனமுற்றோர் — அரசு மையங்களில் இலவச உடல் சிகிச்சை, செயற்கை கை/கால் பொருத்துதல், தொழில் பயிற்சி.',
    how_to_apply_en: 'Apply at Government Rehabilitation Centre or district hospital orthopaedic department.',
    source_url: 'https://msje.gov.in',
  },
]

export function getSchemesByDept(deptId: string): Scheme[] {
  return ALL_SCHEMES.filter(s => s.dept_id === deptId)
}

export function getSchemesByType(type: SchemeType): Scheme[] {
  return ALL_SCHEMES.filter(s => s.scheme_type === type)
}

export function getSchemeBySlug(slug: string): Scheme | undefined {
  return ALL_SCHEMES.find(s => s.id === slug)
}
