import { Scheme, SchemeType } from '@/types'

export const ALL_SCHEMES: Scheme[] = [
  // WELFARE
  {
    id: 'magalir-urimai',
    name_en: 'Kalaignar Magalir Urimai Thittam',
    name_ta: 'கலைஞர் மகளிர் உரிமைத் திட்டம்',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2023,
    origin_party: 'DMK',
    beneficiaries_claimed: '1.15 crore women',
    eligibility_en: 'Women aged 21 and above who are head of household. Excludes government employees, income tax payers. ₹1,000 per month direct to bank account.',
    eligibility_ta: '21 வயதுக்கு மேல் உள்ள குடும்பத் தலைவி பெண்கள். அரசு ஊழியர்கள் மற்றும் வருமான வரி செலுத்துவோர் விலக்கு.',
    how_to_apply_en: 'Apply at nearest ration shop or e-Sevai centre with Aadhaar, bank passbook, and ration card. Application is free.',
    source_url: 'https://magalir.tn.gov.in',
  },
  {
    id: 'samathuvapuram',
    name_en: 'Samathuvapuram Housing Scheme',
    name_ta: 'சமத்துவபுரம் வீட்டு திட்டம்',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1999,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1.5 lakh families housed',
    eligibility_en: 'BPL families including SC/ST, minorities, women-headed households — integrated housing in mixed communities.',
    eligibility_ta: 'BPL குடும்பங்கள் — SC/ST, சிறுபான்மையினர், பெண் தலைவியர் — கலப்பு சமூக வீட்டு வசதி.',
    how_to_apply_en: 'Apply at your Collectorate or Block Development Officer. Allotment through lottery among eligible applicants.',
    source_url: 'https://tnscb.tn.gov.in',
  },
  // HEALTH
  {
    id: 'cmchis',
    name_en: 'Chief Minister Comprehensive Health Insurance Scheme (CMCHIS)',
    name_ta: 'முதலமைச்சரின் விரிவான சுகாதார காப்பீட்டுத் திட்டம்',
    dept_id: 'health',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2012,
    origin_party: 'AIADMK',
    beneficiaries_claimed: '1.75 crore families',
    eligibility_en: 'BPL families and those earning below ₹72,000 per year. Annual health cover of ₹5 lakh per family for 1,027 procedures.',
    eligibility_ta: 'BPL குடும்பங்கள் மற்றும் ஆண்டு வருமானம் ₹72,000-க்கு கீழ் உள்ளவர்கள். 1,027 சிகிச்சைகளுக்கு ₹5 லட்சம் வரை.',
    how_to_apply_en: 'Register at nearest government hospital with Aadhaar, income certificate, and ration card. No premium payment required.',
    source_url: 'https://www.cmchistn.com',
  },
  {
    id: 'pmjay',
    name_en: 'Ayushman Bharat PM-JAY',
    name_ta: 'ஆயுஷ்மான் பாரத் PM-JAY',
    dept_id: 'health',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2018,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: 'Merged with CMCHIS in TN',
    eligibility_en: 'Bottom 40% households by income (SECC list). In TN, operationally merged with CMCHIS — use CMCHIS card.',
    eligibility_ta: 'கீழ் 40% வருமான குடும்பங்கள். TN-ல் CMCHIS-உடன் இணைக்கப்பட்டது.',
    how_to_apply_en: 'In Tamil Nadu, apply through CMCHIS at nearest ration shop. CMCHIS card is valid for PM-JAY benefits.',
    source_url: 'https://pmjay.gov.in',
    parent_scheme_en: 'Replaced RSBY (Rashtriya Swasthya Bima Yojana)',
  },
  {
    id: 'jsy',
    name_en: 'Janani Suraksha Yojana (JSY)',
    name_ta: 'ஜனனி சுரட்சா யோஜனா',
    dept_id: 'health',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2005,
    origin_party: 'UPA/Central',
    beneficiaries_claimed: '5 lakh deliveries per year',
    eligibility_en: 'All pregnant women delivering in government hospitals. ₹1,000 cash for institutional delivery in TN.',
    eligibility_ta: 'அரசு மருத்துவமனையில் பிரசவிக்கும் அனைத்து கர்ப்பிணி பெண்கள். ₹1,000 பணம்.',
    how_to_apply_en: 'Register at nearest PHC or govt hospital during antenatal check-up. ASHA worker will assist with paperwork.',
    source_url: 'https://nhm.gov.in',
  },
  // EDUCATION
  {
    id: 'puthumai-penn',
    name_en: 'Puthumai Penn Scheme',
    name_ta: 'புதுமைப் பெண் திட்டம்',
    dept_id: 'education',
    scheme_type: 'state',
    status: 'extended',
    funding_ratio_en: '100% State funded',
    origin_year: 2022,
    origin_party: 'DMK',
    beneficiaries_claimed: '5.4 lakh girl students per year',
    eligibility_en: 'Girls studying in government and government-aided schools. ₹1,000 per month from Class 6 to 12. Extended from govt-only to include aided schools in 2023.',
    eligibility_ta: 'அரசு மற்றும் அரசு உதவி பெறும் பள்ளிகளில் படிக்கும் மாணவிகள். 6 முதல் 12-ம் வகுப்பு வரை மாதம் ₹1,000.',
    how_to_apply_en: 'Apply through school principal. Benefits credited directly to student bank account.',
    source_url: 'https://www.tnschools.gov.in',
    parent_scheme_en: 'Same scheme — extended to aided schools in 2023',
  },
  {
    id: 'tamizh-pudhalvan',
    name_en: 'Tamizh Pudhalvan Scheme',
    name_ta: 'தமிழ் புதல்வன் திட்டம்',
    dept_id: 'education',
    scheme_type: 'state',
    status: 'new',
    funding_ratio_en: '100% State funded',
    origin_year: 2024,
    origin_party: 'DMK',
    beneficiaries_claimed: '4.2 lakh boy students',
    eligibility_en: 'Boys in government schools from Class 6 to 12. ₹1,000 per month to match Puthumai Penn parity.',
    eligibility_ta: 'அரசு பள்ளிகளில் படிக்கும் ஆண் மாணவர்கள். 6 முதல் 12-ம் வகுப்பு வரை மாதம் ₹1,000.',
    how_to_apply_en: 'Apply through school principal. Launched January 2024.',
    source_url: 'https://www.tnschools.gov.in',
  },
  {
    id: 'pm-poshan',
    name_en: 'PM POSHAN (Mid-Day Meal Scheme)',
    name_ta: 'PM போஷண் (மதிய உணவு திட்டம்)',
    dept_id: 'education',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 1995,
    origin_party: 'Central (renamed 2021)',
    beneficiaries_claimed: '66 lakh students daily',
    eligibility_en: 'All students in government and government-aided schools from Class 1 to 8. Free cooked meal every school day.',
    eligibility_ta: 'அரசு பள்ளிகளில் 1 முதல் 8-ம் வகுப்பு மாணவர்களுக்கு தினமும் இலவச சத்தான மதிய உணவு.',
    how_to_apply_en: 'No application needed. Automatic for all enrolled students in eligible schools.',
    source_url: 'https://pmposhan.education.gov.in',
    parent_scheme_en: 'Renamed from Mid-Day Meal Scheme in 2021',
  },
  {
    id: 'samagra-shiksha',
    name_en: 'Samagra Shiksha Abhiyan',
    name_ta: 'சமக்ர சிக்ஷா அபியான்',
    dept_id: 'education',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2018,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: 'All govt school students',
    eligibility_en: 'All students in government schools — covers infrastructure, teacher training, digital equipment, and textbooks.',
    eligibility_ta: 'அனைத்து அரசு பள்ளி மாணவர்கள் — கட்டமைப்பு, ஆசிரியர் பயிற்சி, டிஜிட்டல் கருவிகள்.',
    how_to_apply_en: 'No application — delivered through schools automatically.',
    source_url: 'https://samagrashiksha.in',
    parent_scheme_en: 'Merged SSA, RMSA, and TE schemes in 2018',
  },
  // REVENUE
  {
    id: 'pmay-gramin',
    name_en: 'PM Awas Yojana Gramin (PMAY-G)',
    name_ta: 'PM ஆவாஸ் யோஜனா கிராமின்',
    dept_id: 'revenue',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2016,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '8 lakh houses sanctioned in TN',
    eligibility_en: 'Homeless or inadequately housed families in rural areas — BPL, SC/ST, widows, differently-abled. ₹1.2 lakh per unit in plains, ₹1.3 lakh in hilly areas.',
    eligibility_ta: 'கிராமப்புறங்களில் வீடற்ற அல்லது பழுதடைந்த வீடுடைய குடும்பங்கள். ₹1.2 லட்சம் மானியம்.',
    how_to_apply_en: 'Apply through Block Development Office or Gram Panchayat. Beneficiaries selected from Socio-Economic Caste Census (SECC) list.',
    source_url: 'https://pmayg.nic.in',
  },
  // AGRICULTURE
  {
    id: 'pm-kisan',
    name_en: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    name_ta: 'PM-கிசான் (பிரதம மந்திரி கிசான் சம்மான் நிதி)',
    dept_id: 'agriculture',
    scheme_type: 'central',
    status: 'active',
    funding_ratio_en: '100% Central funded',
    origin_year: 2019,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '42 lakh farmers in TN',
    eligibility_en: 'All landholder farmer families with cultivable land. ₹6,000 per year in 3 instalments of ₹2,000 direct to bank account.',
    eligibility_ta: 'விவசாய நில உரிமையாளர் குடும்பங்கள். ஆண்டுக்கு ₹6,000 மூன்று தவணைகளில்.',
    how_to_apply_en: 'Register at nearest Common Service Centre or pmkisan.gov.in. Aadhaar, land record, and bank details required.',
    source_url: 'https://pmkisan.gov.in',
  },
  {
    id: 'pmfby',
    name_en: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    name_ta: 'பிரதம மந்திரி ஃபாஸல் பீமா யோஜனா',
    dept_id: 'agriculture',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State',
    origin_year: 2016,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '28 lakh farmers insured in TN',
    eligibility_en: 'All farmers growing notified crops. Premium: 2% for kharif, 1.5% for rabi, 5% for horticulture crops. Government pays the rest.',
    eligibility_ta: 'அனைத்து விவசாயிகள். பயிர் காப்பீட்டுக்கு 2% பிரீமியம் மட்டும் செலுத்தினால் போதும்.',
    how_to_apply_en: 'Apply through nearest bank, cooperative, or Common Service Centre before the crop season deadline. Aadhaar, land record required.',
    source_url: 'https://pmfby.gov.in',
  },
  // TRANSPORT
  {
    id: 'free-bus-women',
    name_en: 'Free Bus Pass for Women',
    name_ta: 'பெண்களுக்கு இலவச பேருந்து பாஸ்',
    dept_id: 'transport',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '1.5 crore women daily',
    eligibility_en: 'All women in Tamil Nadu — free travel on all TNSTC, MTC, and SETC buses. No income restriction.',
    eligibility_ta: 'தமிழ்நாட்டில் உள்ள அனைத்து பெண்களுக்கும் — TNSTC, MTC, SETC பேருந்துகளில் இலவச பயணம்.',
    how_to_apply_en: 'No application needed. Board any government bus and show identity if asked.',
    source_url: 'https://tnstc.in',
  },
  // ENERGY
  {
    id: 'free-100-units',
    name_en: 'Free 100 Units Electricity Scheme',
    name_ta: '100 இலவச மின் யூனிட் திட்டம்',
    dept_id: 'energy',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '2.8 crore domestic consumers',
    eligibility_en: 'All domestic electricity consumers using up to 100 units per month. No application — applied automatically on monthly bill.',
    eligibility_ta: 'மாதம் 100 யூனிட் வரை பயன்படுத்தும் வீட்டு நுகர்வோர். தானாகவே பில்லில் கழிக்கப்படும்.',
    how_to_apply_en: 'No application needed. Free units automatically applied to domestic consumer bills each month.',
    source_url: 'https://www.tangedco.gov.in',
  },
  // MUNICIPAL
  {
    id: 'amrut-2',
    name_en: 'AMRUT 2.0 (Atal Mission for Rejuvenation & Urban Transformation)',
    name_ta: 'AMRUT 2.0',
    dept_id: 'municipal',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '50% Central / 50% State',
    origin_year: 2021,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '3.8 crore urban citizens',
    eligibility_en: 'All urban citizens in cities with population over 1 lakh — water supply, sewerage, and urban green spaces.',
    eligibility_ta: '1 லட்சம் மக்கள்தொகை மேற்பட்ட நகரங்களில் நீர் விநியோகம், கழிவுநீர் மற்றும் பூங்காக்கள்.',
    how_to_apply_en: 'No direct application — benefits delivered through urban local bodies. Contact your municipality for connections.',
    source_url: 'https://amrut.gov.in',
  },
  // PWD
  {
    id: 'pmgsy',
    name_en: 'PMGSY — Pradhan Mantri Gram Sadak Yojana',
    name_ta: 'PM கிராம் சாலை யோஜனா',
    dept_id: 'pwd',
    scheme_type: 'centrally_sponsored',
    status: 'active',
    funding_ratio_en: '60% Central / 40% State',
    origin_year: 2000,
    origin_party: 'NDA/Central',
    beneficiaries_claimed: '12,000+ villages connected in TN',
    eligibility_en: 'All-weather road connectivity to habitations with population over 250. Over 12,000 villages connected in Tamil Nadu.',
    eligibility_ta: '250-க்கும் மேற்பட்ட மக்கள்தொகை உள்ள கிராமங்களுக்கு சர்வகால சாலை வசதி.',
    how_to_apply_en: 'Villages apply through Block Office. Connectivity priority set by state government based on population and connectivity gap.',
    source_url: 'https://pmgsy.nic.in',
  },
  // WELFARE - additional
  {
    id: 'widow-pension',
    name_en: 'Widow Pension Scheme',
    name_ta: 'விதவை ஓய்வூதியம்',
    dept_id: 'welfare',
    scheme_type: 'state',
    status: 'active',
    funding_ratio_en: '100% State funded',
    origin_year: 1962,
    origin_party: 'State scheme',
    beneficiaries_claimed: '16 lakh widows',
    eligibility_en: 'Widows below poverty line, not receiving any other pension, aged 18 and above. ₹1,000 per month.',
    eligibility_ta: 'வறுமைக் கோட்டிற்கு கீழ் உள்ள விதவைகள், வேறு ஓய்வூதியம் இல்லாதவர்கள். மாதம் ₹1,000.',
    how_to_apply_en: 'Apply at nearest Block Development Office with death certificate, Aadhaar, and income certificate.',
    source_url: 'https://tnswdept.tn.gov.in',
  },
  // AGRICULTURE - additional
  {
    id: 'crop-loan-waiver',
    name_en: 'Farm Loan Waiver Scheme',
    name_ta: 'விவசாய கடன் தள்ளுபடி திட்டம்',
    dept_id: 'agriculture',
    scheme_type: 'state',
    status: 'extended',
    funding_ratio_en: '100% State funded',
    origin_year: 2021,
    origin_party: 'DMK',
    beneficiaries_claimed: '16.4 lakh farmers',
    eligibility_en: 'Farmers with crop loans up to ₹1 lakh from cooperative banks waived. Phased payment to banks by state government.',
    eligibility_ta: 'கூட்டுறவு வங்கிகளில் ₹1 லட்சம் வரை கடன் உள்ள விவசாயிகள். அரசு படிப்படியாக வங்கிகளுக்கு செலுத்தும்.',
    how_to_apply_en: 'No separate application — farmers with eligible cooperative bank loans automatically included. Check with your bank.',
    source_url: 'https://www.tn.gov.in/agriculture',
  },
]

export function getSchemesByDept(deptId: string): Scheme[] {
  return ALL_SCHEMES.filter(s => s.dept_id === deptId)
}

export function getSchemesByType(type: SchemeType): Scheme[] {
  return ALL_SCHEMES.filter(s => s.scheme_type === type)
}

export function getSchemeBySlug(slug: string): Scheme | undefined {
  return ALL_SCHEMES.find(s => s.id === slug)
}
