export type TimelineEvent = {
  year: number
  month?: number
  event_en: string
  event_ta: string
  category: 'political' | 'policy' | 'economic' | 'social' | 'infrastructure' | 'legal' | 'disaster'
  cm?: string
  significance: 'high' | 'medium' | 'low'
  source_en?: string
}

export const TN_TIMELINE: TimelineEvent[] = [
  // 1947–1954 — Madras Province / Early Statehood
  { year: 1947, month: 8, event_en: 'India gains independence — Madras Province becomes part of Indian Union', event_ta: 'இந்தியா சுதந்திரம் பெற்றது — மதராஸ் மாகாணம் இந்திய யூனியனில் இணைந்தது', category: 'political', significance: 'high', source_en: 'Indian Independence Act 1947' },
  { year: 1948, event_en: 'Mahatma Gandhi assassinated — TN observes mourning', event_ta: 'மகாத்மா காந்தி படுகொலை — TN துக்கம் கொண்டாடியது', category: 'political', significance: 'high' },
  { year: 1949, event_en: 'Madras State University Act enacted; Annamalai University established', event_ta: 'மதராஸ் மாநில பல்கலைக்கழக சட்டம்; அண்ணாமலை பல்கலைக்கழகம் நிறுவப்பட்டது', category: 'social', significance: 'medium' },
  { year: 1950, month: 1, event_en: 'Constitution of India enacted — Madras Province renamed Madras State', event_ta: 'இந்திய அரசியலமைப்பு நடைமுறைக்கு வந்தது — மதராஸ் மாகாணம், மதராஸ் மாநிலம் ஆனது', category: 'legal', significance: 'high', source_en: 'Constitution of India 1950' },
  { year: 1952, event_en: 'First General Election — INC wins Madras State; C. Rajagopalachari becomes CM', event_ta: 'முதல் பொதுத்தேர்தல் — INC வெற்றி; C. ராஜகோபாலாச்சாரி முதலமைச்சர் ஆனார்', category: 'political', cm: 'C. Rajagopalachari', significance: 'high' },
  { year: 1952, event_en: 'Compulsory Hindi in schools — protests begin (precursor to 1965 agitation)', event_ta: 'பள்ளிகளில் கட்டாய இந்தி — எதிர்ப்பு தொடங்கியது (1965 போராட்டத்தின் தொடக்கம்)', category: 'social', significance: 'medium' },
  { year: 1953, event_en: 'Kulithalai bridge opens; irrigation expansion in Cauvery delta', event_ta: 'குளிட்டலை பாலம் திறப்பு; காவிரி டெல்டாவில் நீர்ப்பாசன விரிவாக்கம்', category: 'infrastructure', significance: 'low' },
  { year: 1954, event_en: 'K. Kamaraj becomes Chief Minister — begins transformative education push', event_ta: 'K. காமராஜர் முதலமைச்சர் ஆனார் — கல்வி மாற்றத்தை தொடங்கினார்', category: 'political', cm: 'K. Kamaraj', significance: 'high' },
  { year: 1954, event_en: 'Mid-day meal scheme launched for school children — first in India', event_ta: 'பள்ளி மாணவர்களுக்கு மதிய உணவு திட்டம் — இந்தியாவிலேயே முதல்', category: 'policy', cm: 'K. Kamaraj', significance: 'high', source_en: 'Tamil Nadu School Meal Scheme' },
  { year: 1956, event_en: 'States Reorganisation Act — TN boundaries set on linguistic basis; Coimbatore, Salem districts added', event_ta: 'மாநிலங்கள் மறுசீரமைப்பு சட்டம் — TN எல்லைகள் மொழி அடிப்படையில் நிர்ணயம்', category: 'political', significance: 'high', source_en: 'States Reorganisation Act 1956' },
  { year: 1956, event_en: 'TNEB (Tamil Nadu Electricity Board) established — rural electrification begins', event_ta: 'TNEB நிறுவப்பட்டது — கிராமப்புற மின்மயமாக்கல் தொடங்கியது', category: 'infrastructure', cm: 'K. Kamaraj', significance: 'high' },
  { year: 1957, event_en: 'Second General Election — INC retains Madras State; Kamaraj continues as CM', event_ta: 'இரண்டாம் பொதுத்தேர்தல் — INC தொடர்ந்து வெற்றி; காமராஜர் முதலமைச்சர் பதவி தொடர்ந்தார்', category: 'political', cm: 'K. Kamaraj', significance: 'medium' },
  { year: 1960, event_en: 'NLC (Neyveli Lignite Corporation) coal mining starts — energy independence milestone', event_ta: 'NLC (நெய்வேலி மரக்கரி கார்பொரேஷன்) நிலக்கரி சுரங்கம் — ஆற்றல் தன்னிறைவு மைல்கல்', category: 'economic', significance: 'high' },
  { year: 1961, event_en: 'Integral Coach Factory (ICF) Perambur commissioned — railway manufacturing hub', event_ta: 'ICF பெரம்பூர் தொடங்கியது — இந்தியாவின் ரயில் வண்டி தயாரிப்பு மையம்', category: 'economic', significance: 'high' },
  { year: 1962, event_en: 'Kamaraj Plan — senior Congress ministers resign to work for party organisation', event_ta: 'காமராஜர் திட்டம் — மூத்த காங்கிரஸ் மந்திரிகள் கட்சி வேலைக்கு ராஜினாமா', category: 'political', cm: 'K. Kamaraj', significance: 'high' },
  { year: 1963, event_en: 'M. Bhaktavatsalam becomes CM; Kamaraj becomes INC national president', event_ta: 'M. பக்தவத்சலம் முதலமைச்சர் ஆனார்; காமராஜர் INC தேசிய தலைவர்', category: 'political', cm: 'M. Bhaktavatsalam', significance: 'medium' },
  { year: 1965, event_en: 'Anti-Hindi agitation — violent protests against Hindi imposition; police firing kills 70+', event_ta: 'இந்தி எதிர்ப்பு போராட்டம் — வன்முறை ஆர்ப்பாட்டங்கள்; காவல் துறை சுடுதலில் 70+பேர் உயிரிழந்தனர்', category: 'political', significance: 'high', source_en: 'Official Inquiry Commission Report 1965' },
  { year: 1967, event_en: 'Third General Election — DMK wins; first non-Congress state government in India; C. N. Annadurai becomes CM', event_ta: 'மூன்றாம் பொதுத்தேர்தல் — DMK வெற்றி; இந்தியாவில் முதல் காங்கிரஸ் அல்லாத மாநில அரசு; C. N. அண்ணாதுரை முதலமைச்சர்', category: 'political', cm: 'C. N. Annadurai', significance: 'high' },
  { year: 1967, event_en: 'Two-language policy adopted — Tamil and English only in TN government', event_ta: 'இரு மொழி கொள்கை — தமிழ் மற்றும் ஆங்கிலம் மட்டும் TN அரசு மொழி', category: 'policy', cm: 'C. N. Annadurai', significance: 'high' },
  { year: 1969, event_en: 'C. N. Annadurai passes away — M. Karunanidhi becomes CM', event_ta: 'C. N. அண்ணாதுரை மரணம் — M. கருணாநிதி முதலமைச்சர்', category: 'political', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 1970, event_en: 'Madurai Airport inaugurated; first commercial airport outside Chennai', event_ta: 'மதுரை விமான நிலையம் திறப்பு; சென்னைக்கு வெளியே முதல் வணிக விமான நிலையம்', category: 'infrastructure', significance: 'medium' },
  { year: 1971, event_en: 'State renamed Tamil Nadu (from Madras State)', event_ta: 'மாநிலத்தின் பெயர் மதராஸ் மாநிலத்திலிருந்து தமிழ்நாடு என மாற்றப்பட்டது', category: 'political', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 1971, event_en: 'BHEL Tiruchirappalli plant commissioned — heavy engineering manufacturing', event_ta: 'BHEL திருச்சி ஆலை தொடங்கியது — கனரக பொறியியல் உற்பத்தி', category: 'economic', significance: 'medium' },
  { year: 1972, event_en: 'AIADMK formed by M. G. Ramachandran after split from DMK', event_ta: 'AIADMK நிறுவப்பட்டது — M. G. ராமச்சந்திரன் DMK-ஐ விட்டு பிரிந்து', category: 'political', significance: 'high' },
  { year: 1972, event_en: 'TNSTC (TN State Transport Corporation) reorganised; bus services expanded', event_ta: 'TNSTC மறுசீரமைப்பு; பேருந்து சேவைகள் விரிவாக்கம்', category: 'infrastructure', significance: 'medium' },
  { year: 1974, event_en: 'Kalpakkam nuclear plant construction begins — India\'s first indigenous reactor site', event_ta: 'கல்பாக்கம் அணுமின் நிலையம் கட்டுமானம் — இந்தியாவின் முதல் உள்நாட்டு அணு உலை', category: 'infrastructure', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 1975, event_en: 'Emergency declared nationally — DMK government dismissed; President\'s Rule in TN', event_ta: 'தேசிய அவசரநிலை — DMK அரசு பதவி நீக்கம்; TN-ல் குடியரசுத் தலைவர் ஆட்சி', category: 'political', significance: 'high' },
  { year: 1977, event_en: 'M. G. Ramachandran (MGR) wins TN election — AIADMK era begins', event_ta: 'M. G. ராமச்சந்திரன் தேர்தலில் வெற்றி — AIADMK ஆட்சி தொடங்கியது', category: 'political', cm: 'M. G. Ramachandran', significance: 'high' },
  { year: 1977, event_en: 'Noon Meal Scheme for school children expanded to all government schools', event_ta: 'பள்ளி மதிய உணவு திட்டம் — அனைத்து அரசு பள்ளிகளுக்கும் விரிவாக்கம்', category: 'policy', cm: 'M. G. Ramachandran', significance: 'high' },
  { year: 1979, event_en: 'Cyclone hits Nagapattinam — 10,000+ deaths; major disaster response effort', event_ta: 'நாகப்பட்டினம் புயல் — 10,000+ மரணங்கள்; பேரிடர் நிவாரண நடவடிக்கை', category: 'disaster', significance: 'high' },
  { year: 1981, event_en: 'First female collector in India appointed in TN', event_ta: 'இந்தியாவில் முதல் பெண் ஆட்சியர் TN-ல் நியமிக்கப்பட்டனர்', category: 'social', significance: 'medium' },
  { year: 1982, event_en: 'Madras Crocodile Bank and other conservation parks established in TN', event_ta: 'மதராஸ் முதலை பண்ணை மற்றும் பிற பாதுகாப்பு பூங்காக்கள் TN-ல் நிறுவப்பட்டன', category: 'social', significance: 'low' },
  { year: 1983, event_en: 'TASMAC formed — state monopoly on alcohol retail', event_ta: 'TASMAC நிறுவப்பட்டது — மது விற்பனையில் மாநில ஏகபோகம்', category: 'policy', cm: 'M. G. Ramachandran', significance: 'medium' },
  { year: 1984, event_en: 'Indira Gandhi assassinated; sympathy wave in elections; anti-Sikh riots not in TN', event_ta: 'இந்திரா காந்தி படுகொலை; தேர்தல் அனுதாப அலை; சீக்கிய எதிர்ப்பு கலவரம் TN-ல் இல்லை', category: 'political', significance: 'high' },
  { year: 1987, event_en: 'M. G. Ramachandran passes away — political transition; widow pension scheme had 20 lakh beneficiaries', event_ta: 'M. G. ராமச்சந்திரன் மரணம் — அரசியல் மாற்றம்; விதவை ஓய்வூதியம் 20 லட்சம் பயனாளிகள்', category: 'political', significance: 'high' },
  { year: 1988, event_en: 'Janaki Ramachandran becomes CM — first woman CM of TN; government collapses in 32 days', event_ta: 'ஜானகி ராமச்சந்திரன் முதலமைச்சர் — TN முதல் பெண் CM; 32 நாளில் அரசு வீழ்ந்தது', category: 'political', cm: 'Janaki Ramachandran', significance: 'high' },
  { year: 1989, event_en: 'Karunanidhi returns as CM; Eelam war in Sri Lanka — refugee crisis in TN', event_ta: 'கருணாநிதி மீண்டும் முதலமைச்சர்; இலங்கையில் ஈழப்போர் — TN-ல் அகதி நெருக்கடி', category: 'political', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 1991, event_en: 'Rajiv Gandhi assassinated at Sriperumbudur, Tamil Nadu — election postponed', event_ta: 'ஸ்ரீபெரும்புதூரில் ராஜீவ் காந்தி படுகொலை — தேர்தல் ஒத்திவைக்கப்பட்டது', category: 'political', significance: 'high', source_en: 'CBI Investigation Report' },
  { year: 1991, event_en: 'Economic liberalisation begins — TN positioned for industrial growth', event_ta: 'பொருளாதார தாராளமயமாக்கல் — TN தொழில் வளர்ச்சிக்கு தயாராகியது', category: 'economic', significance: 'high' },
  { year: 1991, event_en: 'J. Jayalalithaa becomes CM — first elected woman CM in TN history', event_ta: 'J. ஜெயலலிதா முதலமைச்சர் — TN வரலாற்றில் முதல் தேர்ந்தெடுக்கப்பட்ட பெண் CM', category: 'political', cm: 'J. Jayalalithaa', significance: 'high' },
  { year: 1993, event_en: 'TIDCO and SIPCOT expand — auto components industry cluster at Sriperumbudur grows', event_ta: 'TIDCO மற்றும் SIPCOT விரிவாக்கம் — ஸ்ரீபெரும்புதூரில் வாகன உதிரிபாகம் தொகுப்பு வளர்ந்தது', category: 'economic', significance: 'medium' },
  { year: 1994, event_en: '73rd/74th Constitutional Amendment — Panchayati Raj institutions strengthened in TN', event_ta: '73/74-ம் அரசியலமைப்பு திருத்தம் — TN-ல் பஞ்சாயத்து ராஜ் நிறுவனங்கள் வலுப்படுத்தப்பட்டன', category: 'legal', significance: 'medium' },
  { year: 1995, event_en: 'Hyundai Motor plant established at Sriperumbudur — first Korean auto investment', event_ta: 'ஹூண்டாய் ஆலை ஸ்ரீபெரும்புதூரில் — முதல் கொரிய வாகன முதலீடு', category: 'economic', significance: 'high', source_en: 'Hyundai Motor India' },
  { year: 1996, event_en: 'Karunanidhi wins — DMK government; major infrastructure push in highways', event_ta: 'கருணாநிதி வெற்றி — DMK அரசு; நெடுஞ்சாலைகளில் பெரும் உள்கட்டமைப்பு முயற்சி', category: 'political', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 1996, event_en: 'ELCOT and IT corridor concept announced — TN positions for software industry', event_ta: 'ELCOT மற்றும் IT வழி அறிவிப்பு — TN மென்பொருள் தொழிலுக்கு தயாரிப்பு', category: 'economic', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 1997, event_en: 'Southern Railway computerisation — CRIS project speeds ticketing in Chennai', event_ta: 'தென் ரயில்வே கணினிமயமாக்கல் — சென்னையில் டிக்கெட் சேவை முடுக்கிவிடப்பட்டது', category: 'infrastructure', significance: 'low' },
  { year: 1999, event_en: 'Jayalalithaa convicted in corruption cases — AIADMK loses 2001 election', event_ta: 'ஜெயலலிதா ஊழல் வழக்கில் தண்டிக்கப்பட்டனர் — AIADMK 2001 தேர்தலில் தோல்வி', category: 'political', significance: 'medium' },
  { year: 1999, event_en: 'Super Cyclone Odisha — TN coastal areas affected; disaster management improved', event_ta: 'ஒடிசா சூறாவளி — TN கடலோர பகுதிகள் பாதிக்கப்பட்டன; பேரிடர் மேலாண்மை மேம்பாடு', category: 'disaster', significance: 'medium' },
  { year: 2001, event_en: 'Jayalalithaa wins — AIADMK returns to power; Karunanidhi arrested', event_ta: 'ஜெயலலிதா வெற்றி — AIADMK மீண்டும் ஆட்சி; கருணாநிதி கைது', category: 'political', cm: 'J. Jayalalithaa', significance: 'high' },
  { year: 2002, event_en: 'Cauvery Water Dispute Tribunal — final award in 2007; inter-state water conflict', event_ta: 'காவிரி நீர் தகராறு நீதிமன்றம் — 2007-ல் இறுதி தீர்ப்பு; மாநிலங்களுக்கிடையே நீர் மோதல்', category: 'legal', significance: 'high' },
  { year: 2003, event_en: 'Amma Unavagam pilot starts — subsidised canteen concept (scaled up in 2011)', event_ta: 'அம்மா உணவகம் முன்னோடி — மானிய விலை உணவு அரங்கம் (2011-ல் விரிவாக்கம்)', category: 'policy', significance: 'medium' },
  { year: 2004, event_en: 'December 26 — Indian Ocean Tsunami devastates Tamil Nadu coast; 7,983 dead', event_ta: 'டிசம்பர் 26 — இந்திய மகாகடல் சுனாமி; TN கடற்கரை நாசம்; 7,983 உயிரிழப்பு', category: 'disaster', significance: 'high', source_en: 'Disaster Management Report 2004' },
  { year: 2005, event_en: 'RTI Act 2005 — Right to Information becomes law; TN implements', event_ta: 'RTI சட்டம் 2005 — தகவல் அறியும் உரிமை சட்டமானது; TN அமல்படுத்தியது', category: 'legal', significance: 'high', source_en: 'Right to Information Act 2005' },
  { year: 2005, event_en: 'Cognizant, TCS, Infosys expand in Chennai — IT export growth 40% per year', event_ta: 'Cognizant, TCS, Infosys சென்னையில் விரிவாக்கம் — IT ஏற்றுமதி 40% வருடாந்திர வளர்ச்சி', category: 'economic', significance: 'high' },
  { year: 2006, event_en: 'DMK wins — Karunanidhi becomes CM for fifth time; major welfare scheme expansion', event_ta: 'DMK வெற்றி — கருணாநிதி ஐந்தாவது முறை முதலமைச்சர்; நலன் திட்ட விரிவாக்கம்', category: 'political', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 2007, event_en: 'Free colour TV scheme — 1.48 crore TV sets distributed to BPL families', event_ta: 'இலவச வண்ண தொலைக்காட்சி திட்டம் — BPL குடும்பங்களுக்கு 1.48 கோடி TV வழங்கல்', category: 'policy', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 2008, event_en: 'MGNREGS implementation in TN — 45 lakh households enrolled', event_ta: 'MGNREGS TN-ல் செயல்படுத்தல் — 45 லட்சம் குடும்பங்கள் பதிவு', category: 'policy', significance: 'high' },
  { year: 2008, event_en: 'Ford India plant expands at Maraimalai Nagar — 10,000 jobs in auto sector', event_ta: 'Ford India ஆலை மாறைமலை நகரில் விரிவாக்கம் — வாகனத் துறையில் 10,000 வேலைவாய்ப்பு', category: 'economic', significance: 'medium' },
  { year: 2009, event_en: 'Siemens, Nokia, Samsung expand Chennai — mobile phone components exports begin', event_ta: 'Siemens, Nokia, Samsung சென்னை விரிவாக்கம் — கையடக்கத் தொலைபேசி உதிரிப்பொருள் ஏற்றுமதி தொடங்கியது', category: 'economic', significance: 'medium' },
  { year: 2010, event_en: 'Free laptop scheme launched for government college students — first in India', event_ta: 'அரசு கல்லூரி மாணவர்களுக்கு இலவச மடிக்கணினி — இந்தியாவிலேயே முதல்', category: 'policy', cm: 'M. Karunanidhi', significance: 'high' },
  { year: 2010, event_en: 'Chennai Port modernisation — container throughput reaches 1 million TEU', event_ta: 'சென்னை துறைமுக நவீனமயமாக்கல் — கொள்கலன் ஏற்றுமதி 10 லட்சம் TEU எட்டியது', category: 'infrastructure', significance: 'medium' },
  { year: 2011, event_en: 'AIADMK landslide — Jayalalithaa wins; Amma Canteen, Amma Water, Amma Pharmacy launched', event_ta: 'AIADMK வன்மையான வெற்றி — ஜெயலலிதா; அம்மா உணவகம், அம்மா குடிநீர், அம்மா மருந்தகம்', category: 'political', cm: 'J. Jayalalithaa', significance: 'high' },
  { year: 2011, event_en: 'Koodankulam nuclear plant nears completion — protests; Tamil Nadu power deficit addressed', event_ta: 'கூடங்குளம் அணு நிலையம் — எதிர்ப்பு போராட்டங்கள்; TN மின்சார பற்றாக்குறை நிவர்த்தி', category: 'infrastructure', significance: 'high' },
  { year: 2012, event_en: 'CMCHIS launched — ₹1 lakh health insurance for 1.75 crore families', event_ta: 'CMCHIS தொடங்கியது — 1.75 கோடி குடும்பங்களுக்கு ₹1 லட்சம் சுகாதார காப்பீடு', category: 'policy', cm: 'J. Jayalalithaa', significance: 'high' },
  { year: 2013, event_en: 'Cyclone Phailin narrowly misses TN; state disaster preparedness praised', event_ta: 'சூறாவளி ஃபைலின் TN-ஐ சேர்ந்து தாக்கவில்லை; மாநில பேரிடர் தயார்நிலை பாராட்டு', category: 'disaster', significance: 'low' },
  { year: 2014, event_en: 'TN achieves 100% village electrification — all 79,191 habitations electrified', event_ta: 'TN 100% கிராம மின்மயமாக்கல் — 79,191 குடியிருப்புகள் மின்சாரம் பெற்றன', category: 'infrastructure', significance: 'high', source_en: 'TANGEDCO Annual Report 2014' },
  { year: 2015, event_en: 'Chennai floods — 280 dead; ₹9,000 Cr losses; massive relief and rebuild', event_ta: 'சென்னை வெள்ளம் — 280 மரணம்; ₹9,000 கோடி இழப்பு; பெரும் நிவாரண மற்றும் மீளமைப்பு', category: 'disaster', significance: 'high', source_en: 'Chennai Metropolitan Authority Flood Report 2015' },
  { year: 2016, event_en: 'Jayalalithaa wins fifth term — AIADMK continues; she passes away in December', event_ta: 'ஜெயலலிதா ஐந்தாவது முறை வெற்றி — AIADMK தொடர்; டிசம்பரில் மரணம்', category: 'political', cm: 'J. Jayalalithaa', significance: 'high' },
  { year: 2017, event_en: 'E. K. Palaniswami becomes CM; Cauvery protests; jallikattu protest in Marina Beach', event_ta: 'E. K. பழனிசாமி முதலமைச்சர்; காவிரி போராட்டங்கள்; மரீனா கடற்கரையில் ஜல்லிக்கட்டு போராட்டம்', category: 'political', cm: 'E. K. Palaniswami', significance: 'high' },
  { year: 2017, event_en: 'Jallikattu ordinance passed — traditional bull-taming sport legalised after mass protest', event_ta: 'ஜல்லிக்கட்டு அவசரச் சட்டம் — கடும் போராட்டத்திற்குப் பிறகு பாரம்பரிய விளையாட்டு சட்டமயம்', category: 'legal', cm: 'E. K. Palaniswami', significance: 'high' },
  { year: 2018, event_en: 'Sterlite copper smelter protests — 13 killed in police firing in Tuticorin', event_ta: 'ஸ்டெர்லைட் செம்பு ஆலை எதிர்ப்பு — தூத்துக்குடியில் காவல் துறை சுடுதலில் 13 பேர் உயிரிழந்தனர்', category: 'political', significance: 'high', source_en: 'Madurai High Court Order' },
  { year: 2018, event_en: 'Sterlite plant permanently closed by TN government order', event_ta: 'ஸ்டெர்லைட் ஆலை TN அரசு ஆணையால் நிரந்தரமாக மூடப்பட்டது', category: 'policy', cm: 'E. K. Palaniswami', significance: 'high' },
  { year: 2019, event_en: 'Cyclone Gaja devastates Delta districts — 45 dead; paddy crop loss ₹4,000 Cr', event_ta: 'சூறாவளி கஜா டெல்டா மாவட்டங்களை சேதப்படுத்தியது — 45 மரணம்; நெல் பயிர் இழப்பு ₹4,000 கோடி', category: 'disaster', significance: 'high' },
  { year: 2019, event_en: 'GIM 2019 — Tamil Nadu Investment Meet; ₹3.23 lakh Cr investment intentions signed', event_ta: 'GIM 2019 — தமிழ்நாடு முதலீட்டாளர் கூட்டம்; ₹3.23 லட்சம் கோடி முதலீட்டு நோக்கங்கள்', category: 'economic', cm: 'E. K. Palaniswami', significance: 'high' },
  { year: 2019, event_en: 'Apple supplier Foxconn announces Sriperumbudur facility expansion — smartphone manufacturing', event_ta: 'Apple சப்ளையர் Foxconn ஸ்ரீபெரும்புதூர் விரிவாக்கம் — ஸ்மார்ட்போன் உற்பத்தி', category: 'economic', significance: 'high' },
  { year: 2020, event_en: 'COVID-19 pandemic — TN imposes early lockdown; 38,000+ COVID deaths; vaccine drive', event_ta: 'COVID-19 தொற்றுநோய் — TN முன்கூட்டியே ஊரடங்கு; 38,000+ கோவிட் மரணங்கள்; தடுப்பூசி பிரச்சாரம்', category: 'social', significance: 'high' },
  { year: 2020, event_en: 'TN extends PM-SVANidhi to 2 lakh street vendors — COVID livelihood support', event_ta: 'PM-SVANidhi திட்டம் 2 லட்சம் தெரு வணிகர்களுக்கு — கோவிட் வாழ்வாதார ஆதரவு', category: 'policy', significance: 'medium' },
  { year: 2021, event_en: 'DMK wins with 133/234 seats — M. K. Stalin becomes CM; first DMK government since 2011', event_ta: 'DMK 133/234 இடங்களில் வெற்றி — M. K. ஸ்டாலின் முதலமைச்சர்; 2011-க்குப் பிறகு முதல் DMK அரசு', category: 'political', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2021, event_en: 'Kalaignar Magalir Urimai — ₹1,000/month to 1.15 crore women announced', event_ta: 'கலைஞர் மகளிர் உரிமை — 1.15 கோடி பெண்களுக்கு மாதம் ₹1,000 அறிவிப்பு', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2021, event_en: 'Free bus pass for women launched — all government buses', event_ta: 'பெண்களுக்கு இலவச பேருந்து பாஸ் — அனைத்து அரசு பேருந்துகள்', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2021, event_en: 'Chief Minister Breakfast Scheme — free breakfast for 18 lakh school children', event_ta: 'முதலமைச்சர் காலை உணவு திட்டம் — 18 லட்சம் பள்ளி மாணவர்களுக்கு இலவச காலை உணவு', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2022, event_en: 'Puthumai Penn Scheme — ₹1,000/month for girl students in government schools', event_ta: 'புதுமைப் பெண் திட்டம் — அரசு பள்ளி மாணவிகளுக்கு மாதம் ₹1,000', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2022, event_en: 'Naan Mudhalvan — employability training for 25 lakh students launched', event_ta: 'நான் முதல்வன் — 25 லட்சம் மாணவர்களுக்கு வேலைவாய்ப்பு பயிற்சி தொடங்கியது', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2022, event_en: 'Cyclone Mandous — Chennai and Villupuram severely impacted; ₹500 Cr relief', event_ta: 'சூறாவளி மண்டோஸ் — சென்னை மற்றும் விழுப்புரம் கடுமையாக பாதிப்பு; ₹500 கோடி நிவாரணம்', category: 'disaster', significance: 'medium' },
  { year: 2022, event_en: 'TN Urban Employment Scheme — 100 days work for urban poor (first state-level urban MGNREGS equivalent)', event_ta: 'TN நகர்ப்புற வேலைவாய்ப்பு திட்டம் — நகர்ப்புற ஏழைகளுக்கு 100 நாள் வேலை (முதல் மாநில நகர்ப்புற MGNREGS)', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2023, event_en: 'Kalaignar Magalir Urimai fully operational — ₹13,800 Cr/year to 1.15 crore women', event_ta: 'கலைஞர் மகளிர் உரிமை முழு செயல்பாடு — 1.15 கோடி பெண்களுக்கு ஆண்டுக்கு ₹13,800 கோடி', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2023, event_en: 'Makkalai Thedi Maruthuvam — 2 crore screened in doorstep healthcare drive', event_ta: 'மக்களை தேடி மருத்துவம் — 2 கோடி பேர் வீட்டிலேயே சுகாதார பரிசோதனை', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2023, event_en: 'GIM 2024 announced — TN prepares for mega investor summit', event_ta: 'GIM 2024 அறிவிப்பு — TN மாபெரும் முதலீட்டாளர் மாநாட்டுக்கு தயார்', category: 'economic', significance: 'medium' },
  { year: 2023, event_en: 'Chennai Metro Phase 2 construction accelerates — ₹63,246 Cr project, 118 km', event_ta: 'சென்னை மெட்ரோ கட்டம் 2 கட்டுமானம் முடுக்கிவிடல் — ₹63,246 கோடி திட்டம், 118 கி.மீ.', category: 'infrastructure', significance: 'high' },
  { year: 2023, event_en: 'Tamizh Pudhalvan — ₹1,000/month extended to boy students to match Puthumai Penn', event_ta: 'தமிழ் புதல்வன் — ஆண் மாணவர்களுக்கும் மாதம் ₹1,000 — புதுமைப்பெண்ணுடன் சமநிலை', category: 'policy', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2024, event_en: 'GIM 2024 — ₹6.65 lakh Cr investment intentions; Apple, Tesla suppliers commit to TN', event_ta: 'GIM 2024 — ₹6.65 லட்சம் கோடி முதலீட்டு நோக்கங்கள்; Apple, Tesla சப்ளையர்கள் TN-க்கு', category: 'economic', cm: 'M. K. Stalin', significance: 'high' },
  { year: 2024, event_en: 'TN ranked No. 1 in ease of doing business — 3rd consecutive year', event_ta: 'TN வணிக இயல்பு மதிப்பீட்டில் முதல் இடம் — தொடர்ந்து 3-ம் ஆண்டு', category: 'economic', significance: 'high', source_en: 'DPIIT Ease of Doing Business Report' },
  { year: 2024, event_en: 'Cyclone Michaung — Chennai and north TN badly hit; ₹8,000 Cr infrastructure damage', event_ta: 'சூறாவளி மைக்கொங் — சென்னை மற்றும் வட TN கடுமையாக பாதிப்பு; ₹8,000 கோடி உள்கட்டமைப்பு சேதம்', category: 'disaster', significance: 'high' },
  { year: 2024, event_en: 'PM Surya Ghar Solar scheme — 5 lakh TN households enrolled for rooftop solar', event_ta: 'PM சூர்ய கர் சோலார் திட்டம் — 5 லட்சம் TN குடும்பங்கள் கூரை சோலார் பதிவு', category: 'policy', significance: 'medium' },
  { year: 2025, event_en: 'TN GSDP crosses ₹27 lakh Cr — third largest state economy in India', event_ta: 'TN GSDP ₹27 லட்சம் கோடியை தாண்டியது — இந்தியாவின் மூன்றாவது பெரிய மாநில பொருளாதாரம்', category: 'economic', significance: 'high', source_en: 'MOSPI / TN Economic Survey 2025' },
  { year: 2025, event_en: 'Semiconductor fabrication unit — TN signs MoU for India\'s second chip plant in Oragadam', event_ta: 'குறைக்கடத்தி தயாரிப்பு — TN ஒரகாடத்தில் இந்தியாவின் இரண்டாவது சிப் ஆலைக்கு MoU கையொப்பம்', category: 'economic', cm: 'M. K. Stalin', significance: 'high' },
]

export function getEventsByCategory(category: TimelineEvent['category']): TimelineEvent[] {
  return TN_TIMELINE.filter(e => e.category === category)
}

export function getEventsByDecade(from: number, to: number): TimelineEvent[] {
  return TN_TIMELINE.filter(e => e.year >= from && e.year < to)
}

export function getHighSignificanceEvents(): TimelineEvent[] {
  return TN_TIMELINE.filter(e => e.significance === 'high')
}
